'\" t
.\"     Title: apt-secure
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 28. Oktober 2008
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-SECURE" "8" "28\&. Oktober 2008" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-secure \- Archivauthentifizierungsunterstützung für APT
.SH "BESCHREIBUNG"
.PP
Beginnend mit Version 0\&.6 enthält
\fBapt\fR
Code, der die Signatur der Release\-Datei für alle Archive prüft\&. Dies stellt sicher, dass Pakete im Archiv nicht von Leuten geändert werden können, die keinen Zugriff auf den Signierschlüssel der Release\-Datei haben\&.
.PP
Wenn ein Paket aus einem Archiv ohne Signatur stammt oder einem mit Signatur, für das APT keinen Schlüssel hat, wird dieses Paket als nicht vertrauenswürdig angesehen und es zu installieren, führt zu einer großen Warnung\&.
\fBapt\-get\fR
wird aktuell nur bei nicht signierten Archiven warnen, zukünftige Releases könnten die Prüfung aller Quellen vor dem Herunterladen von Paketen von dort erzwingen\&.
.PP
Die Paketoberflächen
\fBapt-get\fR(8),
\fBaptitude\fR(8)
und
\fBsynaptic\fR(8)
unterstützen diese neue Authentifizierungsfunktion\&.
.SH "VERTRAUENSWüRDIGE ARCHIVE"
.PP
Eine Kette des Vertrauens von einem APT\-Archiv zum Endanwender wird durch verschiedene Schritte erreicht\&.
\fBapt\-secure\fR
ist der letzte Schritt in dieser Kette\&. Einem Archiv zu vertrauen bedeutet nicht, dass das Paket, dem Sie vertrauen, keinen schadhaften Code enthält, aber es bedeutet, dass Sie dem Archivbetreuer vertrauen\&. Der Archivbetreuer ist dafür verantwortlich, dass er die Korrektheit der Integrität des Archivs sicherstellt\&.
.PP
apt\-secure überprüft keine Signaturen auf einer Ebene des Pakets\&. Falls Sie ein Werkzeug benötigen, das dies tut, sollten Sie einen Blick auf
\fBdebsig\-verify\fR
und
\fBdebsign\fR
werfen (bereitgestellt von den Paketen debsig\-verify beziehungsweise devscripts)\&.
.PP
Die Kette des Vertrauens in Debian beginnt, wenn eine Betreuer ein neues Paket oder eine neue Version eines Pakets in das Debian\-Archiv hochlädt\&. Dieser Upload muss mit einem Schlüssel des Betreuers, der sich im Schlüsselring der Debian\-Betreuer befindet (verfügbar im Paket debian\-keyring) signiert werden\&. Betreuerschlüssel werden von anderen Betreuern gemäß vorbestimmter Regeln signiert, um die Identität des Schlüsselinhabers sicherzustellen\&.
.PP
Sobald das hochgeladenen Paket überprüft und in das Archiv hinzugefügt wurde, wird die Betreuersignatur entfernt, eine MD5\-Summe des Pakets berechnet und in die Paketdatei getan\&. Dann werden die MD5\-Summen aller Paketdateien berechnet und in die Release\-Datei getan\&. Dann wird die Release\-Datei durch den Archivschlüssel signiert (der einmal jährlich erzeugt und per FTP\-Server verteilt wird)\&. Dieser Schlüssel ist außerdem der Debian\-Schlüsselring\&.
.PP
Jeder Endanwender kann die Signatur der Release\-Datei prüfen, die MD5\-Summe eines Paketes daraus entpacken und mit der MD5\-Summe des Pakets vergleichen, das er heruntergeladen hat\&. Vor Version 0\&.6 wurde nur die MD5\-Summe des heruntergeladenen Debian\-Pakets geprüft\&. Nun werden sowohl die MD5\-Summe als auch die Signatur der Release\-Datei geprüft\&.
.PP
Beachten Sie, dass dies verschieden von geprüften Signaturen auf Paketbasis ist\&. Es wurde entworfen, um zwei mögliche Angriffe zu verhindern:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Network "man in the middle" attacks\&. Ohne Signaturprüfung kann ein schädlicher Mittelsmann sich selbst in das Herunterladen von Paketen einbringen und Schadsoftware bereitstellen\&. Dies kann entweder durch Kontrolle eines Netzwerkelements (Router, Switch, etc\&.) oder durch Umleiten des Netzverkehrs zu einem bösartigen Server (durch ARP\- oder DNS\-Manipulationsangriffe) erfolgen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mirror network compromise\&. Ohne Signaturprüfung kann ein schädlicher Mittelsmann einen Spiegelserver kompromittieren und die Dateien darauf verändern, um schädliche Software an alle Anwender zu verbreiten, die Pakete von diesem Rechner herunterladen\&.
.RE
.PP
Es schützt jedoch nicht gegen eine Kompromittierung des Haupt\-Debian\-Servers selbst (der die Pakete signiert) oder gegen eine Kompromittierung des Schlüssels, der zum Signieren der Release\-Dateien benutzt wird\&. In jedem Fall kann dieser Mechanismus eine Signatur pro Paket ergänzen\&.
.SH "BENUTZERKONFIGURATION"
.PP

\fBapt\-key\fR
ist das Programm, das die Liste der von APT verwendeten Schlüssel verwaltet\&. Es kann benutzt werden, um Schlüssel hinzuzufügen oder zu entfernen, obwohl eine Installation dieses Releases automatisch die Standard\-Debian\-Archivsignierschlüssel bereitstellt, die in den Debian\-Paketdepots benutzt werden\&.
.PP
Um einen neuen Schlüssel hinzuzufügen, müssen Sie ihn zuerst herunterladen (Sie sollten sicherstellen, dass Sie einen vertrauenswürdigen Kommunikationskanal benutzen, wenn Sie ihn herunterladen), ihn mit
\fBapt\-key\fR
hinzufügen und dann
\fBapt\-get update\fR
ausführen, so dass APT die
Release\&.gpg\-Dateien der von Ihnen konfigurierten Archive herunterladen und prüfen kann\&.
.SH "ARCHIVKONFIGURATION"
.PP
Wenn Sie Archivsignaturen in einem von Ihnen betreuten Archiv zur Verfügung stellen möchten, müssen Sie:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIErzeugen einer Release\-Datei der obersten Stufe\fR, wenn sie nicht bereits existiert\&. Sie können dies erledigen, indem Sie
\fBapt\-ftparchive release\fR
(aus apt\-utils) ausführen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIEs signieren\fR\&. Sie können dies tun, indem Sie
\fBgpg \-abs \-o Release\&.gpg Release\fR
ausführen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVeröffentlichen Sie den Schlüsselfingerabdruck\fR, damit Ihre Anwender wissen, welchen Schlüssel sie importieren müssen, um die Dateien im Archiv zu authentifizieren\&.
.RE
.PP
Immer wenn sich die Inhalte des Archivs ändern (neue Pakete hinzugefügt oder entfernt werden), muss der Archivbetreuen den beiden zuerst skizzierten Schritten folgen\&.
.SH "SIEHE AUCH"
.PP

\fBapt.conf\fR(5),
\fBapt-get\fR(8),
\fBsources.list\fR(5),
\fBapt-key\fR(8),
\fBapt-ftparchive\fR(1),
\fBdebsign\fR(1)
\fBdebsig-verify\fR(1),
\fBgpg\fR(1)
.PP
Um weitere Hintergrundinformationen zu erhalten, können Sie die
\m[blue]\fBDie Infrastruktur für Sicherheit in Debian\fR\m[]\&\s-2\u[1]\d\s+2\-Kapitel des Handbuchs \(FcAnleitung zum Absichern von Debian\(Fo (auch verfügbar im Paket harden\-doc) und dem
\m[blue]\fBStrong Distribution HOWTO\fR\m[]\&\s-2\u[2]\d\s+2
von V\&. Alex Brennen lesen\&.
.SH "FEHLER"
.PP
\m[blue]\fBAPT\-Fehlerseite\fR\m[]\&\s-2\u[3]\d\s+2\&. Wenn Sie einen Fehler in APT berichten möchten, lesen Sie bitte
/usr/share/doc/debian/bug\-reporting\&.txt
oder den
\fBreportbug\fR(1)\-Befehl\&. Verfassen Sie Fehlerberichte bitte auf Englisch\&.
.SH "AUTOR"
.PP
APT wurde vom APT\-Team geschrieben
apt@packages\&.debian\&.org\&.
.SH "AUTOREN DER HANDBUCHSEITE"
.PP
Diese Handbuchseite basiert auf der Arbeit von Javier Fernández\-Sanguino Peña, Isaac Jones, Colin Walters, Florian Weimer und Michael Vogt\&.
.SH "ÜBERSETZUNG"
.PP
Die deutsche Übersetzung wurde 2009 von Chris Leick
c\&.leick@vollbio\&.de
angefertigt in Zusammenarbeit mit dem Debian German\-l10n\-Team
debian\-l10n\-german@lists\&.debian\&.org\&.
.PP
Note that this translated document may contain untranslated parts\&. This is done on purpose, to avoid losing content when the translation is lagging behind the original content\&.
.SH "AUTHOR"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1998-2001 Jason Gunthorpe
.br
.SH "NOTES"
.IP " 1." 4
Die Infrastruktur für Sicherheit in Debian
.RS 4
\%http://www.debian.org/doc/manuals/securing-debian-howto/ch7.de.html
.RE
.IP " 2." 4
Strong Distribution HOWTO
.RS 4
\%http://www.cryptnet.net/fdp/crypto/strong_distro.html
.RE
.IP " 3." 4
APT-Fehlerseite
.RS 4
\%http://bugs.debian.org/src:apt
.RE
