'\" t
.\"     Title: apt-cache
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 29. Februar 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-CACHE" "8" "29\&. Februar 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-cache \- APT\-Werkzeug zur Handhabung von Paketen \-\- Zwischenspeichermanipulierer
.SH "SYNOPSIS"
.HP \w'\fBapt\-cache\fR\ 'u
\fBapt\-cache\fR [\fB\-hvsn\fR] [\fB\-o=\fR\fB\fIKonfigurationszeichenkette\fR\fR] [\fB\-c=\fR\fB\fIDatei\fR\fR] {[add\ \fIDatei\fR...] | [gencaches] | [showpkg\ \fIpkg\fR...] | [showsrc\ \fIpkg\fR...] | [stats] | [dump] | [dumpavail] | [unmet] | [search\ \fIregex\fR] | [show\ \fIpkg\fR...] | [depends\ \fIpkg\fR...] | [rdepends\ \fIPaket\fR...] | [pkgnames\ \fIPräfix\fR] | [dotty\ \fIPaket\fR...] | [xvcg\ \fIPaket\fR...] | [policy\ \fIPakete\fR...] | [madison\ \fIPakete\fR...]}
.SH "BESCHREIBUNG"
.PP
\fBapt\-cache\fR
führt eine Vielzahl von Operationen auf dem Paketzwischenspeicher von APT durch\&.
\fBapt\-cache\fR
manipuliert nicht den Status des Systems, stellt aber Operationen zum Suchen und Generieren von interessanten Ausgaben der Paket\-Metadaten bereit\&.
.PP
Sofern nicht die
\fB\-h\fR\-, oder
\fB\-\-help\fR\-Option angegeben ist, muss einer der unten aufgeführten Befehle vorkommen\&.
.PP
add \fIDatei(en)\fR
.RS 4
add
fügt die genannten Paket\-Index\-Dateien zum Paketzwischenspeicher hinzu\&. Dies dient nur der Fehlersuche\&.
.RE
.PP
gencaches
.RS 4
gencaches
führt die gleichen Operationen wie
\fBapt\-get check\fR
durch\&. Es bildet die Quellen\- und Paketzwischenspeicher aus den Quellen in
\fBsources.list\fR(5)
und von
/var/lib/dpkg/status\&.
.RE
.PP
showpkg \fIPaket(e)\fR
.RS 4
showpkg
zeigt Informationen über die auf der Befehlszeile aufgelisteten Pakete\&. Die übrigen Argumente sind Paketnamen\&. Die verfügbaren Versionen und Rückwärtsabhängigkeiten jedes aufgeführten Paketes werden ebenso aufgelistet, wie die Vorwärtsabhängigkeiten jeder Version\&. Vorwärtsabhängigkeiten (normale Abhängigkeiten) sind jene Pakete, von denen das betreffende Paket abhängt\&. Rückwärtsabhängigkeiten sind jene Pakete, die von dem betreffenden Paket abhängen\&. Deshalb müssen Vorwärtsabhängigkeiten für das Paket erfüllt werden, Rückwärtsabhängigkeiten allerdings nicht\&.
\fBapt\-cache showpkg libreadline2\fR
würde zum Beispiel eine Ausgabe ähnlich der folgenden erzeugen:
.sp
.if n \{\
.RS 4
.\}
.nf
Package: libreadline2
Versions: 2\&.1\-12(/var/state/apt/lists/foo_Packages),
Reverse Depends: 
  libreadlineg2,libreadline2
  libreadline2\-altdev,libreadline2
Dependencies:
2\&.1\-12 \- libc5 (2 5\&.4\&.0\-0) ncurses3\&.0 (0 (null))
Provides:
2\&.1\-12 \- 
Reverse Provides: 
.fi
.if n \{\
.RE
.\}
Dadurch sieht man, dass libreadline2, Version 2\&.1\-12, von libc5 und ncurses3\&.0 abhängt, die installiert sein müssen, damit libreadline2 funktioniert\&. Im Gegenzug hängen libreadlineg2 und libreadline2\-altdev von libreadline2 ab\&. Wenn libreadline2 installiert ist, müssen außerdem libc5 und ncurses3\&.0 (und ldso) installiert sein\&. Für die spezielle Bedeutung der restlichen Ausgabe ist es am besten, den apt\-Quelltext zu konsultieren\&.
.RE
.PP
stats
.RS 4
stats
zeigt einige Statistiken über den Zwischenspeicher\&. Es werden keine weiteren Argumente erwartet\&. Berichtete Statistiken sind:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total package names
ist die Gesamtzahl der im Zwischenspeicher gefundenen Pakete\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Normal packages
ist die Anzahl der regulären, gewöhnlichen Paketnamen\&. Diese sind Pakete, die eine Eins\-zu\-Eins\-Entsprechung zwischen ihren Namen und den Namen, die andere Pakete für ihre Abhängigkeiten benutzen, tragen\&. Die Mehrzahl der Pakete fällt in diese Kategorie\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pure virtual packages
ist die Anzahl der Pakete, die nur als ein virtueller Paketname existieren\&. Das kommt vor, wenn Pakete nur den virtuellen Paketnamen \(Fcbereitstellen\(Fo und aktuell kein Paket den Namen benutzt\&. Zum Beispiel ist im Debian\-GNU/Linux\-System \(Fcmail\-transport\-agent\(Fo ein rein virtuelles Paket\&. Mehrere Pakete stellen \(Fcmail\-transport\-agent\(Fo bereit, aber es gibt kein Paket mit dem Namen \(Fcmail\-transport\-agent\(Fo\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Single virtual packages
ist die Anzahl der Pakete mit nur einem Paket, das ein bestimmtes virtuelles Paket bereitstellt\&. \(FcX11\-text\-viewer\(Fo ist zum Beispiel im Debian\-GNU/Linux\-System ein virtuelles Paket, aber nur ein Paket, xless, stellt \(FcX11\-text\-viewer\(Fo bereit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mixed virtual packages
ist die Anzahl der Pakete, die entweder ein bestimmtes virtuelles Paket bereitstellen oder den virtuellen Paketnamen als Paketnamen haben\&. \(Fcdebconf\(Fo ist zum Beispiel sowohl ein tatsächliches Paket, wird aber auch vom Paket debconf\-tiny bereitgestellt\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Missing
ist die Anzahl der Paketnamen, auf die eine Abhängigkeit verweist, die aber von keinem Paket bereitgestellt werden\&. Fehlende Pakete könnten auftauchen, wenn nicht auf eine vollständige Distribution zugegriffen oder ein (echtes oder virtuelles) Paket aus einer Distribution gestrichen wurde\&. Normalerweise wird auf sie von Conflicts oder Breaks\-Angaben Bezug genommen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total distinct
Versionen ist die Anzahl der im Zwischenspeicher gefundenen Paketversionen\&. Dieser Wert ist daher meistens gleich der Anzahl der gesamten Paketnamen\&. Wenn auf mehr als eine Distribution (zum Beispiel \(Fcstable\(Fo und \(Fcunstable\(Fo zusammen) zugegriffen wird, kann dieser Wert deutlich größer als die gesamte Anzahl der Paketnamen sein\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total dependencies
ist die Anzahl der Abhängigkeitsbeziehungen, den alle Pakete im Zwischenspeicher beanspruchen\&.
.RE
.sp
.RE
.PP
showsrc \fIPaket(e)\fR
.RS 4
showsrc
zeigt alle Quellpaketdatensätze, die den angegebenen Paketnamen entsprechen\&. Alle Versionen werden ebenso angezeigt, wie alle Datensätze, die den Namen für ein Programm deklarieren\&.
.RE
.PP
dump
.RS 4
dump
zeigt einen kurzen Programmausdruck von jedem Paket im Zwischenspeicher\&. Es dient in erster Linie der Fehlersuche\&.
.RE
.PP
dumpavail
.RS 4
dumpavail
gibt eine verfügbare Liste auf stdout aus\&. Dies ist geeignet für die Benutzung mit
\fBdpkg\fR(1)
und wird für die
\fBdselect\fR(1)\-Methode benutzt\&.
.RE
.PP
unmet
.RS 4
unmet
zeigt die Zusammenfassung aller unerfüllten Abhängigkeiten im Paketzwischenspeicher\&.
.RE
.PP
show \fIPaket(e)\fR
.RS 4
show
führt eine Funktion aus, die
\fBdpkg \-\-print\-avail\fR
ähnlich ist\&. Es zeigt die Paketdatensätze für die genannten Pakete\&.
.RE
.PP
search \fIregex [ regex \&.\&.\&. ]\fR
.RS 4
search
führt eine Volltextsuche in der Liste aller verfügbaren Pakete für das gegebene POSIX\-regex\-Muster durch, siehe
\fBregex\fR(7)\&. Es durchsucht die Paketnamen und die Beschreibungen nach einem Vorkommen des regulären Ausdrucks und gibt den Paketnamen mit einer kurzen Beschreibung, einschließlich virtueller Paketnamen, aus\&. Wenn
\fB\-\-full\fR
angegeben wurde, ist die Ausgabe gleich der, die
show
für jedes Paket erzeugt und wenn
\fB\-\-names\-only\fR
angegeben wurde, wird die lange Beschreibung nicht durchsucht, sondern nur der Paketname\&.
.sp
Separate Argumente können benutzt werden, um mehrere Suchmuster anzugeben, die \(Fcund\(Fo\-verknüpft werden\&.
.RE
.PP
depends \fIPaket(e)\fR
.RS 4
depends
zeigt eine Liste von jeder Abhängigkeit, die ein Paket hat und alle möglichen anderen Pakete, die die Abhängigkeit erfüllen können\&.
.RE
.PP
rdepends \fIPaket(e)\fR
.RS 4
rdepends
zeigt eine Liste von jeder Rückwärtsabhängigkeit, die ein Paket hat\&.
.RE
.PP
pkgnames \fI[ Präfix ]\fR
.RS 4
Dieser Befehl gibt den Namen jedes Paketes aus, das APT kennt\&. Das optionale Argument ist ein passendes Präfix, um die Namensliste zu filtern\&. Die Ausgabe ist geeignet für die Benutzung in der Tabulatorvervollständigung in der Shell\&. Die Ausgabe wird extrem schnell generiert\&. Dieser Befehl wird am besten mit der
\fB\-\-generate\fR\-Option benutzt\&.
.sp
Beachten Sie, dass ein Paket, das APT kennt, nicht notwendigerweise zum Herunterladen verfügbar, installierbar oder installiert ist, virtuelle Pakete sind z\&.B\&. auch in der generierten Liste aufgeführt\&.
.RE
.PP
dotty \fIPaket(e)\fR
.RS 4
dotty
nimmt eine Paketliste auf der Befehlszeile entgegen und generiert eine Ausgabe, die für die Benutzung durch dotty aus dem Paket
\m[blue]\fBGraphViz\fR\m[]\&\s-2\u[1]\d\s+2
geeignet ist\&. Das Ergebnis ist eine Zusammenstellung von Knoten und Kanten, die die Beziehung zwischen Paketen darstellen\&. Standardmäßig werden alle abhängigen Pakete ausfindig gemacht\&. Dies kann zu einem sehr großen Schaubild führen\&. Um die Ausgabe auf die Pakete zu beschränken, die auf der Befehlszeile eingegeben wurden, setzen Sie die Option
APT::Cache::GivenOnly\&.
.sp
Die resultierenden Knoten haben mehrere Formen\&. Normale Pakete sind Kästchen, reine Bereitstellungen sind Dreiecke, gemischte Bereitstellungen sind Diamanten, fehlende Pakete sind Sechsecke\&. Orange Kästchen bedeuten, dass die Rekursion beendet wurde [Blattpakete], blaue Linien sind Pre\-depends, grüne Linien sind Konflikte\&.
.sp
Vorsicht, dotty kann keine größeren Zusammenstellungen von Paketen grafisch darstellen\&.
.RE
.PP
xvcg \fIPaket(e)\fR
.RS 4
Das gleiche wie
dotty, nur für xvcg vom
\m[blue]\fBVCG\-Werkzeug\fR\m[]\&\s-2\u[2]\d\s+2\&.
.RE
.PP
policy \fI[ Paket(e) ]\fR
.RS 4
policy
ist dazu gedacht, bei Fragen der Fehlersuche, die sich auf die Einstellungsdatei beziehen, zu helfen\&. Ohne Argumente gibt es die Prioritäten von jeder Quelle aus\&. Ansonsten gibt es umfangreiche Informationen über die Prioritätenauswahl der genannten Pakete aus\&.
.RE
.PP
madison \fI/[ Paket(e) ]\fR
.RS 4
apt\-caches
madison\-Befehl versucht das Ausgabeformat und eine Untermenge der Funktionalität des Debian\-Archivververwaltungswerkzeuges
madison
nachzuahmen\&. Es zeigt verfügbare Versionen eines Pakets in Tabellenform\&. Anders als das Original
madison, kann es nur Informationen für die Architektur anzeigen, für die APT Paketlisten heruntergeladen hat (APT::Architecture)\&.
.RE
.SH "OPTIONEN"
.PP
Alle Befehlszeilenoptionen können durch die Konfigurationsdatei gesetzt werden, die Beschreibung gibt die zu setzende Option an\&. Für boolesche Optionen können Sie die Konfigurationsdatei überschreiben, indem Sie etwas wie
\fB\-f\-\fR,
\fB\-\-no\-f\fR,
\fB\-f=no\fR
oder etliche weitere Varianten benutzen\&.
.PP
\fB\-p\fR, \fB\-\-pkg\-cache\fR
.RS 4
Wählt die Datei zum Speichern des Paketzwischenspeichers\&. Der Paketzwischenspeicher ist der primäre Zwischenspeicher, der von allen Operationen benutzt wird\&. Konfigurationselement:
Dir::Cache::pkgcache\&.
.RE
.PP
\fB\-s\fR, \fB\-\-src\-cache\fR
.RS 4
Wählt die Datei zum Speichern des Quellenzwischenspeichers\&. Die Quelle wird nur von
gencaches
benutzt und sie speichert eine ausgewertete Version der Paketinformationen von entfernt liegenden Quellen\&. Wenn der Paketzwischenspeicher gebildet wird, wird der Quellenzwischenspeicher benutzt, um ein erneutes Auswerten aller Paketdateien zu vermeiden\&. Konfigurationselement:
Dir::Cache::srcpkgcache\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Still; erzeugt eine Ausgabe, die für Protokollierung geeignet ist und Fortschrittsanzeiger weglässt\&. Mehr \(Fcq\(Fos unterdrücken mehr Ausgaben, bis zu einem Maximum von 2\&. Sie können außerdem
\fB\-q=#\fR
benutzen, um die Stillestufe zu setzen, was die Konfigurationsdatei überschreibt\&. Konfigurationselement:
quiet\&.
.RE
.PP
\fB\-i\fR, \fB\-\-important\fR
.RS 4
Nur wichtige Abhängigkeiten ausgeben\&. Zur Benutzung mit unmet und depends\&. Veranlasst, dass nur Depends\- und Pre\-Depends\-Beziehungen ausgegeben werden\&. Konfigurationselement:
APT::Cache::Important\&.
.RE
.PP
\fB\-f\fR, \fB\-\-full\fR
.RS 4
Gibt die vollständigen Paketdatensätze beim Suchen aus\&. Konfigurationselement:
APT::Cache::ShowFull\&.
.RE
.PP
\fB\-a\fR, \fB\-\-all\-versions\fR
.RS 4
Gibt die vollständigen Datensätze für alle verfügbaren Versionen aus\&. Dies ist die Vorgabe\&. Um sie auszuschalten, benutzen Sie
\fB\-\-no\-all\-versions\fR\&. Wenn
\fB\-\-no\-all\-versions\fR
angegeben ist, wird nur die Anwärterversion angezeigt (die, die zur Installation ausgewählt würde)\&. Diese Option ist nur für den
show\-Befehl anwendbar\&. Konfigurationselement:
APT::Cache::AllVersions\&.
.RE
.PP
\fB\-g\fR, \fB\-\-generate\fR
.RS 4
Führt das Neuerstellen des Paketzwischenspeichers aus, anstatt den Zwischenspeicher so zu benutzen, wie er ist\&. Das ist die Vorgabe\&. Um sie auszuschalten benutzen Sie
\fB\-\-no\-generate\fR\&. Konfigurationselement:
APT::Cache::Generate\&.
.RE
.PP
\fB\-\-names\-only\fR, \fB\-n\fR
.RS 4
Durchsucht nur die Paketnamen, nicht die Langbeschreibungen\&. Konfigurationselement:
APT::Cache::NamesOnly\&.
.RE
.PP
\fB\-\-all\-names\fR
.RS 4
Lässt
pkgnames
alle Namen, einschließlich virtueller Pakete und fehlender Abhängigkeiten, ausgeben\&. Konfigurationselement:
APT::Cache::AllNames\&.
.RE
.PP
\fB\-\-recurse\fR
.RS 4
Macht
depends
und
rdepends
rekursiv, so dass alle erwähnten Pakete einmal ausgegeben werden\&. Konfigurationselement:
APT::Cache::RecurseDepends\&.
.RE
.PP
\fB\-\-installed\fR
.RS 4
Begrenzt die Ausgabe von
depends
und
rdepends
auf Pakete, die aktuell installiert sind\&. Konfigurationselement:
APT::Cache::Installed\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Ein kurze Aufrufzusammenfassung zeigen\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Die Version des Programms anzeigen\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Konfigurationsdatei; Gibt eine Konfigurationssdatei zum Benutzen an\&. Das Programm wird die Vorgabe\-Konfigurationsdatei und dann diese Konfigurationsdatei lesen\&. Lesen Sie
\fBapt.conf\fR(5), um Syntax\-Informationen zu erhalten
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Eine Konfigurationsoption setzen; Dies wird eine beliebige Konfigurationsoption setzen\&. Die Syntax lautet
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
und
\fB\-\-option\fR
kann mehrfach benutzt werden, um verschiedene Optionen zu setzen\&.
.RE
.SH "DATEIEN"
.PP
/etc/apt/sources\&.list
.RS 4
Orte, von denen Pakete geladen werden\&. Konfigurationselement:
Dir::Etc::SourceList\&.
.RE
.PP
/etc/apt/sources\&.list\&.d/
.RS 4
Dateifragmente für Orte, von denen Pakete geladen werden\&. Konfigurationselement:
Dir::Etc::SourceParts\&.
.RE
.PP
/var/lib/apt/lists/
.RS 4
Speicherbereich für Statusinformationen jeder in
\fBsources.list\fR(5)
angegebenen Paketquelle Konfigurationselement:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
Speicherbereich für Statusinformationen auf dem Transportweg\&. Konfigurationselement:
Dir::State::Lists
(implizit teilweise)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBapt.conf\fR(5),
\fBsources.list\fR(5),
\fBapt-get\fR(8)
.SH "DIAGNOSE"
.PP
\fBapt\-cache\fR
gibt bei normalen Operationen 0 zurück, dezimal 100 bei Fehlern\&.
.SH "FEHLER"
.PP
\m[blue]\fBAPT\-Fehlerseite\fR\m[]\&\s-2\u[3]\d\s+2\&. Wenn Sie einen Fehler in APT berichten möchten, lesen Sie bitte
/usr/share/doc/debian/bug\-reporting\&.txt
oder den
\fBreportbug\fR(1)\-Befehl\&. Verfassen Sie Fehlerberichte bitte auf Englisch\&.
.SH "ÜBERSETZUNG"
.PP
Die deutsche Übersetzung wurde 2009 von Chris Leick
c\&.leick@vollbio\&.de
angefertigt in Zusammenarbeit mit dem Debian German\-l10n\-Team
debian\-l10n\-german@lists\&.debian\&.org\&.
.PP
Note that this translated document may contain untranslated parts\&. This is done on purpose, to avoid losing content when the translation is lagging behind the original content\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT\-Team\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
GraphViz
.RS 4
\%http://www.research.att.com/sw/tools/graphviz/
.RE
.IP " 2." 4
VCG-Werkzeug
.RS 4
\%http://rw4.cs.uni-sb.de/users/sander/html/gsvcg1.html
.RE
.IP " 3." 4
APT-Fehlerseite
.RS 4
\%http://bugs.debian.org/src:apt
.RE
