'\" t
.\"     Title: apt-extracttemplates
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 29 F\('evrier 2004
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT\-EXTRACTTEMPLATE" "1" "29 F\('evrier 2004" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt-extracttemplates \- Un outil pour extraire d\'un paquet Debian les textes de configuration pour DebConf\&.
.SH "SYNOPSIS"
.HP \w'\fBapt\-extracttemplates\fR\ 'u
\fBapt\-extracttemplates\fR [\fB\-hv\fR] [\fB\-t=\fR\fB\fIr\('epertoire\ temporaire\fR\fR] \fIfichier\fR...
.SH "DESCRIPTION"
.PP

\fBApt\-extracttemplates\fR
prend un ou plusieurs paquets Debian en argument et renvoie (dans un r\('epertoire temporaire) tous les scripts et guides de configuration associ\('es\&. Pour chaque paquet trait\('e contenant des scripts et guides de configuration, une ligne est affich\('ee au format suivant\ \&:
.PP
paquet version guide\-de\-configuration script\-de\-configuration
.PP
Les scripts et guides de configuration sont \('ecrits dans le r\('epertoire temporaire indiqu\('e par l\'option
\fB\-t\fR
ou
\fB\-\-tempdir\fR
(APT::ExtractTemplates::TempDir)\ \&; les noms de fichier sont de la forme
package\&.template\&.XXXX
ou
package\&.config\&.XXXX\&.
.SH "OPTIONS"
.PP
Toutes les options en ligne de commande peuvent \(^etre positionn\('ees via le fichier de configuration\ \&; les descriptifs indiquent l\'option de configuration \(`a positionner\&. En ce qui concerne les options bool\('eennes, on peut annuler le fichier de configuration en utilisant quelque chose comme
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou d\'autres variantes\&.
.PP
\fB\-t\fR, \fB\-\-tempdir\fR
.RS 4
R\('epertoire temporaire dans lequel \('ecrire les scripts et guides de configuration pour Debconf\&. \('El\('ement de configuration\ \&:
APT::ExtractTemplates::TempDir\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Affiche un mode d\'emploi succinct\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Affiche la version du programme\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Fichier de configuration\ \&; indique quel fichier de configuration utiliser\&. Le programme lit le fichier de configuration par d\('efaut, puis celui\-ci\&. Voyez
\fBapt.conf\fR(5)
pour la syntaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Donne une option de configuration\ \&; cela fixe une option de configuration arbitraire\&. La syntaxe est :
\fB\-o Foo::Bar=bar\fR\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBapt-config\fR(8)
.SH "DIAGNOSTICS"
.PP

\fBapt\-extracttemplates\fR
retourne z\('ero si tout se passe bien, le nombre 100 en cas d\'erreur\&.
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTION"
.PP
Philippe Batailler\&.
debian\-l10n\-french@lists\&.debian\&.org\&. 2005\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.PP
\fBAPT team\fR
.RS 4
Auteur.
.RE
.SH "NOTES"
.IP " 1." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
