'\" t
.\"     Title: apt-get
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 29 F\('evrier 2004
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT\-GET" "8" "29 F\('evrier 2004" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt-get \- Utilitaire d\'APT pour la manipulation de paquets \-\- interface en ligne de commande\&.
.SH "SYNOPSIS"
.HP \w'\fBapt\-get\fR\ 'u
\fBapt\-get\fR [\fB\-hvs\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] {[update] | [upgrade] | [dselect\-upgrade] | [install\ \fIpaquet\fR...] | [remove\ \fIpaquet\fR...] | [source\ \fIpaquet\fR...] | [build\-dep\ \fIpaquet\fR...] | [check] | [clean] | [autoclean]}
.SH "DESCRIPTION"
.PP

\fBApt\-get\fR
est l\'outil en ligne de commande pour manipuler les paquets\&. Il peut \(^etre consid\('er\('e par l\'utilisateur comme un g\('en\('erateur de sortie pour les autres outils de la biblioth\(`eque APT\&. Plusieurs interfaces utilisateur existent, comme dselect, aptitude, synaptic, gnome\-apt ou wajig\&.
.PP
\(`A moins que l\'option
\fB\-h\fR, ou
\fB\-\-help\fR
ne soit donn\('ee, l\'une des commandes suivantes doit \(^etre pr\('esente\&.
.PP
update
.RS 4
La commande
update
permet de resynchroniser un fichier r\('epertoriant les paquets disponibles et sa source\&. Ces fichiers sont r\('ecup\('er\('es aux endroits sp\('ecifi\('es dans
/etc/apt/sources\&.list\&. Ainsi, lorsqu\'on utilise une archive Debian, cette commande r\('ecup\(`ere les fichiers
Packages\&.gz
et les analyse de mani\(`ere \(`a rendre disponibles les informations concernant les nouveaux paquets et les paquets mis \(`a jour\&. On doit toujours ex\('ecuter une commande
update
avant les commandes
upgrade
ou
dist\-upgrade\&. Il faut savoir que l\'indicateur de progression d\'ensemble n\'est pas correct puisque la taille de ces fichiers ne peut \(^etre connue \(`a l\'avance\&.
.RE
.PP
upgrade
.RS 4
La commande
upgrade
permet d\'installer les versions les plus r\('ecentes de tous les paquets pr\('esents sur le syst\(`eme en utilisant les sources \('enum\('er\('ees dans
/etc/apt/sources\&.list\&. Les paquets install\('es dont il existe de nouvelles versions sont r\('ecup\('er\('es et mis \(`a niveau\&. En aucun cas des paquets d\('ej\(`a install\('es ne sont supprim\('es\ \&; de m\(^eme, des paquets qui ne sont pas d\('ej\(`a install\('es ne sont ni r\('ecup\('er\('es ni install\('es\&. Les paquets dont de nouvelles versions ne peuvent pas \(^etre install\('ees sans changer le statut d\'installation d\'un autre paquet sont laiss\('es dans leur version courante\&. On doit d\'abord ex\('ecuter la commande
update
pour que
\fBapt\-get\fR
connaisse l\'existence de nouvelles versions des paquets\&.
.RE
.PP
dselect\-upgrade
.RS 4

dselect\-upgrade
est utilis\('ee conjointement avec
\fBdselect\fR(8), l\'interface traditionnelle Debian pour la gestion des paquets\&. La commande
dselect\-upgrade
suit les modifications faites par
\fBdselect\fR(8)
dans le champ
Status
des paquets disponibles, et effectue les actions n\('ecessaires \(`a la r\('ealisation de cet \('etat (par exemple, suppression d\'anciens paquets, installation de nouveaux paquets)\&.
.RE
.PP
dist\-upgrade
.RS 4
La commande
dist\-upgrade
effectue la fonction
upgrade
en y ajoutant une gestion intelligente des changements de d\('ependances dans les nouvelles versions des paquets\ \&;
\fBapt\-get\fR
poss\(`ede un syst\(`eme \(Fo\ \&intelligent\ \&\(Fc de r\('esolution des conflits et il essaye, quand c\'est n\('ecessaire, de mettre \(`a niveau les paquets les plus importants aux d\('epens des paquets les moins importants\&. Le fichier
/etc/apt/sources\&.list
contient une liste de sources o\(`u r\('ecup\('erer les paquets d\('esir\('es\&. Voyez aussi
\fBapt_preferences\fR(5)
pour un m\('ecanisme de remplacement des param\(`etres g\('en\('eraux pour certains paquets\&.
.RE
.PP
install
.RS 4
La commande
install
est suivie par un ou plusieurs paquets \(`a installer\&. Chaque paquet est un nom de paquet\ \&; ce n\'est pas un nom de fichier enti\(`erement d\('efini (par exemple, dans un syst\(`eme Debian GNU/Linux, on indiquera libc6 et non pas
libc6_1\&.9\&.6\-2\&.deb)\&. Tous les paquets requis par le(s) paquet(s) que l\'on veut installer sont aussi r\('ecup\('er\('es et install\('es\&. On se sert du fichier
/etc/apt/sources\&.list
pour localiser les paquets d\('esir\('es\&. Quand un trait d\'union est accol\('e (sans espace interm\('ediaire) au nom d\'un paquet d\('ej\(`a install\('e, ce paquet est supprim\('e\&. De m\(^eme on peut ajouter un signe \(Fo\ \&+\ \&\(Fc pour d\('esigner un paquet \(`a installer\&. Cette derni\(`ere fonctionnalit\('e peut \(^etre utilis\('ee pour annuler les d\('ecisions prises par le syst\(`eme de r\('esolution des conflits d\'apt\-get\&.
.sp
On peut choisir d\'installer une version particuli\(`ere d\'un paquet en faisant suivre son nom par un signe \('egal et par la version\&. Cette version sera localis\('ee et l\'installation sera demand\('ee\&. On peut aussi choisir une distribution particuli\(`ere en faisant suivre le nom du paquet par une barre oblique et par le nom de la distribution ou de l\'archive (stable, testing, unstable)\&.
.sp
Avec ces possibilit\('es de choisir la version, de vieilles versions d\'un paquet peuvent \(^etre install\('ees\&. Il faut faire attention\&.
.sp
Enfin, le m\('ecanisme d\'\fBapt_preferences\fR(5)
permet de cr\('eer d\'autres r\(`egles pour l\'installation des paquets\&.
.sp
Quand aucun paquet ne correspond \(`a l\'expression donn\('ee en argument et que cette expression contient l\'un des caract\(`eres \(Fo\ \&\&.\ \&\(Fc, \(Fo\ \&?\ \&\(Fc ou \(Fo\ \&*\ \&\(Fc, on consid\(`ere que c\'est une expression rationnelle POSIX et elle est appliqu\('ee \(`a tous les paquets de la base de donn\('ees\&. Tout paquet correspondant est install\('e (ou supprim\('e)\&. Notez que la comparaison est effectu\('ee par sous\-cha\(^ine et \(Fo\ \&lo\ \&\(Fc correspond aussi bien \(`a \(Fo\ \&how\-lo\ \&\(Fc qu\'\(`a \(Fo\ \&lowest\ \&\(Fc\&. Si vous ne le voulez pas, ancrez l\'expression par un caract\(`ere \(Fo\ \&^\ \&\(Fc ou un caract\(`ere \(Fo\ \&$\ \&\(Fc, ou bien cr\('eez une expression plus pr\('ecise\&.
.RE
.PP
remove
.RS 4
La commande
remove
est identique \(`a la commande
install\ \&; Mais les paquets sont supprim\('es et non pas install\('es\&. Quand un signe plus est accol\('e (sans espace interm\('ediaire) au nom du paquet, le paquet est install\('e au lieu d\'\(^etre supprim\('e\&.
.RE
.PP
source
.RS 4
Avec la commande
source,
\fBapt\-get\fR
r\('ecup\(`ere des paquets sources\&. APT examine les paquets disponibles pour choisir le paquet source \(`a r\('ecup\('erer\&. Il trouve ensuite et t\('el\('echarge dans le r\('epertoire courant la version la plus r\('ecente\&. Les paquets source sont g\('er\('es ind\('ependamment des paquets binaires, via les lignes de type
deb\-src
dans le fichier
\fBsources.list\fR(5)\&. On n\'obtiendra probablement pas les m\(^emes sources que celles du paquet install\('e ou celles du paquet qu\'on pourrait installer\&. Si l\'option
\fB\-\-compile\fR
est sp\('ecifi\('ee, le paquet est compil\('e en un binaire \&.deb avec
\fBdpkg\-buildpackage\fR\&. Si
\fB\-\-download\-only\fR
est sp\('ecifi\('e, le source n\'est pas d\('ecompact\('e\&.
.sp
De la m\(^eme fa\(,con qu\'avec les paquets binaires, on peut r\('ecup\('erer une version particuli\(`ere d\'un paquet source en faisant suivre son nom par un signe \('egal et par la version\&. Cela permet une comparaison exacte entre le nom du paquet source et la version\ \&; cela lance implicitement la commande
APT::Get::Only\-Source\&.
.sp
Notez que les paquets sources ne sont pas suivis comme le sont les paquets binaires\&. Ils ne sont pr\('esents que dans le r\('epertoire courant et sont semblables \(`a des sources t\('el\('echarg\('es sous forme de tarball\&.
.RE
.PP
build\-dep
.RS 4
Avec la commande
build\-dep, apt\-get installe ou supprime des paquets dans le but de satisfaire les d\('ependances de construction d\'un paquet source\&. Pour l\'instant, dans le cas d\'un paquet virtuel, un paquet est choisi au hasard\&.
.RE
.PP
check
.RS 4
La commande
check
est un outil de diagnostic\ \&; il met \(`a jour le cache des paquets et cherche des d\('ependances d\('efectueuses\&.
.RE
.PP
clean
.RS 4
La commande
clean
nettoie le r\('ef\('erentiel local des paquets r\('ecup\('er\('es\&. Il supprime tout, except\('e le fichier lock situ\('e dans
/var/cache/apt/archives/
et
/var/cache/apt/archives/partial/\&. Quand APT est utilis\('e comme mode de
\fBdselect\fR(8),
clean
est effectu\('e automatiquement\&. Quand on n\'utilise pas dselect, il faut ex\('ecuter
apt\-get clean
de temps en temps si l\'on veut lib\('erer de l\'espace disque\&.
.RE
.PP
autoclean
.RS 4
Tout comme
clean,
autoclean
nettoie le r\('ef\('erentiel local des paquets r\('ecup\('er\('es\&. La diff\('erence est qu\'il supprime uniquement les paquets qui ne peuvent plus \(^etre t\('el\('echarg\('es et qui sont grandement inutiles\&. On peut ainsi contr\(^oler la taille de ce cache sur une longue p\('eriode\&. Tant qu\'elle n\'est pas activ\('ee, l\'option de configuration
APT::Clean\-Installed
emp\(^eche la suppression de paquets install\('es\&.
.RE
.SH "OPTIONS"
.PP
Toutes les options en ligne de commande peuvent \(^etre positionn\('ees via le fichier de configuration\ \&; les descriptifs indiquent l\'option de configuration \(`a positionner\&. En ce qui concerne les options bool\('eennes, on peut annuler le fichier de configuration en utilisant quelque chose comme
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou d\'autres variantes\&.
.PP
\fB\-d\fR, \fB\-\-download\-only\fR
.RS 4
R\('ecup\('eration seule\ \&; les paquets sont r\('ecup\('er\('es mais ne sont ni d\('epaquet\('es ni install\('es\&. \('El\('ement de configuration\ \&:
APT::Get::Download\-Only\&.
.RE
.PP
\fB\-f\fR, \fB\-\-fix\-broken\fR
.RS 4
Correction\ \&; essaye de r\('eparer un syst\(`eme dont les d\('ependances sont d\('efectueuses\&. Cette option, utilis\('ee avec install ou remove, peut omettre tout paquet de fa\(,con \(`a permettre \(`a APT de d\('eduire une solution viable\&. Chaque paquet sp\('ecifi\('e doit compl\(`etement corriger le probl\(`eme\&. Cette option est quelquefois n\('ecessaire lorsque l\'on ex\('ecute APT pour la premi\(`ere fois\ \&; APT lui\-m\(^eme interdit les d\('ependances d\('efectueuses dans un syst\(`eme\&. Il est possible que la structure de d\('ependances d\'un syst\(`eme soit tellement corrompue qu\'elle requiert une intervention manuelle (ce qui veut dire la plupart du temps utiliser
\fBdselect\fR(8)
ou
\fBdpkg \-\-remove\fR
pour \('eliminer les paquets en cause)\&. L\'utilisation de cette option conjointement avec
\fB\-m\fR
peut produire une erreur dans certaines situations\&. \('El\('ement de configuration\ \&:
APT::Get::Fix\-Broken\&.
.RE
.PP
\fB\-m\fR, \fB\-\-ignore\-missing\fR, \fB\-\-fix\-missing\fR
.RS 4
Ignorer les paquets manquants\ \&; si des paquets ne peuvent \(^etre r\('ecup\('er\('es, ou, apr\(`es r\('ecup\('eration, ne satisfont pas au contr\(^ole d\'int\('egrit\('e, cette commande met ces paquets de c\(^ot\('e et g\(`ere le r\('esultat\&. Utiliser cette option conjointement avec
\fB\-f\fR
peut produire une erreur dans certaines situations\&. Quand un paquet, s\('electionn\('e pour une installation (particuli\(`erement si c\'est mentionn\('e en ligne de commande), ne peut \(^etre r\('ecup\('er\('e, il est mis silencieusement de c\(^ot\('e\&. \('El\('ement de configuration\ \&:
APT::Get::Fix\-Missing\&.
.RE
.PP
\fB\-\-no\-download\fR
.RS 4
Pas de r\('ecup\('eration\&. Le mieux est d\'utiliser cette option avec
\fB\-\-ignore\-missing\fR
pour forcer APT \(`a n\'utiliser que les \&.deb qu\'il a d\('ej\(`a r\('ecup\('er\('es\&. \('El\('ement de configuration\ \&:
APT::Get::Download\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Mode silencieux\ \&; cette commande produit une sortie destin\('ee \(`a l\'enregistrement dans un fichier\-journal en omettant les indicateurs de progression\&. Un plus grand nombre de \(Fo\ \&q\ \&\(Fc (2 au plus) produit un plus grand silence\&. On peut aussi utiliser
\fB\-q=#\fR
pour positionner le niveau de silence, et annuler le fichier de configuration\&. Notez qu\'un niveau de silence \('egal \(`a 2 implique
\fB\-y\fR
et vous ne devez jamais utiliser
\fB\-qq\fR
sans l\'accompagner d\'un modificateur tel que
\fB\-d\fR,
\fB\-\-print\-uris\fR
ou
\fB\-s\fR\ \&: APT pourrait ex\('ecuter des actions inattendues\ \&! \('El\('ement de configuration\ \&:
quiet\&.
.RE
.PP
\fB\-s\fR, \fB\-\-simulate\fR, \fB\-\-just\-print\fR, \fB\-\-dry\-run\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 4
Simulation\ \&; cette commande r\('ealise une simulation des actions qui seraient ex\('ecut\('ees mais ne modifie pas le syst\(`eme\&. \('El\('ement de configuration\ \&:
APT::Get::Simulate\&.
.sp
La simulation affiche une s\('erie de lignes repr\('esentant chacune une op\('eration de dpkg, Configure (Conf),Remove (Remv),Unpack (Inst)\&. Les crochets encadrent des paquets endommag\('es et des crochets n\'encadrant rien indiquent que les dommages n\'ont aucune cons\('equence (rare)\&.
.RE
.PP
\fB\-y\fR, \fB\-\-yes\fR, \fB\-\-assume\-yes\fR
.RS 4
R\('epond automatiquement oui aux questions\ \&; pr\('esume \(Fo\ \&oui\ \&\(Fc comme r\('eponse \(`a toutes les questions et s\'ex\('ecute de mani\(`ere non interactive\&. Dans le cas d\'une situation ind\('esirable, comme le changement d\'un paquet gel\('e, l\'installation d\'un paquet non authentifi\('e ou la suppression d\'un paquet essentiel,
apt\-get
s\'interrompt\&. \('El\('ement de configuration\ \&:
APT::Get::Assume\-Yes\&.
.RE
.PP
\fB\-u\fR, \fB\-\-show\-upgraded\fR
.RS 4
Afficher les paquets mis \(`a niveau\ \&; affiche une liste de tous les paquets \(`a mettre \(`a niveau\&. \('El\('ement de configuration\ \&:
APT::Get::Show\-Upgraded\&.
.RE
.PP
\fB\-V\fR, \fB\-\-verbose\-versions\fR
.RS 4
Afficher les versions compl\(`etes des paquets install\('es ou mis \(`a niveau\&. \('El\('ement de configuration\ \&:
APT::Get::Show\-Versions\&.
.RE
.PP
\fB\-b\fR, \fB\-\-compile\fR, \fB\-\-build\fR
.RS 4
Cette commande compile un paquet source apr\(`es l\'avoir r\('ecup\('er\('e\&. \('El\('ement de configuration\ \&:
APT::Get::Compile\&.
.RE
.PP
\fB\-\-ignore\-hold\fR
.RS 4
Cette commande ignore la marque \(Fo\ \&Hold\ \&\(Fc d\'un paquet\ \&; par ce biais,
\fBapt\-get\fR
ignore un \(Fo\ \&hold\ \&\(Fc plac\('e sur un paquet\&. cela peut \(^etre utile avec
dist\-upgrade
pour annuler un grand nombre de \(Fo\ \&hold\ \&\(Fc ind\('esirables\&. \('El\('ement de configuration\ \&:
APT::Ignore\-Hold\&.
.RE
.PP
\fB\-\-no\-upgrade\fR
.RS 4
Aucune mise \(`a niveau\ \&; quand elle est utilis\('ee avec
install, cette commande emp\(^eche les paquets list\('es sur la ligne de commande d\'\(^etre mis \(`a niveau\&. \('El\('ement de configuration\ \&:
APT::Get::Upgrade\&.
.RE
.PP
\fB\-\-force\-yes\fR
.RS 4
Forcer l\'acceptation\ \&; cette option est dangereuse parce qu\'elle laisse APT continuer sans poser de questions quand il r\('ealise quelque chose de potentiellement dommageable\&. Cette option ne doit \(^etre utilis\('ee que dans des circonstances tr\(`es sp\('eciales\&. Utiliser
force\-yes
peut d\('etruire le syst\(`eme\ \&! \('El\('ement de configuration\ \&:
APT::Get::force\-yes\&.
.RE
.PP
\fB\-\-print\-uris\fR
.RS 4
Au lieu d\'aller chercher les paquets \(`a installer, leurs URI sont affich\('ees\&. Chaque URI a un chemin, un nom de fichier destination, une taille et une cl\('e md5 attendue\&. Notez que le nom de fichier \(`a afficher ne correspond pas toujours au nom de fichier sur le site distant\ \&! Cette option fonctionne aussi avec la commande
source
et avec la commande
update\&. Avec la commande
update, la somme MD5 et la taille ne sont pas donn\('ees et c\'est \(`a l\'utilisateur de d\('ecompresser les fichiers compress\('es\&. \('El\('ement de configuration\ \&:
APT::Get::Print\-URIs\&.
.RE
.PP
\fB\-\-purge\fR
.RS 4
Utiliser purge \(`a la place de remove pour supprimer tout ce qui peut \(^etre supprim\('e\&. Un ast\('erisque (*) sera affich\('e pr\(`es des paquets qui vont \(^etre purg\('es\&. \('El\('ement de configuration\ \&:
APT::Get::Purge\&.
.RE
.PP
\fB\-\-reinstall\fR
.RS 4
R\('einstaller les paquets d\('ej\(`a install\('es avec leur version la plus r\('ecente\&. \('El\('ement de configuration\ \&:
APT::Get::ReInstall\&.
.RE
.PP
\fB\-\-list\-cleanup\fR
.RS 4
Cette option est activ\('ee par d\('efaut\ \&; utilisez
\-\-no\-list\-cleanup
pour la d\('esactiver\&. Quand elle est activ\('ee,
\fBapt\-get\fR
g\(`ere automatiquement le contenu de
/var/lib/apt/lists
afin d\'assurer que les fichiers obsol\(`etes soient effac\('es\&. La seule raison de la d\('esactiver est une modification fr\('equente de votre liste de sources\&. \('El\('ement de configuration\ \&:
APT::Get::List\-Cleanup\&.
.RE
.PP
\fB\-t\fR, \fB\-\-target\-release\fR, \fB\-\-default\-release\fR
.RS 4
Cette option contr\(^ole l\'entr\('ee par d\('efaut pour les questions de distribution\ \&; une \('etiquette (pin) par d\('efaut dont la priorit\('e vaut 990 est cr\('e\('e en utilisant la cha\(^ine sp\('ecifi\('ee\&. Le fichier des pr\('ef\('erences peut annuler cette d\('ecision\&. En clair, cette option permet de contr\(^oler simplement dans quelle distribution seront r\('ecup\('er\('es les paquets\&. Par exemple\ \&:
\fB\-t \'2\&.1*\'\fR
ou
\fB\-t unstable\fR\&. \('El\('ement de configuration\ \&:
APT::Default\-Release\&. Voyez aussi la page de manuel d\'\fBapt_preferences\fR(5)\&.
.RE
.PP
\fB\-\-trivial\-only\fR
.RS 4
Ne r\('ealise que les op\('erations \(Fo\ \&triviales\ \&\(Fc\&. Logiquement ceci peut \(^etre consid\('er\('e comme relatif \(`a
\fB\-\-assume\-yes\fR\&. Alors que
\fB\-\-assume\-yes\fR
r\('epond oui \(`a n\'importe quelle question,
\fB\-\-trivial\-only\fR
r\('epond non\&. \('El\('ement de configuration\ \&:
APT::Get::Trivial\-Only\&.
.RE
.PP
\fB\-\-no\-remove\fR
.RS 4
Quand des paquets doivent \(^etre supprim\('es, apt\-get s\'arr\(^ete imm\('ediatement sans poser de questions\&. \('El\('ement de configuration\ \&:
APT::Get::Remove\&.
.RE
.PP
\fB\-\-only\-source\fR
.RS 4
Cette option n\'a de sens qu\'avec les commandes
source
et
build\-dep\&. Elle indique que les noms de sources donn\('es ne doivent pas \(^etre rep\('er\('es \(`a travers le tableau des binaires\&. Cela signifie que si cette option est choisie, la commande
source
acceptera seulement des noms de paquets source comme argument\ \&; elle n\'acceptera pas de les rechercher \(`a partir des noms de paquets binaires correspondants\&. \('El\('ement de configuration\ \&:
APT::Get::Only\-Source
.RE
.PP
\fB\-\-diff\-only\fR, \fB\-\-tar\-only\fR
.RS 4
Ne r\('ecup\('erer que le fichier diff ou tar d\'une archive de source\&. \('El\('ement de configuration\ \&:
APT::Get::Diff\-Only
et
APT::Get::Tar\-Only\&.
.RE
.PP
\fB\-\-arch\-only\fR
.RS 4
Ne traiter que les d\('ependances de construction pour telle architecture\&. \('El\('ement de configuration\ \&:
APT::Get::Arch\-Only
.RE
.PP
\fB\-\-allow\-unauthenticated\fR
.RS 4
Ignorer le fait que les paquets ne peuvent pas \(^etre authentifi\('es ; pas d\'interrogation de l\'utilisateur\&. C\'est tr\(`es utile pour certains outils comme pbuilder \('El\('ement de configuration\ \&:
APT::Get::AllowUnauthenticated\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Affiche un mode d\'emploi succinct\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Affiche la version du programme\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Fichier de configuration\ \&; indique quel fichier de configuration utiliser\&. Le programme lit le fichier de configuration par d\('efaut, puis celui\-ci\&. Voyez
\fBapt.conf\fR(5)
pour la syntaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Donne une option de configuration\ \&; cela fixe une option de configuration arbitraire\&. La syntaxe est :
\fB\-o Foo::Bar=bar\fR\&.
.RE
.SH "FICHIERS"
.PP
/etc/apt/sources\&.list
.RS 4
Liste les emplacements o\(`u aller chercher les paquets\&. \('El\('ement de configuration\ \&:
Dir::Etc::SourceList\&.
.RE
.PP
/etc/apt/apt\&.conf
.RS 4
Fichier de configuration d\'APT\&. \('El\('ement de configuration\ \&:
Dir::Etc::Main\&.
.RE
.PP
/etc/apt/apt\&.conf\&.d/
.RS 4
\('El\('ements du fichier de configuration d\'APT\&. \('El\('ement de configuration\ \&:
Dir::Etc::Parts\&.
.RE
.PP
/etc/apt/preferences
.RS 4
Fichier des pr\('ef\('erences\&. C\'est dans ce fichier qu\'on peut faire de l\'\('etiquetage (pinning) c\'est\-\(`a\-dire, choisir d\'obtenir des paquets d\'une source distincte ou d\'une distribution diff\('erente\&. \('El\('ement de configuration\ \&:
Dir::Etc::Preferences\&.
.RE
.PP
/var/cache/apt/archives/
.RS 4
Zone de stockage pour les paquets r\('ecup\('er\('es\&. \('El\('ement de configuration\ \&:
Dir::Cache::Archives\&.
.RE
.PP
/var/cache/apt/archives/partial/
.RS 4
Zone de stockage pour les paquets en transit\&. \('El\('ement de configuration\ \&:
Dir::Cache::Archives
(implicitement, partial)\&.
.RE
.PP
/var/lib/apt/lists/
.RS 4
Zone de stockage des informations concernant chaque ressource sp\('ecifi\('ee dans
\fBsources.list\fR(5)\&. \('El\('ement de configuration\ \&:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
Zone de stockage pour les informations d\'\('etat des paquets en transit\&. \('El\('ement de configuration\ \&:
Dir::State::Lists
(implicit partial)\&.
.RE
.SH "VOIR AUSSI"
.PP

\fBapt-cache\fR(8),
\fBapt-cdrom\fR(8),
\fBdpkg\fR(8),
\fBdselect\fR(8),
\fBsources.list\fR(5),
\fBapt.conf\fR(5),
\fBapt-config\fR(8), le guide \(Fo\ \&APT users guide\ \&\(Fc dans /usr/share/doc/apt/,
\fBapt_preferences\fR(5), le guide APT\&.
.SH "DIAGNOSTIC"
.PP
\fBapt\-get\fR
renvoie z\('ero apr\(`es une op\('eration normale, le d\('ecimal 100 en cas d\'erreur\&.
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTION"
.PP
J\('er\(^ome Marant\&. 2000\ \&; mise \(`a jour : Philippe Batailler\&. 2005\&.
debian\-l10n\-french@lists\&.debian\&.org\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.PP
\fBAPT team\fR
.RS 4
Auteur.
.RE
.SH "NOTES"
.IP " 1." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
