'\" t
.\"     Title: apt-get
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 08
Novembre 2008
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-GET" "8" "08 Novembre 2008" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-get \- Utilitaire APT pour la gestion des paquets \-\- interface en ligne de commande\&.
.SH "SYNOPSIS"
.HP \w'\fBapt\-get\fR\ 'u
\fBapt\-get\fR [\fB\-sqdyfmubV\fR] [\fB\-o=\ \fR\fB\fIoption_de_configuration\fR\fR\fB\ \fR] [\fB\-c=\ \fR\fB\fIfichier_de_configuration\fR\fR\fB\ \fR] [\fB\-t=\fR\ {\ \fInom_version_cible\fR\ |\ \fIexpression_numéro_version_cible\fR\ |\ \fInom_code_version_cible\fR\ }] {update | upgrade | dselect\-upgrade | dist\-upgrade | install\ \fIpkg\fR\ [\ {\ =\fInumero_version_paquet\fR\ |\ /\fInom_version_cible\fR\ |\ /\fInom_code_version_cible\fR\ }\ ]\ ...  | remove\ \fIpkg\fR...  | purge\ \fIpkg\fR...  | source\ \fIpaquet\fR\ [\ =\fInuméro_version_paquet\fR\ ]\ ...  | build\-dep\ \fIpaquet\fR...  | check | clean | autoclean | autoremove | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "DESCRIPTION"
.PP
\fBApt\-get\fR
est le programme en ligne de commande pour la gestion des paquets\&. Il peut être considéré comme l\*(Aqoutil de base pour les autres programmes de la bibliothèque APT\&. Plusieurs interfaces utilisateur existent, comme dselect, aptitude, synaptic, gnome\-apt ou wajig\&.
.PP
À moins que l\*(Aqoption
\fB\-h\fR
ou
\fB\-\-help\fR
ne soit donnée, l\*(Aqune des commandes suivantes doit être présente\&.
.PP
update
.RS 4
La commande
update
permet de resynchroniser un fichier d\*(Aqindex répertoriant les paquets disponibles et sa source\&. Ces fichiers sont récupérés aux endroits spécifiés dans
/etc/apt/sources\&.list\&. Ainsi, lorsqu\*(Aqon utilise une archive Debian, cette commande récupère les fichiers
Packages\&.gz
et les analyse de manière à rendre disponibles les informations concernant les nouveaux paquets et les paquets mis à jour\&. On doit toujours exécuter une commande
update
avant les commandes
upgrade
ou
dist\-upgrade\&. Veuillez noter que l\*(Aqindicateur de progression d\*(Aqensemble peut être imprécis puisque la taille de ces fichiers ne peut être connue à l\*(Aqavance\&.
.RE
.PP
upgrade
.RS 4
La commande
upgrade
permet d\*(Aqinstaller les versions les plus récentes de tous les paquets présents sur le système en utilisant les sources énumérées dans
/etc/apt/sources\&.list\&. Les paquets installés dont il existe de nouvelles versions sont récupérés et mis à niveau\&. En aucun cas des paquets déjà installés ne sont supprimés\ \&; de même, des paquets qui ne sont pas déjà installés ne sont ni récupérés ni installés\&. Les paquets dont de nouvelles versions ne peuvent pas être installées sans changer le statut d\*(Aqinstallation d\*(Aqun autre paquet sont laissés dans leur version courante\&. On doit d\*(Aqabord exécuter la commande
update
pour que
\fBapt\-get\fR
connaisse l\*(Aqexistence de nouvelles versions des paquets\&.
.RE
.PP
dselect\-upgrade
.RS 4
dselect\-upgrade
est utilisée conjointement avec
\fBdselect\fR(1), la plus ancienne interface du projet Debian pour la gestion des paquets\&. La commande
dselect\-upgrade
suit les modifications faites par
\fBdselect\fR(1)
dans le champ
Status
des paquets disponibles, et effectue les actions nécessaires à la réalisation de cet état (par exemple, suppression d\*(Aqanciens paquets, installation de nouveaux paquets)\&.
.RE
.PP
dist\-upgrade
.RS 4
La commande
dist\-upgrade
effectue la fonction
upgrade
en y ajoutant une gestion intelligente des changements de dépendances dans les nouvelles versions des paquets\ \&;
\fBapt\-get\fR
possède un système \(Fo\ \&intelligent\ \&\(Fc de résolution des conflits et il essaye, quand c\*(Aqest nécessaire, de mettre à niveau les paquets les plus importants avant les paquets les moins importants\&. Le fichier
/etc/apt/sources\&.list
contient une liste de sources où récupérer les paquets désirés\&. Voyez aussi
\fBapt_preferences\fR(5)
pour un mécanisme de remplacement des paramètres généraux pour certains paquets\&.
.RE
.PP
install
.RS 4
La commande
install
est suivie par un ou plusieurs paquets à installer\&. Chaque paquet est un nom de paquet\ \&; ce n\*(Aqest pas un nom complet de fichier (par exemple, dans un système Debian GNU/Linux, on indiquera libc6 et non pas
libc6_1\&.9\&.6\-2\&.deb)\&. Tous les paquets requis par le(s) paquet(s) que l\*(Aqon veut installer sont aussi récupérés et installés\&. Le fichier
/etc/apt/sources\&.list
est utilisé pour retrouver les paquets désirés\&. Quand un trait d\*(Aqunion est accolé (sans espace intermédiaire) au nom d\*(Aqun paquet déjà installé, ce paquet est supprimé\&. De même on peut ajouter un signe \(Fo\ \&+\ \&\(Fc pour désigner un paquet à installer\&. Cette dernière fonctionnalité peut être utilisée pour annuler les décisions prises par le système de résolution des conflits d\*(Aqapt\-get\&.
.sp
On peut choisir d\*(Aqinstaller une version particulière d\*(Aqun paquet en faisant suivre son nom par un signe égal et par la version\&. Cette version sera recherchée et l\*(Aqinstallation sera demandée\&. On peut aussi choisir une distribution particulière en faisant suivre le nom du paquet par une barre oblique et par le nom de la distribution ou de l\*(Aqarchive (stable, testing, unstable)\&.
.sp
Avec ces possibilités de choisir la version, de vieilles versions d\*(Aqun paquet peuvent être installées\&. Cette fonctionnalité est donc à utiliser avec précaution\&.
.sp
Cette méthode est aussi utile pour mettre à jour un ou plusieurs paquets déjà installés sans mettre à jour les autres paquets du système\&. À la différence de la commande \(Fo\ \&upgrade\ \&\(Fc qui installera la dernière version disponible de tous les paquets installés au moment de son exécution, \(Fo\ \&install\ \&\(Fc n\*(Aqinstallera la nouvelle version que pour le(s) paquet(s) indiqué(s)\&. Il suffit de fournir le nom du(des) paquet(s) à mettre à jour et si une nouvelle version est disponible, cette version (et ses dépendances, comme décrit plus haut) sera récupérée et installée\&.
.sp
Enfin, le mécanisme d\*(Aq\fBapt_preferences\fR(5)
permet de créer d\*(Aqautres règles pour l\*(Aqinstallation des paquets\&.
.sp
Quand aucun paquet ne correspond à l\*(Aqexpression donnée en paramètre et que cette expression contient l\*(Aqun des caractères \(Fo\ \&\&.\ \&\(Fc, \(Fo\ \&?\ \&\(Fc ou \(Fo\ \&*\ \&\(Fc, elle est considérée comme une expression rationnelle POSIX et elle est appliquée à tous les paquets de la base de données\&. Tout paquet correspondant est installé (ou supprimé)\&. Veuillez noter que la comparaison est effectuée par sous\-chaîne et \(Fo\ \&lo\&.*\ \&\(Fc correspond aussi bien à \(Fo\ \&how\-lo\ \&\(Fc qu\*(Aqà \(Fo\ \&lowest\ \&\(Fc\&. Si ce n\*(Aqest pas le comportement souhaité, l\*(Aqexpression peut être ancrée avec un caractère \(Fo\ \&^\ \&\(Fc ou un caractère \(Fo\ \&$\ \&\(Fc, une autre possibilité étant d\*(Aqutiliser une expression plus précise\&.
.RE
.PP
remove
.RS 4
La commande
remove
est identique à la commande
install, les paquets étant alors supprimés et non installés\&. Veuillez noter que la suppression d\*(Aqun paquet en laisse les fichiers de configuration sur le système\&. Quand un signe plus est accolé (sans espace intermédiaire) au nom du paquet, le paquet est installé au lieu d\*(Aqêtre supprimé\&.
.RE
.PP
purge
.RS 4
La commande
purge
est identique à
remove
mais les paquets indiqués sont supprimés et purgés (leurs fichiers de configuration sont également effacés)\&.
.RE
.PP
source
.RS 4
Avec la commande
source,
\fBapt\-get\fR
récupère des paquets source\&. APT examine les paquets disponibles pour choisir le paquet source à récupérer\&. Il télécharge ensuite dans le répertoire courant la version la plus récente du paquet, définie par rapport à la distribution par défaut établie soit avec l\*(Aqoption
APT::Default\-Release, soit avec l\*(Aqoption
\fB\-t\fR
ou soit par paquet avec la syntaxe
paquet/version
"""while respect the default release""" me paraît douteux\&.
.sp
Les paquets source sont gérés indépendamment des paquets binaires, avec les lignes de type
deb\-src
dans le fichier
\fBsources.list\fR(5)\&. Il est donc nécessaire d\*(Aqajouter une telle ligne pour chaque dépôt pour lequel vous souhaitez pouvoir obtenir les sources\&. Dans le cas contraire, vous n\*(Aqobtiendrez pas les mêmes sources que celles du paquet que vous avez installé ou que vous voulez installer\&.
.sp
Si l\*(Aqoption
\fB\-\-compile\fR
est spécifiée, le paquet est compilé en un binaire \&.deb avec
\fBdpkg\-buildpackage\fR\&. Si
\fB\-\-download\-only\fR
est spécifié, le source n\*(Aqest pas décompacté\&.
.sp
De la même façon qu\*(Aqavec les paquets binaires, on peut récupérer une version particulière d\*(Aqun paquet source en faisant suivre son nom par un signe égal et par la version\&. Cela permet une comparaison exacte entre le nom du paquet source et la version\ \&; l\*(Aqoption correspondante est\ \&:\ \&APT::Get::Only\-Source\&.
.sp
Veuillez noter que les paquets source ne sont pas suivis comme le sont les paquets binaires\&. Ils ne sont présents que dans le répertoire courant et sont semblables à des sources téléchargées sous forme d\*(Aqarchives tar\&.
.RE
.PP
build\-dep
.RS 4
Avec la commande
build\-dep, apt\-get installe ou supprime des paquets dans le but de satisfaire les dépendances de construction d\*(Aqun paquet source\&.
.RE
.PP
check
.RS 4
La commande
check
est un outil de diagnostic\ \&; il met à jour le cache des paquets et cherche les dépendances défectueuses\&.
.RE
.PP
clean
.RS 4
La commande
clean
nettoie le référentiel local des paquets récupérés\&. Elle supprime tout, excepté le fichier de verrou situé dans
/var/cache/apt/archives/
et
/var/cache/apt/archives/partial/\&. Quand APT est utilisé comme mode de
\fBdselect\fR(1),
clean
est exécuté automatiquement\&. Quand on n\*(Aqutilise pas dselect, il faut exécuter
apt\-get clean
de temps en temps si l\*(Aqon veut libérer de l\*(Aqespace disque\&.
.RE
.PP
autoclean
.RS 4
Tout comme
clean,
autoclean
nettoie le référentiel local des paquets récupérés\&. La différence est qu\*(Aqil supprime uniquement les paquets qui ne peuvent plus être téléchargés et qui sont inutiles\&. On peut ainsi contrôler la taille de ce cache sur une longue période\&. Tant qu\*(Aqelle n\*(Aqest pas activée, l\*(Aqoption de configuration
APT::Clean\-Installed
empêche la suppression de paquets installés\&.
.RE
.PP
autoremove
.RS 4
Avec la commande
autoremove, apt\-get supprime les paquets installés dans le but de satisfaire les dépendances d\*(Aqun paquet donné et qui ne sont plus nécessaires\&.
.RE
.SH "OPTIONS"
.PP
Toutes les options de la ligne de commande peuvent être définies dans le fichier de configuration, les descriptions indiquant l\*(Aqoption de configuration concernée\&. Pour les options booléennes, vous pouvez inverser les réglages du fichiers de configuration avec
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
et d\*(Aqautres variantes analogues\&.
.PP
\fB\-\-no\-install\-recommends\fR
.RS 4
Ne pas considérer les paquets recommandés comme des dépendances à installer\&. Élément de configuration\ \&:
APT::Install\-Recommends\&.
.RE
.PP
\fB\-d\fR, \fB\-\-download\-only\fR
.RS 4
Récupération seule\ \&; les paquets sont récupérés mais ne sont ni dépaquetés ni installés\&. Élément de configuration\ \&:
APT::Get::Download\-Only\&.
.RE
.PP
\fB\-f\fR, \fB\-\-fix\-broken\fR
.RS 4
Fix; attempt to correct a system with broken dependencies in place\&. This option, when used with install/remove, can omit any packages to permit APT to deduce a likely solution\&. If packages are specified, these have to completely correct the problem\&. The option is sometimes necessary when running APT for the first time; APT itself does not allow broken package dependencies to exist on a system\&. It is possible that a system\*(Aqs dependency structure can be so corrupt as to require manual intervention (which usually means using
\fBdselect\fR(1)
or
\fBdpkg \-\-remove\fR
to eliminate some of the offending packages)\&. Use of this option together with
\fB\-m\fR
may produce an error in some situations\&. Configuration Item:
APT::Get::Fix\-Broken\&.
.RE
.PP
\fB\-m\fR, \fB\-\-ignore\-missing\fR, \fB\-\-fix\-missing\fR
.RS 4
Ignorer les paquets manquants\ \&; si des paquets ne peuvent être récupérés, ou, après récupération, ne satisfont pas au contrôle d\*(Aqintégrité, cette commande met ces paquets de côté et gère le résultat\&. Utiliser cette option conjointement avec
\fB\-f\fR
peut produire une erreur dans certaines situations\&. Quand un paquet, sélectionné pour une installation (particulièrement si c\*(Aqest mentionné en ligne de commande), ne peut être récupéré, il est mis silencieusement de côté\&. Élément de configuration\ \&:
APT::Get::Fix\-Missing\&.
.RE
.PP
\fB\-\-no\-download\fR
.RS 4
Pas de récupération\&. Le mieux est d\*(Aqutiliser cette option avec
\fB\-\-ignore\-missing\fR
pour forcer APT à n\*(Aqutiliser que les \&.deb qu\*(Aqil a déjà récupérés\&. Élément de configuration\ \&:
APT::Get::Download\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Mode silencieux\ \&; cette commande produit une sortie destinée à l\*(Aqenregistrement dans un fichier\-journal en omettant les indicateurs de progression\&. Un plus grand nombre de \(Fo\ \&q\ \&\(Fc (2 au plus) produit un plus grand silence\&. On peut aussi utiliser
\fB\-q=#\fR
pour positionner le niveau de silence, et annuler le fichier de configuration\&. Notez qu\*(Aqun niveau de silence égal à 2 implique
\fB\-y\fR
et vous ne devez jamais utiliser
\fB\-qq\fR
sans l\*(Aqaccompagner d\*(Aqun modificateur tel que
\fB\-d\fR,
\fB\-\-print\-uris\fR
ou
\fB\-s\fR\ \&: APT pourrait alors exécuter des actions inattendues\&. Élément de configuration\ \&:
quiet\&.
.RE
.PP
\fB\-s\fR, \fB\-\-simulate\fR, \fB\-\-just\-print\fR, \fB\-\-dry\-run\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 4
Pas d\*(Aqaction\ \&; simule les événements qui devraient se produire sans effectuer de changement réel sur le système\&. Élément de configuration\ \&:
APT::Get::Simulate\&.
.sp
Lorsque la simulation est effectuée par un utilisateur sans privilège, le verrouillage (Debug::NoLocking) sera désactivé automatiquement\&. Une mention explicite indiquant qu\*(Aqil s\*(Aqagit d\*(Aqune simple simulation sera affichée si l\*(Aqoption
APT::Get::Show\-User\-Simulation\-Note
est activée (elle est active par défaut)\&. Ni la désactivation du verrou ni l\*(Aqaffichage de la mention de simulation ne seront déclenchées si la commande est lancée par l\*(Aqutilisateur root (pour qui il n\*(Aqest pas jugé utile qu\*(Aqapt\-get
envoie de telles notifications)\&.
.sp
La simulation affiche une série de lignes représentant chacune une opération de dpkg, Configure (Conf), Remove (Remv), Unpack (Inst)\&. Des crochets encadrent des paquets endommagés et des crochets n\*(Aqencadrant rien indiquent que les dommages n\*(Aqont aucune conséquence (rare)\&.
.RE
.PP
\fB\-y\fR, \fB\-\-yes\fR, \fB\-\-assume\-yes\fR
.RS 4
Répondre automatiquement oui aux questions\ \&; présume \(Fo\ \&oui\ \&\(Fc comme réponse à toutes les questions et s\*(Aqexécute de manière non interactive\&. Dans le cas d\*(Aqune situation indésirable, comme le changement d\*(Aqun paquet gelé, l\*(Aqinstallation d\*(Aqun paquet non authentifié ou la suppression d\*(Aqun paquet essentiel,
apt\-get
s\*(Aqinterrompt\&. Élément de configuration\ \&:
APT::Get::Assume\-Yes\&.
.RE
.PP
\fB\-u\fR, \fB\-\-show\-upgraded\fR
.RS 4
Afficher les paquets mis à niveau\ \&; affiche une liste de tous les paquets à mettre à niveau\&. Élément de configuration\ \&:
APT::Get::Show\-Upgraded\&.
.RE
.PP
\fB\-V\fR, \fB\-\-verbose\-versions\fR
.RS 4
Afficher les versions complètes des paquets installés ou mis à niveau\&. Élément de configuration\ \&:
APT::Get::Show\-Versions\&.
.RE
.PP
\fB\-b\fR, \fB\-\-compile\fR, \fB\-\-build\fR
.RS 4
Cette commande compile un paquet source après l\*(Aqavoir récupéré\&. Élément de configuration\ \&:
APT::Get::Compile\&.
.RE
.PP
\fB\-\-install\-recommends\fR
.RS 4
Installer également les paquets recommandés\&.
.RE
.PP
\fB\-\-no\-install\-recommends\fR
.RS 4
Ne pas installer les paquets recommandés\&.
.RE
.PP
\fB\-\-ignore\-hold\fR
.RS 4
Cette commande ignore la marque \(Fo\ \&Hold\ \&\(Fc (\(Fo\ \&garder\ \&\(Fc) d\*(Aqun paquet\ \&; par ce biais,
\fBapt\-get\fR
ignore un \(Fo\ \&hold\ \&\(Fc placé sur un paquet\&. cela peut être utile avec
dist\-upgrade
pour annuler un grand nombre de \(Fo\ \&hold\ \&\(Fc indésirables\&. Élément de configuration\ \&:
APT::Ignore\-Hold\&.
.RE
.PP
\fB\-\-no\-upgrade\fR
.RS 4
Aucune mise à niveau\ \&; quand elle est utilisée avec
install, cette commande empêche les paquets mentionnés sur la ligne de commande d\*(Aqêtre mis à niveau\&. Élément de configuration\ \&:
APT::Get::Upgrade\&.
.RE
.PP
\fB\-\-force\-yes\fR
.RS 4
Forcer l\*(Aqacceptation\ \&; cette option est dangereuse parce qu\*(Aqelle laisse APT continuer sans poser de questions quand il réalise quelque chose de potentiellement dommageable\&. Cette option ne doit être utilisée que dans des circonstances très spéciales\&. Utiliser
force\-yes
peut détruire le système\&.\&.\&. Élément de configuration\ \&:
APT::Get::force\-yes\&.
.RE
.PP
\fB\-\-print\-uris\fR
.RS 4
Au lieu de récupérer les paquets à installer, leurs URI sont affichées\&. Chaque URI a un chemin, un nom de fichier destination, une taille et une clé md5 attendue\&. Veuillez noter que le nom de fichier à afficher ne correspond pas toujours au nom de fichier sur le site distant\&. Cette option fonctionne aussi avec la commande
source
et avec la commande
update\&. Avec la commande
update, la somme MD5 et la taille ne sont pas données et c\*(Aqest à l\*(Aqutilisateur de décompresser les fichiers compressés\&. Élément de configuration\ \&:
APT::Get::Print\-URIs\&.
.RE
.PP
\fB\-\-purge\fR
.RS 4
Use purge instead of remove for anything that would be removed\&. An asterisk ("*") will be displayed next to packages which are scheduled to be purged\&.
\fBremove \-\-purge\fR
is equivalent to the
\fBpurge\fR
command\&. Configuration Item:
APT::Get::Purge\&.
.RE
.PP
\fB\-\-reinstall\fR
.RS 4
Réinstaller les paquets déjà installés avec leur version la plus récente\&. Élément de configuration\ \&:
APT::Get::ReInstall\&.
.RE
.PP
\fB\-\-list\-cleanup\fR
.RS 4
Cette option est activée par défaut\ \&; utilisez
\-\-no\-list\-cleanup
pour la désactiver\&. Quand elle est activée,
\fBapt\-get\fR
gère automatiquement le contenu de
/var/lib/apt/lists
afin d\*(Aqassurer que les fichiers obsolètes soient effacés\&. La seule raison de la désactiver est une modification fréquente de la liste de sources\&. Élément de configuration\ \&:
APT::Get::List\-Cleanup\&.
.RE
.PP
\fB\-t\fR, \fB\-\-target\-release\fR, \fB\-\-default\-release\fR
.RS 4
Cette option contrôle l\*(Aqentrée par défaut pour les questions de distribution\ \&; une étiquette (pin) par défaut dont la priorité vaut 990 est créée en utilisant la chaîne spécifiée\&. Le fichier des préférences peut annuler cette décision\&. En clair, cette option permet de contrôler simplement dans quelle distribution seront récupérés les paquets\&. Par exemple\ \&:
\fB\-t \*(Aq2\&.1*\*(Aq\fR,
\fB\-t unstable\fR
ou
\fB\-t sid\fR\&. Élément de configuration\ \&:
APT::Default\-Release\&. Voyez aussi la page de manuel d\*(Aq\fBapt_preferences\fR(5)\&.
.RE
.PP
\fB\-\-trivial\-only\fR
.RS 4
Ne réalise que les opérations \(Fo\ \&triviales\ \&\(Fc\&. Logiquement ceci peut être considéré comme relatif à
\fB\-\-assume\-yes\fR\&. Alors que
\fB\-\-assume\-yes\fR
répond oui à n\*(Aqimporte quelle question,
\fB\-\-trivial\-only\fR
répond non\&. Élément de configuration\ \&:
APT::Get::Trivial\-Only\&.
.RE
.PP
\fB\-\-no\-remove\fR
.RS 4
Arrêter immédiatement apt\-get, sans poser de questions, si des paquets doivent être supprimés\&. Élément de configuration\ \&:
APT::Get::Remove\&.
.RE
.PP
\fB\-\-auto\-remove\fR
.RS 4
Si la commande utilisée est soit
install
soit
remove, cette option a le même effet qu\*(Aqautoremove
et supprime les paquets de dépendance inutilisés\&. Élément de configuration\ \&:
APT::Get::Upgrade\&.
.RE
.PP
\fB\-\-only\-source\fR
.RS 4
Cette option n\*(Aqa de sens qu\*(Aqavec les commandes
source
et
build\-dep\&. Elle indique que les noms de sources donnés ne doivent pas être repérés à travers le tableau des binaires\&. Cela signifie que si cette option est choisie, la commande
source
acceptera seulement des noms de paquets source comme argument\ \&; elle n\*(Aqacceptera pas de les rechercher à partir des noms de paquets binaires correspondants\&. Élément de configuration\ \&:
APT::Get::Only\-Source
.RE
.PP
\fB\-\-diff\-only\fR, \fB\-\-dsc\-only\fR, \fB\-\-tar\-only\fR
.RS 4
Ne télécharger que le fichier \&.diff, \&.dsc ou \&.tar d\*(Aqune archive source\&. Élément de configuration\ \&:
APT::Get::Diff\-Only,
APT::Get::Dsc\-Only
et
APT::Get::Tar\-Only,
.RE
.PP
\fB\-\-arch\-only\fR
.RS 4
Ne traiter que les dépendances de construction dépendantes de l\*(Aqarchitecture\&. Élément de configuration\ \&:
APT::Get::Arch\-Only\&.
.RE
.PP
\fB\-\-allow\-unauthenticated\fR
.RS 4
Ignorer le fait que les paquets ne peuvent pas être authentifiés\ \&; ne le signale pas à l\*(Aqutilisateur\&. Cette option est très utile pour certains outils comme pbuilder\&. Élément de configuration\ \&:
APT::Get::AllowUnauthenticated\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Afficher un bref résumé de l\*(Aqutilisation\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Afficher la version du programme\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Fichier de configuration\ \&; indique le fichier de configuration à utiliser\&. Le programme lira le fichier de configuration par défaut puis le fichier indiqué ici\&. Veuillez consulter
\fBapt.conf\fR(5)
pour des informations sur la syntaxe d\*(Aqutilisation\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Définir une option de configuration\ \&; permet de régler une option de configuration donnée\&. La syntaxe est
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
et
\fB\-\-option\fR
peuvent être utilisées plusieurs fois pour définir des options différentes\&.
.RE
.SH "FICHIERS"
.PP
/etc/apt/sources\&.list
.RS 4
Emplacement pour la récupération des paquets\&. Élément de configuration\ \&:
Dir::Etc::SourceList\&.
.RE
.PP
/etc/apt/sources\&.list\&.d/
.RS 4
Fragments de fichiers définissant les emplacements de récupération de paquets\&. Élément de configuration\ \&:
Dir::Etc::SourceParts\&.
.RE
.PP
/etc/apt/apt\&.conf
.RS 4
Fichier de configuration d\*(AqAPT\&. Élément de configuration\ \&:
Dir::Etc::Main\&.
.RE
.PP
/etc/apt/apt\&.conf\&.D/
.RS 4
Fragments du fichier de configuration d\*(AqAPT\&. Élément de configuration\ \&:
Dir::Etc::Parts\&.
.RE
.PP
/etc/apt/preferences
.RS 4
Fichier des préférences\&. C\*(Aqest dans ce fichier qu\*(Aqon peut faire de l\*(Aqétiquetage (pinning) c\*(Aqest\-à\-dire, choisir d\*(Aqobtenir des paquets d\*(Aqune source distincte ou d\*(Aqune distribution différente\&. Élément de configuration\ \&:
Dir::Etc::Preferences\&.
.RE
.PP
/etc/apt/preferences\&.d/
.RS 4
Fragments de fichiers pour la préférence des versions\&. Élément de configuration\ \&:
Dir::Etc::PreferencesParts\&.
.RE
.PP
/var/cache/apt/archives/
.RS 4
Zone de stockage des fichiers récupérés\&. Élément de configuration\ \&:
Dir::Cache::Archives\&.
.RE

Z     .PP
/var/cache/apt/archives/partial/
.RS 4
Zone de stockage pour les paquets en transit\&. Élément de configuration\ \&:
Dir::Cache::Archives
(implicitement, partial)\&.
.RE
.PP
/var/lib/apt/lists/
.RS 4
Zone de stockage pour les informations qui concernent chaque ressource de paquet spécifiée dans
\fBsources.list\fR(5)
Élément de configuration\ \&:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
Zone de stockage pour les informations en transit\&. Élément de configuration\ \&:
Dir::State::Lists
(implicit partial)\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBapt-cache\fR(8),
\fBapt-cdrom\fR(8),
\fBdpkg\fR(1),
\fBdselect\fR(1),
\fBsources.list\fR(5),
\fBapt.conf\fR(5),
\fBapt-config\fR(8), le guide d\*(AqAPT dans /usr/share/doc/apt\-doc/,
\fBapt_preferences\fR(5), le \(Fo\ \&HOWTO\ \&\(Fc d\*(AqAPT\&.
.SH "DIAGNOSTICS"
.PP
\fBapt\-get\fR
renvoie zéro après une opération normale, le décimal 100 en cas d\*(Aqerreur\&.
.SH "AUTEURS D'ORIGINE"
.PP

Jason Gunthorpe
.SH "AUTEURS ACTUELS"
.PP

Équipe de développement d\*(AqAPT
.PP

\m[blue]\fBPage qualité\fR\m[]\&\s-2\u[1]\d\s+2
.SH "BOGUES"
.PP
\m[blue]\fBPage des bogues d\*(AqAPT\fR\m[]\&\s-2\u[2]\d\s+2\&. Si vous souhaitez signaler un bogue à propos d\*(AqAPT, veuillez lire
/usr/share/doc/debian/bug\-reporting\&.txt
ou utiliser la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTEURS"
.PP
Jérôme Marant, Philippe Batailler, Christian Perrier
bubulle@debian\&.org
(2000, 2005, 2009, 2010), Équipe de traduction francophone de Debian
debian\-l10n\-french@lists\&.debian\&.org
.PP
Veuillez noter que cette traduction peut contenir des parties non traduites Cela est volontaire, pour éviter de perdre du contenu quand la traduction est légèrement en retard sur le contenu d\*(Aqorigine\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBÉquipe de développement d\*(AqAPT\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
Page qualité
.RS 4
\%http://packages.qa.debian.org/a/apt.html
.RE
.IP " 2." 4
Page des bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
