'\" t
.\"     Title: apt-cache
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 29 F\('evrier 2004
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT\-CACHE" "8" "29 F\('evrier 2004" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt-cache \- Gestion des paquets et manipulation du cache par APT
.SH "SYNOPSIS"
.HP \w'\fBapt\-cache\fR\ 'u
\fBapt\-cache\fR [\fB\-hvsn\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] {[add\ \fIfichier\fR...] | [gencaches] | [showpkg\ \fIpaquet\fR...] | [showsrc\ \fIpaquet\fR...] | [stats] | [dump] | [dumpavail] | [unmet] | [search\ \fIregex\fR] | [show\ \fIpaquet\fR...] | [depends\ \fIpaquet\fR...] | [rdepends\ \fIpaquet\fR...] | [pkgnames\ \fIprefix\fR] | [dotty\ \fIpaquet\fR...] | [policy\ \fIpaquets\fR...] | [madison\ \fIpaquets\fR...]}
.SH "DESCRIPTION"
.PP

\fBapt\-cache\fR
r\('ealise diff\('erentes op\('erations sur le cache de paquet d\' APT\&.
\fBapt\-cache\fR
ne manipule pas l\'\('etat du syst\(`eme mais fournit des moyens de recherche dans les m\('etadonn\('ees d\'un paquet desquelles il extrait d\'int\('eressantes informations\&.
.PP
\(`A moins que l\'option
\fB\-h\fR
ou
\fB\-\-help\fR
ne soit donn\('ee, l\'une des commandes suivantes doit \(^etre pr\('esente\&.
.PP
add \fIfichier(s)\fR
.RS 4
La commande
add
ajoute des fichiers indexant des paquets au cache des paquets\&. Cela sert uniquement pour le d\('ebogage\&.
.RE
.PP
gencaches
.RS 4
La commande
gencaches
fait la m\(^eme chose que
\fBapt\-get check\fR\&. Elle construit les caches des sources et des paquets \(`a partir des sources r\('epertori\('ees dans
\fBsources.list\fR(5)et dans
/var/lib/dpkg/status\&.
.RE
.PP
showpkg \fIpaquet(s)\fR
.RS 4
La commande
showpkg
affiche des informations sur les paquets donn\('es en argument\&. Les arguments restants sont les noms de paquets\&. Les versions disponibles et les d\('ependances inverses de chaque paquet r\('epertori\('e sont list\('ees, ainsi que les d\('ependances normales pour chaque version\&. Les d\('ependances normales d\'un paquet sont constitu\('ees par les paquets dont il d\('epend\ \&; les d\('ependances inverses sont les paquets qui d\('ependent du paquet en question\&. Les d\('ependances normales doivent donc \(^etre satisfaites et les d\('ependances inverses n\'ont pas besoin de l\'\(^etre\&. Ainsi, la commande
\fBapt\-cache showpkg libreadline2\fR
donnera ce r\('esultat\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Package: libreadline2
Versions: 2\&.1\-12(/var/state/apt/lists/foo_Packages),
Reverse Depends: 
  libreadlineg2,libreadline2
  libreadline2\-altdev,libreadline2
Dependencies:
2\&.1\-12 \- libc5 (2 5\&.4\&.0\-0) ncurses3\&.0 (0 (null))
Provides:
2\&.1\-12 \- 
Reverse Provides: 
.fi
.if n \{\
.RE
.\}
On peut voir que libreadline2, version 2\&.1\-12, d\('epend de libc5, ncurses3\&.0\ \&; ces paquets doivent \(^etre install\('es au pr\('ealable pour que libreadline2 fonctionne\&. \(`A leur tour, libreadlineg2 et libreadline2\-altdev d\('ependent de libreadline2\&. Si libreadline2 est install\('e, libc5 et ncurses3\&.0 doivent \(^etre install\('es\ \&; libreadlineg2 et libreadline2\-altdev n\'ont pas \(`a l\'\(^etre\&. Pour conna\(^itre le sens de la fin de cha\(^ine, il est pr\('ef\('erable de consulter le code source d\'APT\&.
.RE
.PP
stats
.RS 4
La commande
stats
affiche des statistiques \(`a propos du cache\&. Aucun autre argument n\'est attendu\&. Voici les informations rapport\('ees\ \&:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Total package names
est le nombre de paquets trouv\('es dans le cache\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Normal packages
est le nombre de paquets simples, ordinaires\ \&; ces paquets tol\(`erent une correspondance bijective entre leur nom et le nom utilis\('e par les autres paquets pour les qualifier comme d\('ependance\&. La majorit\('e des paquets appartient \(`a cette cat\('egorie\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Pure virtual packages
est le nombre des paquets qui n\'existent que sous la forme d\'un nom repr\('esentant un paquet virtuel\ \&; ces paquets \(Fo\ \&fournissent\ \&\(Fc seulement un nom de paquet virtuel et aucun paquet n\'utilise v\('eritablement ce nom\&. Par exemple, au sein du syst\(`eme Debian GNU/Linux, le nom \(Fo\ \&mail\-transport\-agent\ \&\(Fc est un paquet virtuel pur\ \&; plusieurs paquets peuvent \(Fo\ \&remplir\ \&\(Fc ce nom \(Fo\ \&mail\-transport\-agent\ \&\(Fc, mais il n\'existe aucun paquet nomm\('e \(Fo\ \&mail\-transport\-agent\ \&\(Fc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Single virtual packages
est le nombre de paquets virtuels qui ne peuvent \(^etre remplis que par un seul paquet\&. Par exemple, au sein du syst\(`eme Debian GNU/Linux, \(Fo\ \&X11\-text\-viewer\ \&\(Fc est un paquet virtuel\ \&; seul le paquet \(Fo\ \&xless\ \&\(Fc remplit \(Fo\ \&X11\-text\-viewer\ \&\(Fc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Mixed virtual packages
est le nombre des paquets qui remplissent un paquet virtuel particulier ou dont le nom est un nom de paquet virtuel\&. Par exemple, au sein du syst\(`eme Debian GNU/Linux, \(Fo\ \&debconf\ \&\(Fc est un paquet r\('eel et il est aussi fourni par \(Fo\ \&debconf\-tiny\ \&\(Fc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Missing
est le nombre de paquets r\('ef\('erenc\('es dans une d\('ependance mais qui ne sont fournis par aucun paquet\&. Les paquets manquants peuvent \(^etre mis en \('evidence quand on n\'acc\(`ede pas \(`a une distribution compl\(`ete ou si un paquet (r\('eel ou virtuel) a \('et\('e sorti d\'une distribution\&. Habituellement on les trouve dans les champs \(Fo\ \&Conflicts\ \&\(Fc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Total distinct versions
est le nombre de versions de paquets trouv\('ees dans le cache\ \&; cette valeur est par cons\('equent au moins \('egale au nombre total de paquets\&. Quand on acc\(`ede \(`a plus d\'une distribution (\(Fo\ \&stable\ \&\(Fc et \(Fo\ \&unstable\ \&\(Fc, par exemple), cette valeur peut \(^etre consid\('erablement plus grande que le nombre total de paquets\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Total dependencies
est le nombre de relations de d\('ependances d\('eclar\('ees par tous les paquets pr\('esents dans le cache\&.
.RE
.RS 4
.RE
.PP
showsrc \fIpaquet(s)\fR
.RS 4

showsrc
affiche toutes les entr\('ees de paquet source qui correspondent aux noms donn\('es\&. Toutes les versions sont affich\('ees et toutes les entr\('ees qui d\('eclarent que ces noms correspondent \(`a des paquets binaires\&.
.RE
.PP
dump
.RS 4
La commande
dump
affiche un court r\('esum\('e sur chaque paquet du cache\&. Elle est d\'abord destin\('ee au d\('ebogage\&.
.RE
.PP
dumpavail
.RS 4
La commande
dumpavail
affiche sur la sortie standard une liste des paquets disponibles\&. Elle convient \(`a une utilisation avec
\fBdpkg\fR(8)
et la m\('ethode
\fBdselect\fR(8)
s\'en sert\&.
.RE
.PP
unmet
.RS 4
La commande
unmet
affiche un r\('esum\('e concernant toutes les d\('ependances absentes dans le cache de paquets\&.
.RE
.PP
show \fIpaquet(s)\fR
.RS 4
La commande
show
est semblable \(`a
\fBdpkg \-\-print\-avail\fR\ \&; elle affiche des informations sur les paquets donn\('es en argument\&.
.RE
.PP
search \fIregex [ regex \&.\&.\&. ]\fR
.RS 4
La commande
search
recherche l\'expression r\('eguli\(`ere donn\('ee en argument sur tous les paquets disponibles\&. Elle cherche une occurrence de la cha\(^ine dans les noms de paquets et dans les descriptions puis elle affiche le nom du paquet et sa description courte\&. Quand on donne l\'option
\fB\-\-full\fR, la sortie est identique \(`a
show
pour chaque paquet\ \&; l\'option
\fB\-\-names\-only\fR
ne recherche pas la cha\(^ine dans les descriptions longues mais seulement dans les noms de paquets\&.
.sp
On peut utiliser des arguments distincts pour indiquer des expressions r\('eguli\(`eres diff\('erentes sur lesquelles sera r\('ealis\('e un \(Fo\ \&et\ \&\(Fc logique\&.
.RE
.PP
depends \fIpaquet(s)\fR
.RS 4
La commande
depends
affiche la liste de toutes les d\('ependances d\'un paquet et la liste de tous les paquets possibles qui satisfont ces d\('ependances\&.
.RE
.PP
rdepends \fIpaquet(s)\fR
.RS 4
La commande
rdepends
affiche la liste de toutes les d\('ependances inverses d\'un paquet\&.
.RE
.PP
pkgnames \fI[ prefix ]\fR
.RS 4
Cette commande affiche le nom de chaque paquet du syst\(`eme\&. Un pr\('efixe pour filtrer la liste des noms peut \(^etre donn\('e en argument\&. La sortie est appropri\('ee \(`a une utilisation au sein d\'une fonction compl\(`ete de shell\ \&; elle est produite tr\(`es rapidement\&. On utilise au mieux cette commande avec l\'option
\fB\-\-generate\fR\&.
.RE
.PP
dotty \fIpaquet(s)\fR
.RS 4
La commande
dotty
prend une liste de paquets sur la ligne de commande et affiche une sortie appropri\('ee \(`a une utilisation par la commande dotty du paquet
\m[blue]\fBGraphViz\fR\m[]\&\s-2\u[1]\d\s+2\&. Il en r\('esulte un ensemble de noeuds et d\'arcs repr\('esentant les relations entre les paquets\&. Par d\('efaut les paquets donn\('es en argument suivent toutes leurs d\('ependances, ce qui peut produire un graphe tr\(`es volumineux\&. Pour limiter la sortie aux seuls paquets list\('es sur la ligne de commande, positionnez l\'option
APT::Cache::GivenOnly\&.
.sp
Les noeuds r\('esultants ont plusieurs formes\ \&; les paquets normaux sont des bo\(^ites, les \(Fo\ \&provides\ \&\(Fc purs sont des triangles, les \(Fo\ \&provides\ \&\(Fc mixtes sont des diamants et les paquets manquants sont des hexagones\&. Les bo\(^ites oranges expriment un arr\(^et de la r\('ecursivit\('e [paquet feuille], les lignes bleues repr\('esentent des pr\('ed\('ependances et les lignes vertes repr\('esentent des conflits\&.
.sp
Attention, dotty ne peut pas repr\('esenter des ensembles tr\(`es grands de paquets\&.
.RE
.PP
policy \fI[ paquet(s) ]\fR
.RS 4

policy
sert \(`a d\('eboguer des probl\(`emes relatifs au fichier des pr\('ef\('erences\&. Sans argument, la commande affiche la priorit\('e de chaque source\&. Sinon, elle affiche des informations pr\('ecises sur la priorit\('e du paquet donn\('e en argument\&.
.RE
.PP
madison \fI[ paquet(s) ]\fR
.RS 4
La commande
madison
d\'apt\-cache
cherche \(`a mimer le format de sortie propre \(`a l\'outil debian de gestion d\'archives,
madison, ainsi qu\'une part de ses fonctionnalit\('es\&. Elle affiche les versions disponibles d\'un paquet dans un tableau\&. Contrairement au programme original
madison, elle n\'affiche que des informations concernant l\'architecture pour laquelle Apt a lu la liste des paquets disponibles (APT::Architecture)\&.
.RE
.SH "OPTIONS"
.PP
Toutes les options en ligne de commande peuvent \(^etre positionn\('ees via le fichier de configuration\ \&; les descriptifs indiquent l\'option de configuration \(`a positionner\&. En ce qui concerne les options bool\('eennes, on peut annuler le fichier de configuration en utilisant quelque chose comme
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou d\'autres variantes\&.
.PP
\fB\-p\fR, \fB\-\-pkg\-cache\fR
.RS 4
Indique le fichier servant de cache des paquets\&. Le cache des paquets est le cache primaire utilis\('e par toutes les op\('erations\&. \('El\('ement de configuration\ \&:
Dir::Cache::pkgcache\&.
.RE
.PP
\fB\-s\fR, \fB\-\-src\-cache\fR
.RS 4
Indique le fichier servant de cache des sources\&. Ce cache n\'est utilis\('e que par
gencaches\ \&; une version des informations sur les paquets, faite \(`a partir d\'une analyse de sources distantes, est conserv\('ee\&. Quand le cache des paquets est cr\('e\('e, le cache des sources est utilis\('e afin d\'\('eviter d\'analyser \(`a nouveau tous les paquets\&. \('El\('ement de configuration\ \&:
Dir::Cache::srcpkgcache\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Mode silencieux\ \&; produit une sortie pertinente pour l\'enregistrement dans un fichier\-journal, sans afficher d\'indicateur de progression\&. Un plus grand nombre de q produira un plus grand silence, avec un maximum de 2\&. Vous pouvez aussi utiliser
\fB\-q=#\fR
pour positionner le niveau de silence, annulant le fichier de configuration\&. \('El\('ement de configuration\ \&:
quiet\&.
.RE
.PP
\fB\-i\fR, \fB\-\-important\fR
.RS 4
N\'affiche que les d\('ependances importantes\ \&; \(`a utiliser avec la commande unmet pour n\'afficher que les relations Depends et Pre\-Depends\&. \('El\('ement de configuration\ \&:
APT::Cache::Important\&.
.RE
.PP
\fB\-f\fR, \fB\-\-full\fR
.RS 4
Affiche la totalit\('e des champs d\'information sur le paquet lors d\'une recherche\&. \('El\('ement de configuration\ \&:
APT::Cache::ShowFull\&.
.RE
.PP
\fB\-a\fR, \fB\-\-all\-versions\fR
.RS 4
Affiche la totalit\('e des champs d\'information pour toutes les versions disponibles\ \&: c\'est la valeur par d\('efaut\&. Pour la d\('esactiver, utilisez l\'option
\fB\-\-no\-all\-versions\fR\&. Quand l\'option
\fB\-\-no\-all\-versions\fR
est choisie, seuls les \('el\('ements de la version choisie (celle qui serait install\('ee) seront affich\('es\&. Cette option concerne seulement la commande
show\&. \('El\('ement de configuration\ \&:
APT::Cache::AllVersions\&.
.RE
.PP
\fB\-g\fR, \fB\-\-generate\fR
.RS 4
R\('ealise une mise \(`a jour automatique du cache des paquets plut\(^ot que de se servir du cache actuel\&. Pour d\('esactiver cette option (option par d\('efaut), utilisez l\'option
\fB\-\-no\-generate\fR\&. \('El\('ement de configuration\ \&:
APT::Cache::Generate\&.
.RE
.PP
\fB\-\-names\-only\fR, \fB\-n\fR
.RS 4
N\'effectue une recherche que sur les noms de paquets et pas sur les descriptions longues\&. \('El\('ement de configuration\ \&:
APT::Cache::NamesOnly\&.
.RE
.PP
\fB\-\-all\-names\fR
.RS 4
Avec cette option
pkgnames
affiche tous les noms, les noms des paquets virtuels et les d\('ependances manquantes\&. \('El\('ement de configuration\ \&:
APT::Cache::AllNames\&.
.RE
.PP
\fB\-\-recurse\fR
.RS 4
Avec cette option
depends
et
rdepends
sont r\('ecursives de mani\(`ere \(`a n\'afficher qu\'une seule fois les paquets mentionn\('es\&. \('El\('ement de configuration\ \&:
APT::Cache::RecurseDepends\&.
.RE
.PP
\fB\-\-installed\fR
.RS 4
Cette option limite la sortie de
depends
et de
rdepends
aux paquets qui sont actuellement install\('es\&. \('El\('ement de configuration\ \&:
APT::Cache::Installed\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Affiche un mode d\'emploi succinct\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Affiche la version du programme\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Fichier de configuration\ \&; indique quel fichier de configuration utiliser\&. Le programme lit le fichier de configuration par d\('efaut, puis celui\-ci\&. Voyez
\fBapt.conf\fR(5)
pour la syntaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Donne une option de configuration\ \&; cela fixe une option de configuration arbitraire\&. La syntaxe est :
\fB\-o Foo::Bar=bar\fR\&.
.RE
.SH "FICHIERS"
.PP
/etc/apt/sources\&.list
.RS 4
Emplacements o\(`u aller chercher les paquets\&. \('El\('ement de configuration\ \&:
Dir::Etc::SourceList\&.
.RE
.PP
/var/lib/apt/lists/
.RS 4
Zone de stockage pour les informations qui concernent chaque ressource de paquet sp\('ecifi\('ee dans
\fBsources.list\fR(5)\('El\('ement de configuration\ \&:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
Zone de stockage pour les informations en transit\&. \('El\('ement de configuration\ \&:
Dir::State::Lists
(partial est implicite)\&.
.RE
.SH "VOIR AUSSI"
.PP

\fBapt.conf\fR(5),
\fBsources.list\fR(5),
\fBapt-get\fR(8)\&.
.SH "DIAGNOSTICS"
.PP

\fBapt\-cache\fR
retourne z\('ero apr\(`es un d\('eroulement normal, et le nombre d\('ecimal 100 en cas d\'erreur\&.
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[2]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTION"
.PP
J\('er\(^ome Marant\&. 2000\ \&; mise \(`a jour : Philippe Batailler\&. 2005\&.
debian\-l10n\-french@lists\&.debian\&.org\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.PP
\fBAPT team\fR
.RS 4
Auteur.
.RE
.SH "NOTES"
.IP " 1." 4
GraphViz
.RS 4
\%http://www.research.att.com/sw/tools/graphviz/
.RE
.IP " 2." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
