'\" t
.\"     Title: apt-config
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 29
février 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-CONFIG" "8" "29 février 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-config \- Programme d\*(Aqinterrogation de la configuration d\*(AqAPT
.SH "SYNOPSIS"
.HP \w'\fBapt\-config\fR\ 'u
\fBapt\-config\fR [\fB\-hv\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] {[shell] | [dump]}
.SH "DESCRIPTION"
.PP
\fBapt\-config\fR
est un programme interne utilisé par différents composants d\*(AqAPT\ \&; il offre la possibilité d\*(Aqune configuration cohérente et permet aux applications conçues sous forme de script une utilisation simple du fichier de configuration principal
/etc/apt/apt\&.conf\&.
.PP
À moins que l\*(Aqoption
\fB\-h\fR
ou
\fB\-\-help\fR
ne soit donnée, l\*(Aqune des commandes suivantes doit être présente\&.
.PP
shell
.RS 4
Le terme shell est utilisé pour accéder aux informations de configuration depuis un script shell\&. Deux arguments doivent lui être donnés\ \&; le premier est une variable du shell et le second une valeur de configuration à demander\&. La sortie standard consiste en une liste de commandes d\*(Aqassignation de shell pour chaque valeur présente\&. Dans un script shell, cette commande devrait être utilisée comme suit\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
OPTS="\-f"
RES=`apt\-config shell OPTS MyApp::Options`
eval $RES
.fi
.if n \{\
.RE
.\}
La variable d\*(Aqenvironnement du shell $OPTS sera définie par la valeur de MyApp::Options ou, par défaut, la valeur \-f\&.
.sp
L\*(Aqélément de configuration peut être suivi par /[fdbi]\&. \(Fo\ \&f\ \&\(Fc renvoie un nom de fichier, \(Fo\ \&d\ \&\(Fc un nom de répertoire, \(Fo\ \&b\ \&\(Fc renvoie \(Fo\ \&true\ \&\(Fc ou \(Fo\ \&false\ \&\(Fc et \(Fo\ \&i\ \&\(Fc renvoie un entier\&. Chacune de ses valeurs est normalisée et vérifiée\&.
.RE
.PP
dump
.RS 4
Affiche seulement le contenu de l\*(Aqespace de configuration\&.
.RE
.SH "OPTIONS"
.PP
Toutes les options de la ligne de commande peuvent être définies dans le fichier de configuration, les descriptions indiquant l\*(Aqoption de configuration concernée\&. Pour les options booléennes, vous pouvez inverser les réglages du fichiers de configuration avec
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
et d\*(Aqautres variantes analogues\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Afficher un bref résumé de l\*(Aqutilisation\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Afficher la version du programme\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Fichier de configuration\ \&; indique le fichier de configuration à utiliser\&. Le programme lira le fichier de configuration par défaut puis le fichier indiqué ici\&. Veuillez consulter
\fBapt.conf\fR(5)
pour des informations sur la syntaxe d\*(Aqutilisation\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Définir une option de configuration\ \&; permet de régler une option de configuration donnée\&. La syntaxe est
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
et
\fB\-\-option\fR
peuvent être utilisées plusieurs fois pour définir des options différentes\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBapt.conf\fR(5)
.SH "DIAGNOSTICS"
.PP
\fBapt\-config\fR
retourne zéro après un déroulement normal, et le nombre 100 en cas d\*(Aqerreur\&.
.SH "BOGUES"
.PP
\m[blue]\fBPage des bogues d\*(AqAPT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous souhaitez signaler un bogue à propos d\*(AqAPT, veuillez lire
/usr/share/doc/debian/bug\-reporting\&.txt
ou utiliser la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTEURS"
.PP
Jérôme Marant, Philippe Batailler, Christian Perrier
bubulle@debian\&.org
(2000, 2005, 2009, 2010), Équipe de traduction francophone de Debian
debian\-l10n\-french@lists\&.debian\&.org
.PP
Veuillez noter que cette traduction peut contenir des parties non traduites Cela est volontaire, pour éviter de perdre du contenu quand la traduction est légèrement en retard sur le contenu d\*(Aqorigine\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBÉquipe de développement d\*(AqAPT\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
Page des bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
