'\" t
.\"     Title: apt-sortpkgs
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 29
février 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-SORTPKGS" "1" "29 février 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-sortpkgs \- Outil de tri des index de paquets\&.
.SH "SYNOPSIS"
.HP \w'\fBapt\-sortpkgs\fR\ 'u
\fBapt\-sortpkgs\fR [\fB\-hvs\fR] [\fB\-o=\fR\fB\fIoption\ de\ configuration\fR\fR] [\fB\-c=\fR\fB\fIfichier\fR\fR] \fIfichier\fR...
.SH "DESCRIPTION"
.PP
\fBApt\-sortpkgs\fR
prend un index (un index de Source ou un index de paquet) et trie leurs enregistrements selon le nom de paquet\&. Un tri des champs de chaque enregistrement est réalisé selon des règles internes\&.
.PP
Le résultat est envoyé sur la sortie standard\ \&; l\*(Aqentrée doit être un fichier analysable\&.
.SH "OPTIONS"
.PP
Toutes les options de la ligne de commande peuvent être définies dans le fichier de configuration, les descriptions indiquant l\*(Aqoption de configuration concernée\&. Pour les options booléennes, vous pouvez inverser les réglages du fichiers de configuration avec
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
et d\*(Aqautres variantes analogues\&.
.PP
\fB\-s\fR, \fB\-\-source\fR
.RS 4
Utiliser un index de sources pour le tri des champs\&. Élément de configuration\ \&:
APT::SortPkgs::Source\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Afficher un bref résumé de l\*(Aqutilisation\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Afficher la version du programme\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Fichier de configuration\ \&; indique le fichier de configuration à utiliser\&. Le programme lira le fichier de configuration par défaut puis le fichier indiqué ici\&. Veuillez consulter
\fBapt.conf\fR(5)
pour des informations sur la syntaxe d\*(Aqutilisation\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Définir une option de configuration\ \&; permet de régler une option de configuration donnée\&. La syntaxe est
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
et
\fB\-\-option\fR
peuvent être utilisées plusieurs fois pour définir des options différentes\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBapt.conf\fR(5)
.SH "DIAGNOSTICS"
.PP
\fBapt\-sortpkgs\fR
retourne zéro si tout se passe bien ou 100 en cas d\*(Aqerreur\&.
.SH "BOGUES"
.PP
\m[blue]\fBPage des bogues d\*(AqAPT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous souhaitez signaler un bogue à propos d\*(AqAPT, veuillez lire
/usr/share/doc/debian/bug\-reporting\&.txt
ou utiliser la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTEURS"
.PP
Jérôme Marant, Philippe Batailler, Christian Perrier
bubulle@debian\&.org
(2000, 2005, 2009, 2010), Équipe de traduction francophone de Debian
debian\-l10n\-french@lists\&.debian\&.org
.PP
Veuillez noter que cette traduction peut contenir des parties non traduites Cela est volontaire, pour éviter de perdre du contenu quand la traduction est légèrement en retard sur le contenu d\*(Aqorigine\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBÉquipe de développement d\*(AqAPT\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
Page des bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
