'\" t
.\"     Title: apt-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 14 d\('ecembre 2003
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT\-KEY" "8" "14 d\('ecembre 2003" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt-key \- Utilitaire de gestion des cl\('es
.SH "SYNOPSIS"
.HP \w'\fBapt\-key\fR\ 'u
\fBapt\-key\fR [\fIcommand\fR/] [\fB\fIarguments\fR\fR...]
.SH "DESCRIPTION"
.PP

\fBapt\-key\fR
g\(`ere les cl\('es dont se sert apt pour authentifier les paquets\&. Les paquets authentifi\('es par ces cl\('es seront r\('eput\('es fiables\&.
.SH "COMMANDES"
.PP
add \fIfichier\fR
.RS 4
Ajouter une cl\('e \(`a la liste des cl\('es fiables\&. La cl\('e est lue dans
\fIfichier\fR, ou sur l\'entr\('ee standard si
\fIfichier\fR
est
\-\&.
.RE
.PP
del \fIkeyid\fR
.RS 4
Supprimer une cl\('e de la liste des cl\('es fiables\&.
.RE
.PP
list
.RS 4
Afficher la liste des cl\('es fiables\&.
.RE
.PP
update
.RS 4
Mettre \(`a jour le trousseau de cl\('es local avec le trousseau de cl\('es de l\'archive Debian et supprimer les cl\('es qui sont p\('erim\('ees\&.
.RE
.SH "FICHIERS"
.PP
/etc/apt/trusted\&.gpg
.RS 4
Trousseau de cl\('es locales fiables, les nouvelles cl\('es sont ajout\('ees ici\&.
.RE
.PP
/etc/apt/trustdb\&.gpg
.RS 4
Base de donn\('ees locale fiable des cl\('es de l\'archive\&.
.RE
.PP
/usr/share/keyrings/debian\-archive\-keyring\&.gpg
.RS 4
Trousseau des cl\('es fiables de l\'archive Debian\&.
.RE
.PP
/usr/share/keyrings/debian\-archive\-removed\-keys\&.gpg
.RS 4
Trousseau des cl\('es fiables supprim\('ees de l\'archive Debian\&.
.RE
.SH "VOIR AUSSI"
.PP

\fBapt-get\fR(8),
\fBapt-secure\fR(8)
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "AUTEUR"
.PP
APT a \('et\('e \('ecrit par l\'\('equipe APT
apt@packages\&.debian\&.org\&.
.SH "TRADUCTION"
.PP
Philippe Batailler\&.
debian\-l10n\-french@lists\&.debian\&.org\&. 2005\&.
.SH "AUTEUR"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.SH "COPYRIGHT"
.br
CopyrightCopyright \(co 1998-2001 Jason Gunthorpe
.br
.SH "NOTES"
.IP " 1." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
