'\" t
.\"     Title: apt-secure
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 14 d\('ecembre 2003
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT\-SECURE" "8" "14 d\('ecembre 2003" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt-secure \- Certification d\'archive avec APT
.SH "DESCRIPTION"
.PP
Depuis sa version 0\&.6,
\fBapt\fR
sait v\('erifier la signature du fichier Release de chaque archive\&. On s\'assure ainsi que les paquets de cette archive ne peuvent pas \(^etre modifi\('es par quelqu\'un qui ne poss\(`ede pas la cl\('e de la signature du fichier Release\&.
.PP
Quand un paquet provient d\'une archive sans signature ou d\'une archive avec une signature dont apt ne poss\(`ede pas la cl\('e, ce paquet n\'est pas consid\('er\('e comme fiable et son installation provoquera un avertissement\&. Pour l\'instant,
\fBapt\-get\fR
ne signale que les archives sans signature\ \&; les prochaines versions pourraient rendre obligatoire la v\('erification des sources avant tout t\('el\('echargement de paquet\&.
.PP
Les paquets
\fBapt-get\fR(8),
\fBaptitude\fR(8)
et
\fBsynaptic\fR(8)
poss\(`edent cette nouvelle fonction de certification\&.
.SH "ARCHIVES FIABLES"
.PP
D\'une archive apt jusqu\'\(`a l\'utilisateur, la confiance se construit en plusieurs \('etapes\&.
\fBApt\-secure\fR
est la derni\(`ere \('etape\&. Faire confiance \(`a une archive ne signifie pas que les paquets qu\'elle contient sont exempts de code malveillant, mais signifie que vous faites confiance au responsable de l\'archive\&. C\'est ensuite au responsable de l\'archive de faire en sorte que l\'archive soit fiable\&.
.PP
\fBApt\-secure\fR
n\'examine pas la signature d\'un paquet\&. Certains programmes peuvent le faire comme
\fBdebsig\-verify\fR
ou
\fBdebsign\fR, qu\'on peut trouver dans les paquets debsig\-verify et devscripts\&.
.PP
La fiabilisation dans Debian commence quand un responsable de paquet envoie un nouveau paquet ou une nouvelle version d\'un paquet dans l\'archive\&. Cet envoi, pour \(^etre effectif, doit \(^etre sign\('e avec la cl\('e d\'un responsable qui se trouve dans le trousseau des responsables Debian (disponible dans le paquet debian\-keyring)\&. Les cl\('es des responsables de paquet sont sign\('ees par d\'autres responsables, suivant des proc\('edures pr\('e\('etablies pour s\'assurer de l\'identit\('e des propri\('etaires de la cl\('e\&.
.PP
Une fois le paquet v\('erifi\('e et archiv\('e, la signature du responsable est enlev\('ee, une somme MD5 du paquet est calcul\('ee et mise dans le fichier Packages\&. Une somme MD5 de tous les paquets est ensuite calcul\('ee et mise dans le fichier Release\&. Ce fichier est sign\('e par la cl\('e de l\'archive\&. Cette cl\('e qui est cr\('e\('ee chaque ann\('ee et distribu\('ee par le serveur FTP se trouve aussi dans le trousseau Debian\&.
.PP
Un utilisateur peut consulter la signature du fichier Release, extraire la somme MD5 d\'un paquet et la comparer avec la somme du paquet qu\'il a t\('el\('echarg\('e\&. Avant la version 0\&.6, seule la somme du paquet t\('el\('echarg\('e \('etait v\('erifi\('ee\&. Maintenant on peut v\('erifier aussi la signature du fichier Release\&.
.PP
Cette fa\(,con de faire est diff\('erente d\'une v\('erification de la signature d\'un paquet\&. Elle vise \(`a emp\(^echer deux types d\'attaque possibles\ \&:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
L\'attaque de type
\(Fo\ \&homme au milieu\ \&\(Fc\&. Sans v\('erification de signature, quelqu\'un de malveillant peut s\'introduire au milieu du processus de t\('el\('echargement et ins\('erer du code soit en contr\(^olant un \('el\('ement du r\('eseau, routeur, commutateur, etc\&. soit en d\('etournant le trafic vers un serveur fourbe (par usurpation d\'adresses)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
L\'attaque par compromission d\'un miroir sur le r\('eseau\&. Sans v\('erification de signature, quelqu\'un de malveillant peut compromettre un miroir et modifier les fichiers\&. Ainsi tous ceux qui t\('el\('echargent les paquets de ce miroir propagent du code malveillant\&.
.RE
.PP
Cependant cette m\('ethode ne garantit pas contre une compromission du serveur Debian lui\-m\(^eme (qui signe les paquets) ni contre la compromission de la cl\('e qui sert \(`a signer les fichiers Release\&. Mais elle peut compl\('eter la signature des paquets\&.
.SH "CONFIGURATION"
.PP
Le programme qui g\(`ere la liste des cl\('es utilis\('ees par apt s\'appelle
\fBapt\-key\fR\&. Il peut ajouter ou supprimer des cl\('es\&. Cette version installe automatiquement les cl\('es qui servent \(`a signer l\'archive Debian et les diff\('erents r\('epertoires de paquets\&.
.PP
Pour ajouter une cl\('e, vous devez d\'abord la t\('el\('echarger\&. Il vaut mieux utiliser un canal fiable pour ce t\('el\('echargement\&. Ensuite vous l\'ajoutez avec la commande
\fBapt\-key\fR
et vous lancez la commande
\fBapt\-get update\fR
pour t\('el\('echarger et v\('erifier le fichier
Release\&.gpg
de l\'archive que vous avez configur\('ee\&.
.SH "CONFIGURATION D'UNE ARCHIVE"
.PP
Si vous voulez signer les archives dont vous avez la responsabilit\('e, vous devez\ \&:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
cr\('eer un fichier Release \(`a la racine de l\'archive, s\'il n\'existe pas d\('ej\(`a\&. Vous pouvez le cr\('eer avec la commande
\fBapt\-ftparchive release\fR
(fournie dans le paquet apt\-utils)\ \&;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
le signer, avec la commande
\fBgpg \-abs \-o Release\&.gpg Release\fR\ \&;
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
publier l\'empreinte de la cl\('e\&. Ainsi les utilisateurs de votre archive conna\(^itront la cl\('e qu\'ils doivent importer pour authentifier les fichiers de l\'archive\&.
.RE
.PP
Chaque fois que le contenu de l\'archive change, le responsable doit refaire les deux premi\(`eres \('etapes\&.
.SH "VOIR AUSSI"
.PP

\fBapt.conf\fR(5),
\fBapt-get\fR(8),\fBsources.list\fR(5),
\fBapt-key\fR(8),
\fBapt-ftparchive\fR(1),
\fBdebsign\fR(1),
\fBdebsig-verify\fR(1),
\fBgpg\fR(1)
.PP
Pour des informations plus substantielles, vous pouvez consulter
\m[blue]\fB l\'infrastructure debian pour la s\('ecurit\('e\fR\m[]\&\s-2\u[1]\d\s+2
un chapitre du manuel Debian sur la s\('ecurit\('e (disponible dans le paquet harden\-doc) et le
\m[blue]\fBStrong Distribution HOWTO\fR\m[]\&\s-2\u[2]\d\s+2
par V\&. Alex Brennen\&.
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[3]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "AUTEUR"
.PP
APT a \('et\('e \('ecrit par l\'\('equipe APT
apt@packages\&.debian\&.org\&.
.SH "AUTEURS"
.PP
Cette page a \('et\('e \('ecrite \(`a partir des travaux de Javier Fern\('andez\-Sanguino Pe\(~na, Isaac Jones, Colin Walters, Florian Weimer et Michael Vogt\&.
.SH "TRADUCTION"
.PP
Philippe Batailler\&.
debian\-l10n\-french@lists\&.debian\&.org\&. 2005\&.
.SH "AUTEUR"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.SH "COPYRIGHT"
.br
CopyrightCopyright \(co 1998-2001 Jason Gunthorpe
.br
.SH "NOTES"
.IP " 1." 4
l'infrastructure debian pour la s\('ecurit\('e
.RS 4
\%http://www.debian.org/doc/manuals/securing-debian-howto/ch7.en.html
.RE
.IP " 2." 4
Strong Distribution HOWTO
.RS 4
\%http://www.cryptnet.net/fdp/crypto/strong_distro.html
.RE
.IP " 3." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
