'\" t
.\"     Title: apt.conf
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 11 juillet 2008
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT\&.CONF" "5" "11 juillet 2008" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt.conf \- Fichier de configuration pour APT
.SH "DESCRIPTION"
.PP
Le fichier
apt\&.conf
est le principal fichier de configuration de la collection d\'outils que constitue APT\ \&; tous les outils font appel \(`a ce fichier de configuration et utilisent un analyseur syntaxique en ligne de commande commun afin de fournir un environnement uniforme\&. Quand un outil d\'APT d\('emarre, il lit la configuration d\('esign\('ee par variable d\'environnement
\fBAPT_CONFIG\fR
(si elle existe), puis il lit les fichiers situ\('es dans
Dir::Etc::Parts
ainsi que le principal fichier de configuration indiqu\('e par
Dir::Etc::main\ \&; enfin il applique les options de la ligne de commande qui pr\('evalent sur les directives de configuration, chargeant si n\('ecessaire d\'autres fichiers de configuration\&.
.PP
Le fichier de configuration est construit comme un arbre d\'options organis\('ees en groupes fonctionnels\&. On se sert du double deux points (\(Fo\ \&::\ \&\(Fc) pour indiquer une option\ \&; par exemple,
APT::Get::Assume\-Yes
est une option pour le groupe d\'outils APT, destin\('ee \(`a l\'outil Get\&. Il n\'y a pas d\'h\('eritage des options des groupes parents\&.
.PP
Syntaxiquement, le langage de configuration est con\(,cu sur le m\(^eme mod\(`ele que les langages utilis\('es par des outils ISC tels que bind et dhcp\&. Une ligne qui commence par
//
est trait\('ee comme un commentaire et ignor\('ee, de m\(^eme que les sections de texte plac\('ees entre
/*
et
*/, tout comme les commentaires C/C++\&. Chaque ligne est de la forme\ \&:
.sp .if n \{\ .RS 4 .\} .nf APT::Get::Assume\-Yes "true"; .fi .if n \{\ .RE .\}
Le point\-virgule final est obligatoire et les guillemets sont optionnels\&. On peut d\('eclarer un nouveau champ d\'action avec des accolades, comme suit\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
   
APT {
  Get {
    Assume\-Yes "true";
    Fix\-Broken "true";
  };
};
.fi
.if n \{\
.RE
.\}
.PP
avec des retours \(`a la ligne pour faciliter la lecture\&. On peut cr\('eer une liste en ouvrant un champ d\'action et en y ins\('erant une cha\(^ine entre guillemets suivie d\'un point virgule pour chaque \('el\('ement de la liste\&.
.sp
.if n \{\
.RS 4
.\}
.nf
   
DPkg::Pre\-Install\-Pkgs {"/usr/sbin/dpkg\-preconfigure \-\-apt";};
.fi
.if n \{\
.RE
.\}
.PP
Les mod\(`eles
/usr/share/doc/apt/examples/apt\&.conf
et
/usr/share/doc/apt/examples/configure\-index\&.gz
montrent \(`a quoi devrait ressembler le fichier de configuration\&.
.PP
Les identifiants des options de configuration ne sont pas sensibles \(`a la casse\&. Dans l\'exemple pr\('ec\('edent, on pourrait donc aussi bien utiliser
dpkg::pre\-install\-pkgs\&.
.PP
Deux \('el\('ements sp\('eciaux sont autoris\('es\ \&:
#include
et
#clear\&.
#include
inclut le fichier donn\('e en argument, \(`a moins que le nom ne se termine par une barre oblique auquel cas le r\('epertoire entier est inclus\&.
#clear
sert \(`a effacer une partie de l\'arbre de configuration\&. L\'\('el\('ement d\('esign\('e et tout ses descendants sont supprim\('es\&.
.PP
Tous les outils d\'APT poss\(`edent une option
\fB\-o\fR
qui permet de sp\('ecifier une configuration arbitraire depuis la ligne de commande\&. La syntaxe consiste en un nom complet d\'option (par exemple
APT::Get::Assume\-Yes) suivi par un signe \('egal, puis par la nouvelle valeur de l\'option\&. On peut compl\('eter une liste en ajoutant un \(Fo\ \&::\ \&\(Fc au nom de la liste\&.
.SH "LE GROUPE APT"
.PP
Ce groupe d\'options contr\(^ole le comportement global d\'APT et contient \('egalement des options communes \(`a tous les outils\&.
.PP
Architecture
.RS 4
L\'architecture du syst\(`eme\ \&; cette option positionne l\'architecture \(`a utiliser pour r\('ecup\('erer des fichiers et analyser des listes de paquets\&. La valeur interne par d\('efaut est l\'architecture pour laquelle APT a \('et\('e compil\('e\&.
.RE
.PP
Default\-Release
.RS 4
Indique la distribution \(`a utiliser par d\('efaut lors de l\'installation d\'un paquet si plusieurs versions sont disponibles\&. La valeur peut \(^etre un nom de distribution ou un num\('ero de version\&. Exemples\ \&: \(Fo\ \&stable\ \&\(Fc, \(Fo\ \&testing\ \&\(Fc, \(Fo\ \&4\&.0\ \&\(Fc, \(Fo\ \&5\&.0*\ \&\(Fc\&. Les noms de codes des distributions (\(Fo\ \&etch\ \&\(Fc, \(Fo\ \&lenny\ \&\(Fc, etc\&.) ne sont pas permis pour l\'instant\&. Voir aussi
\fBapt_preferences\fR(5)\&.
.RE
.PP
Ignore\-Hold
.RS 4
Ignore les paquets \(Fo\ \&gel\('es\ \&\(Fc\ \&; cette option globale indique au syst\(`eme de r\('esolution de ne pas tenir compte des paquets \(Fo\ \&gel\('es\ \&\(Fc dans sa prise de d\('ecision\&.
.RE
.PP
Clean\-Installed
.RS 4
Avec cette option qui est activ\('ee par d\('efaut, la fonctionnalit\('e \(Fo\ \&autoclean\ \&\(Fc supprime du cache tout paquet qui ne peut plus \(^etre r\('ecup\('er\('e\&. Quand cette option est d\('esactiv\('ee, les paquets qui sont install\('es localement sont aussi exclus du nettoyage \- mais notez que APT ne fournit aucun moyen direct pour les r\('einstaller\&.
.RE
.PP
Immediate\-Configure
.RS 4
D\('esactive la configuration imm\('ediate\ \&; cette dangereuse option d\('esactive une partie du code de mise en ordre de APT pour que ce dernier effectue le moins d\'appels possible \(`a
\fBdpkg\fR(8)\&. \(,Ca peut \(^etre n\('ecessaire sur des syst\(`emes \(`a un seul utilisateur extr\(^emement lents, mais cette option est tr\(`es dangereuse et peut faire \('echouer les scripts d\'installation, voire pire\&. Utilisez\-la \(`a vos risques et p\('erils\&.
.RE
.PP
Force\-LoopBreak
.RS 4
Ne jamais activer cette option \(`a moins que vous ne sachiez \- r\('eellement \- ce que vous faites\&. Elle autorise APT \(`a supprimer temporairement un paquet essentiel pour mettre fin \(`a une boucle Conflicts / Conflicts ou Conflicts / Pre\-Depends entre deux paquets essentiels\&. UNE TELLE BOUCLE NE DOIT JAMAIS SE PRODUIRE\ \&: C\'EST UN BOGUE S\('ERIEUX\&. Cette option fonctionne si les paquets essentiels ne sont pas tar, gzip, libc, dpkg, bash ou tous les paquets dont ces paquets d\('ependent\&.
.RE
.PP
Cache\-Limit
.RS 4
APT utilise un fichier de cache charg\('e en m\('emoire avec mmap pour ranger les informations sur les paquets disponibles\&. Cette option fixe la taille m\('emoire allou\('ee pour le chargement de ce cache\&.
.RE
.PP
Build\-Essential
.RS 4
Cette option d\('efinit les paquets qui sont consid\('er\('es comme faisant partie des d\('ependances essentielles pour la construction de paquets\&.
.RE
.PP
Get
.RS 4
La sous\-section
Get
contr\(^ole l\'outil
\fBapt-get\fR(8), veuillez consulter sa documentation pour avoir plus d\'informations sur les options en question\&.
.RE
.PP
Cache
.RS 4
La sous\-section
Cache
contr\(^ole l\'outil
\fBapt-cache\fR(8), veuillez consulter sa documentation pour avoir plus d\'informations sur les options en question\&.
.RE
.PP
CDROM
.RS 4
La sous\-section
CDROM
contr\(^ole l\'outil
\fBapt-cdrom\fR(8), veuillez consulter sa documentation pour avoir plus d\'informations sur les options en question\&.
.RE
.SH "LE GROUPE ACQUIRE"
.PP
Le groupe d\'options
Acquire
contr\(^ole le t\('el\('echargement des paquets et les gestionnaires d\'URI\&.
.PP
PDiffs
.RS 4
Essayer de t\('el\('echarger les fichiers diff\('erentiels appel\('es
PDiffs
pour les paquets ou les fichiers sources, plut\(^ot que de les t\('el\('echarger enti\(`erement\&. Par d\('efaut \(`a \(Fo\ \&true\ \&\(Fc\&.
.RE
.PP
Queue\-Mode
.RS 4
Le mode de file d\'attente\ \&;
Queue\-Mode
peut prendre les valeurs
host
ou
access
et cela d\('etermine comment APT parall\('elise les connexions sortantes\&.
Host
signifie qu\'une connexion par cible sera initi\('ee, tandis que
access
signifie qu\'une connexion par type d\'URI sera initi\('ee\&.
.RE
.PP
Retries
.RS 4
Nombre d\'essais \(`a effectuer\&. Si ce nombre n\'est pas nul, APT essaie de r\('ecup\('erer, le nombre donn\('e de fois, les fichiers dont la r\('ecup\('eration a \('echou\('e\&.
.RE
.PP
Source\-Symlinks
.RS 4
Utilise des liens symboliques pour les archives de sources\&. Positionn\('ee \(`a \(Fo\ \&true\ \&\(Fc, cette option cr\('ee si possible des liens symboliques vers les archives de sources au lieu de les copier\&. Par d\('efaut \(`a \(Fo\ \&true\ \&\(Fc\&.
.RE
.PP
http
.RS 4
URI HTTP\ \&; http::Proxy est le mandataire (proxy) HTTP \(`a utiliser par d\('efaut\&. Il se pr\('esente sous la forme standard\ \&:
http://[[user][:pass]@]host[:port]/\&. On peut sp\('ecifier un mandataire particulier par h\(^ote distant en utilisant la syntaxe\ \&:
http::Proxy::<h\(^ote>\&. Le mot\-cl\('e sp\('ecial
DIRECT
indique alors de n\'utiliser aucun mandataire pour l\'h\(^ote\&. Lorsqu\'elle est d\('efinie, la variable d\'environnement
\fBhttp_proxy\fR
annule et remplace toutes les options de mandataire HTTP\&.
.sp
Trois options de configuration sont fournies pour le contr\(^ole des caches compatibles avec HTTP/1\&.1\&.
No\-Cache
signifie que le mandataire ne doit jamais utiliser les r\('eponses qu\'il a stock\('ees\ \&;
Max\-Age
sert uniquement pour les fichiers d\'index\ \&: cela demande au cache de les mettre \(`a jour quand leur anciennet\('e est sup\('erieure au nombre de secondes donn\('e\&. Debian met \(`a jour ses fichiers d\'index de mani\(`ere quotidienne\ \&; la valeur par d\('efaut est donc de 1 jour\&.
No\-Store
sert uniquement pour les fichiers d\'archive\ \& et demande au cache de ne jamais garder la requ\(^ete\&. Cela peut \('eviter de polluer un cache mandataire avec des fichiers \&.deb tr\(`es grands\&. Note\ \&: Squid 2\&.0\&.2 ne prend en compte aucune de ces options\&.
.sp
L\'option
timeout
positionne le compteur de temps mort (timeout) utilis\('e par la m\('ethode\&. Cela vaut pour tout, connexion et donn\('ees\&.
.sp
Une option de configuration est fournie pour contr\(^oler la profondeur du tube pour le cas o\(`u un serveur distant n\'est pas conforme \(`a la RFC ou est bogu\('e (comme Squid 2\&.0\&.2)\&.
Acquire::http::Pipeline\-Depth
a une valeur comprise entre 0 et 5\ \&: elle indique le nombre de requ\(^etes en attente qui peuvent \(^etre \('emises\&. Quand la machine distante ne conserve pas correctement les connexions TCP, on DOIT donner une valeur \('egale \(`a 0 \-\- sinon des donn\('ees seront corrompues\&. Les machines qui ont besoin de cette option ne respectent pas la RFC 2068\&.
.RE
.PP
https
.RS 4
URI HTTPS\&. Les options de contr\(^ole de cache et de mandataire (proxy) sont les m\(^emes que pour la m\('ethode
http\&. L\'option
Pipeline\-Depth
n\'est pas encore support\('ee\&.
.sp
La sous\-option
CaInfo
sp\('ecifie le fichier contenant les informations sur les certificats de confiance\&. La sous\-option bool\('eenne
Verify\-Peer
pr\('ecise si le certificat d\'h\(^ote du serveur doit \(^etre confront\('e aux certificats de confiance ou pas\&. La sous\-option bool\('eenne
Verify\-Host
pr\('ecise s\'il faut v\('erifier ou pas le nom d\'h\(^ote du serveur\&.
SslCert
d\('etermine le certificat \(`a utiliser pour l\'authentification du client\&.
SslKey
d\('etermine quelle clef priv\('ee doit \(^etre utilis\('ee pour l\'authentification du client\&.
SslForceVersion
surcharge la valeur par d\('efaut pour la version de SSL \(`a utiliser et peut contenir l\'une des cha\(^ines \'TLSv1\' ou \'SSLv3\'\&.
.sp
Chacune de ces options peut \(^etre sp\('ecifi\('ee pour un h\(^ote particulier en utilisant
<h\(^ote>::CaInfo,
<h\(^ote>::Verify\-Peer,
<h\(^ote>::Verify\-Host,
<h\(^ote>::SslCert,
<h\(^ote>::SslKey
et
<h\(^ote>::SslForceVersion
respectivement\&.
.RE
.PP
ftp
.RS 4
URI FTP\ \&; ftp::Proxy est le mandataire (proxy) FTP \(`a utiliser par d\('efaut\&. Il se pr\('esente sous la forme standard\ \&:
ftp://[[user][:pass]@]host[:port]/\&. On peut sp\('ecifier un mandataire particulier par h\(^ote distant en utilisant la syntaxe\ \&:
ftp::Proxy::<h\(^ote>\&. Le mot\-cl\('e sp\('ecial
DIRECT
indique alors de n\'utiliser aucun mandataire pour l\'h\(^ote\&. Lorsqu\'elle est d\('efinie, la variable d\'environnement
\fBftp_proxy\fR
annule et replace toutes les options de mandataire FTP\&. Pour utiliser un mandataire FTP, vous devrez renseigner l\'entr\('ee
ftp::ProxyLogin
dans le fichier de configuration\&. Cette entr\('ee sp\('ecifie les commandes \(`a envoyer au mandataire pour lui pr\('eciser \(`a quoi il doit se connecter\&. Voyez
/usr/share/doc/apt/examples/configure\-index\&.gz
pour savoir comment faire\&. Les variables de substitution disponibles sont\ \&:
$(PROXY_USER),
$(PROXY_PASS),
$(SITE_USER),
$(SITE_PASS),
$(SITE)
et
$(SITE_PORT)\&. Chacune correspond \(`a l\'\('el\('ement respectif de l\'URI\&.
.sp
L\'option
timeout
positionne le compteur de temps mort (timeout) utilis\('e par la m\('ethode\&. Cela vaut pour tout, connexion et donn\('ees\&.
.sp
Plusieurs options de configuration sont fournies pour contr\(^oler le mode passif\&. Il est g\('en\('eralement plus s\(^ur d\'activer le mode passif et cela marche dans presque tous les environnements\&. Cependant, certaines situations n\('ecessitent que le mode passif soit d\('esactiv\('e et que le mode \(Fo\ \&port\ \&\(Fc de ftp soit utilis\('e \(`a la place\&. On peut le faire globalement, pour des connexions qui passent par un mandataire ou pour une machine sp\('ecifique (examinez le mod\(`ele de fichier de configuration)\&.
.sp
Il est possible de faire transiter le trafic FTP par un mandataire HTTP en positionnant la variable d\'environnement
\fBftp_proxy\fR
\(`a une URL HTTP \-\- consultez la m\('ethode http ci\-dessus pour la syntaxe\&. On ne peut pas le faire dans le fichier de configuration et il n\'est de toute fa\(,con pas recommand\('e d\'utiliser FTP au travers de HTTP en raison la faible efficacit\('e de cette m\('ethode\&.
.sp
L\'option
ForceExtended
contr\(^ole l\'utilisation des commandes li\('ees \(`a la RFC 2428,
EPSV
et
EPRT\&. Par d\('efaut, elle vaut \(Fo\ \&false\ \&\(Fc ce qui signifie que ces commandes ne sont utilis\('ees que pour une connexion de type IPv6\&. Quand elle vaut \(Fo\ \&true\ \&\(Fc, on les utilise m\(^eme si la connexion est de type IPv4\&. La plupart des serveurs FTP ne suivent pas la RFC 2428\&.
.RE
.PP
cdrom
.RS 4
URI c\('ed\('erom\ \&; la seule option de configuration pour les URI de c\('ed\('erom est le point de montage\ \&:
cdrom::Mount\ \&; il doit repr\('esenter le point de montage du lecteur de c\('ed\('erom indiqu\('e dans
/etc/fstab\&. On peut fournir d\'autres commandes de montage et de d\('emontage quand le point de montage ne peut \(^etre list\('e dans le fichier
/etc/fstab
(par exemple, un montage SMB)\&. Syntaxiquement, il faut placer
.sp
.if n \{\
.RS 4
.\}
.nf
"/cdrom/"::Mount "foo";
.fi
.if n \{\
.RE
.\}
.sp
dans le bloc cdrom\&. La barre oblique finale est importante\&. Les commandes de d\('emontage peuvent \(^etre sp\('ecifi\('ees en utilisant
UMount\&.
.RE
.PP
gpgv
.RS 4
URI GPGV\ \&; la seule option pour les URI GPGV est celle qui permet de passer des param\(`etres \(`a gpgv\&.
gpgv::Options\ \&: options suppl\('ementaires pass\('ees \(`a gpgv\&.
.RE
.SH "LES R\('EPERTOIRES"
.PP
Les r\('epertoires de la section
Dir::State
concernent le syst\(`eme local\&.
lists
est le r\('epertoire o\(`u placer les listes de paquets t\('el\('echarg\('es et
status
est le nom du fichier d\'\('etat de
\fBdpkg\fR(8)\&.
preferences
concerne APT\ \&: c\'est le nom du fichier des pr\('ef\('erences\&.
Dir::State
contient le r\('epertoire par d\('efaut pr\('efix\('e \(`a tous les sous\-\('el\('ements, quand ceux\-ci ne commencent pas par
/
ou
\&./\&.
.PP

Dir::Cache
contient les emplacements qui renseignent sur le cache local\ \&: par exemple, les deux caches de paquets
srcpkgcache
et
pkgcache, et aussi l\'endroit o\(`u sont plac\('ees les archives t\('el\('echarg\('ees,
Dir::Cache::archives\&. On peut emp\(^echer la cr\('eation des caches en saisissant un nom vide\&. Cela ralentit le d\('emarrage mais sauve de l\'espace disque\&. Il vaut mieux se passer du cache
pkgcache
plut\(^ot que se passer du cache
srcpkgcache\&. Comme pour
Dir::State, le r\('epertoire par d\('efaut est contenu dans
Dir::Cache\&.
.PP

Dir::Etc
contient l\'emplacement des fichiers de configuration,
sourcelist
indique l\'emplacement de la liste de sources et
main
est le fichier de configuration par d\('efaut (le modifier n\'a aucun effet, \(`a moins qu\'on ne le modifie avec le fichier de configuration indiqu\('e par la variable
\fBAPT_CONFIG\fR)\&.
.PP

Dir::Parts
lit, par ordre d\'entr\('ee, tous les fragments de configuration dans le r\('epertoire indiqu\('e\&. Ensuite, le fichier principal de configuration est charg\('e\&.
.PP
Les programmes binaires sont point\('es par
Dir::Bin\&. L\'emplacement des gestionnaires de m\('ethodes est indiqu\('e par
Dir::Bin::Methods\ \&;
gzip,
dpkg,
apt\-get,
dpkg\-source,
dpkg\-buildpackage
et
apt\-cache
indiquent l\'emplacement des programmes correspondants\&.
.PP
L\'option de configuration
RootDir
a une signification particuli\(`ere\&. Lorsqu\'elle est d\('efinie, tous les chemins d\('eclar\('es dans
Dir::
sont consid\('er\('es relativement \(`a
RootDir,
\fIm\(^eme les chemins sp\('ecifi\('es de mani\(`ere absolue\fR\&. Ainsi par exemple si
RootDir
est d\('efini comme
/tmp/staging, et que chemin du fichier d\'\('etat
Dir::State::status
est d\('eclar\('e comme
/var/lib/dpkg/status
alors ce fichier sera cherch\('e dans
/tmp/staging/var/lib/dpkg/status\&.
.SH "APT ET DSELECT"
.PP
Quand APT est utilis\('e comme une m\('ethode de
\fBdselect\fR(8), plusieurs directives contr\(^olent le comportement par d\('efaut\&. On les trouve dans la section
DSelect\&.
.PP
Clean
.RS 4
Mode de nettoyage du cache\ \&; cette variable peut prendre l\'une des valeurs suivantes\ \&: \(Fo\ \&always\ \&\(Fc, \(Fo\ \&prompt\ \&\(Fc, \(Fo\ \&auto\ \&\(Fc, \(Fo\ \&pre\-auto\ \&\(Fc et \(Fo\ \&never\ \&\(Fc\&. \(Fo\ \&always\ \&\(Fc et \(Fo\ \&prompt\ \&\(Fc suppriment tous les paquets du cache apr\(`es la mise \(`a niveau\ \&; \(Fo\ \&prompt\ \&\(Fc (valeur par d\('efaut) les supprime apr\(`es une demande et \(Fo\ \&auto\ \&\(Fc ne supprime que les archives qui ne peuvent plus \(^etre t\('el\('echarg\('ees (remplac\('ees, par exemple, par une nouvelle version)\&. \(Fo\ \&pre\-auto\ \&\(Fc les supprime avant de r\('ecup\('erer de nouveaux paquets\&.
.RE
.PP
Options
.RS 4
Le contenu de cette variable est pass\('e comme options de ligne de commande \(`a
\fBapt-get\fR(8)
lors de la phase d\'installation\&.
.RE
.PP
UpdateOptions
.RS 4
Le contenu de cette variable est pass\('e comme options de ligne de commande \(`a
\fBapt-get\fR(8)
lors de la phase de mise \(`a jour\&.
.RE
.PP
PromptAfterUpdate
.RS 4
Si cette option est \(Fo\ \&vraie\ \&\(Fc, l\'op\('eration [U]pdate de
\fBdselect\fR(8)
interroge toujours l\'utilisateur avant de continuer\&. Par d\('efaut, ce n\'est qu\'en cas d\'erreur que l\'on propose \(`a l\'utilisateur d\'intervenir\&.
.RE
.SH "COMMENT APT APPELLE DPKG(8)"
.PP
Plusieurs directives de configuration contr\(^olent la mani\(`ere dont APT invoque
\fBdpkg\fR(8)\ \&: elles figurent dans la section
DPkg\&.
.PP
Options
.RS 4
Il s\'agit d\'une liste d\'options \(`a passer \(`a
\fBdpkg\fR(8)\&. Les options doivent \(^etre d\('eclar\('ees en utilisant la notation de liste et chaque \('el\('ement de la liste est pass\('e comme un seul argument \(`a
\fBdpkg\fR(8)\&.
.RE
.PP
Pre\-Invoke, Post\-Invoke
.RS 4
Il s\'agit d\'une liste de commandes shell \(`a ex\('ecuter avant ou apr\(`es l\'appel de
\fBdpkg\fR(8)\&. Tout comme pour
Options, on doit utiliser la notation de liste\&. Les commandes sont appel\('ees dans l\'ordre, en utilisant
/bin/sh\ \&: APT s\'arr\(^ete d\(`es que l\'une d\'elles \('echoue\&.
.RE
.PP
Pre\-Install\-Pkgs
.RS 4
Il s\'agit d\'une liste de commandes shell \(`a ex\('ecuter avant d\'appeler
\fBdpkg\fR(8)\&. Tout comme pour
Options, on doit utiliser la notation de liste\&. Les commandes sont appel\('ees dans l\'ordre, en utilisant
/bin/sh\ \&: APT s\'arr\(^ete d\(`es que l\'une d\'elles \('echoue\&. Sur l\'entr\('ee standard, APT transmet aux commandes les noms de tous les fichiers \&.deb qu\'il va installer, \(`a raison d\'un par ligne\&.
.sp
La deuxi\(`eme version de ce protocole donne plus de renseignements\ \&: on obtient la version du protocole, la configuration de APT et les paquets, fichiers ou versions qui ont chang\('e\&. On autorise cette version en positionnant
DPkg::Tools::Options::cmd::Version
\(`a 2\&.
cmd
est une commande pass\('ee \(`a
Pre\-Install\-Pkgs\&.
.RE
.PP
Run\-Directory
.RS 4
APT se place dans ce r\('epertoire avant d\'appeler
\fBdpkg\fR(8)\ \&; par d\('efaut c\'est le r\('epertoire
/\&.
.RE
.PP
Build\-Options
.RS 4
Ces options sont pass\('ees \(`a
\fBdpkg-buildpackage\fR(1)
lors de la compilation des paquets\ \&; par d\('efaut la signature est d\('esactiv\('ee et tous les binaires sont cr\('e\('es\&.
.RE
.SH "OPTIONS \(Fo\ \&PERIODIC\ \&\(Fc ET \(Fo\ \&ARCHIVE\ \&\(Fc"
.PP
Les groupes d\'options
APT::Periodic
et
APT::Archive
configurent les comportements p\('eriodiques r\('ealis\('es par le script
/etc/cron\&.daily/apt, lanc\('e quotidiennement\&.
.PP
APT::Periodic
.RS 4
.PP
Les options de cette section permettent de configurer la fr\('equence d\'ex\('ecution des t\(^aches APT lanc\('ees automatiquement\&. Ces param\(`etre prennent comme valeurs des p\('eriodicit\('es d\'ex\('ecution en nombre de jours\&.

Update\-Package\-List\ \&: p\('eriodicit\('e de mise \(`a jour de la liste des paquets disponibles\&. (0 = d\('esactiv\('e)

Download\-Upgradable\-Packages\ \&: p\('eriodicit\('e de t\('el\('echargement dans le cache des paquets pour lesquels une mise \(`a jour est disponible\&. (0 = d\('esactiv\('e)

AutocleanInterval\ \&: p\('eriodicit\('e des \(Fo\ \&autoclean\ \&\(Fc, c\'est \(`a dire de la suppression du cache des paquets qui ne peuvent plus \(^etre t\('el\('echarg\('es\&. (0 = d\('esactiv\('e)

Unattended\-Upgrade\ \&: p\('eriodicit\('e de mise \(`a jour automatique du syst\(`eme sans intervention humaine\&. Le paquet
unattended\-upgrades
doit \(^etre install\('e pour que cette t\(^ache s\'ex\('ecute\&. Le cas \('ech\('eant un fichier journal est \('ecrit dans
/var/log/unattended\-upgrades\&. (0 = d\('esactiv\('e)
.RE
.PP
APT::Archive
.RS 4
.PP
Les options de la section APT::Archive permettent de contr\(^oler la taille du cache de paquets\&.

MaxAge\ \&: anciennet\('e maximale d\'un paquet dans le cache, en nombre de jours\&. Les paquets plus anciens sont supprim\('es\&. (0 = d\('esactiv\('e)

MaxSize\ \&: taille maximale du cache en Mo\&. (0 = d\('esactive) Si ce maximum est d\('epass\('e, des paquets sont supprim\('es jusqu\'\(`a ce que la taille du cache repasse sous la limite\&. Les paquets les plus volumineux sont supprim\('es en premier\&.

MinAge\ \&: age minimum d\'un paquet du cache, en nombre de jours (0 = d\('esactiv\('e)\&. Un paquet plus r\('ecent ne sera pas supprim\('e\&. Cette option est utile pour garder \(`a disposition une version des paquets en cas de probl\(`eme grave\&.
.RE
.SH "LES OPTIONS DE D\('EBOGAGE"
.PP
Les options de la section
Debug::
servent soit \(`a provoquer l\'affichage d\'informations de d\('ebogage sur la sortie d\'erreur standard du programme qui utilise les librairies APT, soit \(`a activer des modes de fonctionnement sp\('eciaux qui sont principalement utiles pour d\('eboguer le comportement de
APT\&. La plupart de ces options n\'ont pas d\'int\('er\(^et pour un utilisateur normal, mais certaines peuvent tout de m\(^eme \(^etre utiles\ \&:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Debug::pkgProblemResolver
affiche d\'int\('eressantes informations sur les d\('ecisions prises par les commandes
dist\-upgrade, upgrade, install, remove et purge\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Debug::NoLocking
d\('esactive le verrouillage de fichier de mani\(`ere \(`a ce que APT puisse effectuer quelques op\('erations (telles que
apt\-get \-s install) sans \(^etre \(Fo\ \&root\ \&\(Fc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Debug::pkgDPkgPM
affiche la ligne de commande \(`a chaque appel de
\fBdpkg\fR(8)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

Debug::IdentCdrom
d\('esactive l\'inclusion de donn\('ees de type statfs dans les ID de c\('ed\('erom\&.
.RE
.PP
Voici une liste compl\(`ete des options de d\('ebogage de APT\&.
.PP
Debug::Acquire::cdrom
.RS 4
Affiche les informations concernant les sources de type cdrom://
.RE
.PP
Debug::Acquire::ftp
.RS 4
Affiche les informations concernant le t\('el\('echargement de paquets par FTP\&.
.RE
.PP
Debug::Acquire::http
.RS 4
Affiche les informations concernant le t\('el\('echargement de paquets par HTTP\&.
.RE
.PP
Debug::Acquire::https
.RS 4
Affiche les informations concernant le t\('el\('echargement de paquets par HTTPS\&.
.RE
.PP
Debug::Acquire::gpgv
.RS 4
Affiche les informations relatives \(`a la v\('erification de signatures cryptographiques avec
gpg\&.
.RE
.PP
Debug::aptcdrom
.RS 4
Affiche des informations concernant l\'acc\(`es aux collections de paquets stock\('ees sur c\('ed\('erom\&.
.RE
.PP
Debug::BuildDeps
.RS 4
D\('ecrit le processus de r\('esolution des d\('ependances pour la construction de paquets source (\ \&\(Fo\ \&build\-dependencies\ \&\(Fc\ \&) par
\fBapt-get\fR(8)\&.
.RE
.PP
Debug::Hashes
.RS 4
Affiche toutes les clefs de hachage cryptographiques g\('en\('er\('ees par les librairies APT\&.
.RE
.PP
Debug::IdentCdrom
.RS 4
D\('esactive l\'inclusion des donn\('ees de type
statfs
pour la g\('en\('eration des ID de c\('ed\('erom, \(`a savoir le nombre de blocs libres et utilis\('es sur le syst\(`eme de fichier du c\('ed\('erom\&.
.RE
.PP
Debug::NoLocking
.RS 4
D\('esactive le verrouillage de fichiers\&. Cela permet par exemple de lancer deux instances de \(Fo\ \&apt\-get update\ \&\(Fc en m\(^eme temps\&.
.RE
.PP
Debug::pkgAcquire
.RS 4
Trace les ajouts et suppressions d\'\('el\('ements de la queue globale de t\('el\('echargement\&.
.RE
.PP
Debug::pkgAcquire::Auth
.RS 4
Affiche les d\('etails de la v\('erification des sommes de contr\(^ole et des signatures cryptographiques des fichiers t\('el\('echarg\('es, ainsi que les erreurs \('eventuelles\&.
.RE
.PP
Debug::pkgAcquire::Diffs
.RS 4
Affiche les informations de t\('el\('echargement et de prise en compte des fichiers diff\('erentiels des indexes de paquets, ainsi que les erreurs \('eventuelles\&.
.RE
.PP
Debug::pkgAcquire::RRed
.RS 4
Affiche les d\('etails de la v\('erification des sommes de contr\(^ole et des signatures cryptographiques des fichiers t\('el\('echarg\('es, ainsi que les erreurs \('eventuelles\&.
.RE
.PP
Debug::pkgAcquire::Worker
.RS 4
Affiche toutes les interactions avec les processus enfants qui se chargent effectivement des t\('el\('echargements\&.
.RE
.PP
Debug::pkgAcquire::pkgAutoRemove
.RS 4
Affiche les changements concernant le marquage des paquets comme install\('es automatiquement, et la suppression des paquets inutiles\&.
.RE
.PP
Debug::pkgDepCache::AutoInstall
.RS 4
G\('en\(`ere les informations de d\('ebogage d\('ecrivant quels paquets sont install\('es automatiquement pour satisfaire les d\('ependances\&. Cela concerne la passe initiale d\'installation automatique effectu\('ee par exemple par
apt\-get install
et pas le syst\(`eme de r\('esolution de d\('ependances complet de APT\ \&; voir
Debug::pkgProblemResolver
pour ce dernier\&.
.RE
.PP
Debug::pkgInitConfig
.RS 4
Au lancement, affiche l\'ensemble de la configuration sur la sortie d\'erreur standard\&.
.RE
.PP
Debug::pkgDPkgPM
.RS 4
Affiche la commande exacte d\'invocation de
\fBdpkg\fR(8)
\(`a chaque appel\ \&; les arguments sont s\('epar\('es par des espaces\&.
.RE
.PP
Debug::pkgDPkgProgressReporting
.RS 4
Affiche l\'ensemble des informations re\(,cues de
\fBdpkg\fR(8)
par l\'interm\('ediaire du descripteur de fichier d\'\('etat, et les \('eventuelles erreurs d\'analyse de ce fichier\&.
.RE
.PP
Debug::pkgOrderList
.RS 4
Affiche les \('etapes de l\'algorithme utilis\('e pour choisir l\'ordre dans lequel APT passe les paquets \(`a
\fBdpkg\fR(8)\&.
.RE
.PP
Debug::pkgPackageManager
.RS 4
Affiche le d\('etail des op\('erations li\('ees \(`a l\'invocation de
\fBdpkg\fR(8)\&.
.RE
.PP
Debug::pkgPolicy
.RS 4
Au lancement, affiche la priorit\('e de chaque liste de paquets\&.
.RE
.PP
Debug::pkgProblemResolver
.RS 4
Affiche la trace d\'ex\('ecution du syst\(`eme de r\('esolution de d\('ependances (ne concerne que les cas o\(`u un probl\(`eme de d\('ependances complexe se pr\('esente)\&.
.RE
.PP
Debug::sourceList
.RS 4
Affiche les fournisseurs d\('eclar\('es dans le fichier
/etc/apt/vendors\&.list\&.
.RE
.SH "EXEMPLES"
.PP
Le fichier
/usr/share/doc/apt/examples/configure\-index\&.gz
contient un mod\(`ele de fichier montrant des exemples pour toutes les options existantes\&.
.SH "FICHIERS"
.PP

/etc/apt/apt\&.conf
.SH "VOIR AUSSI"
.PP

\fBapt-cache\fR(8),
\fBapt-config\fR(8),
\fBapt_preferences\fR(5)\&.
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTION"
.PP
J\('er\(^ome Marant\&. 2000\ \&; mise \(`a jour : Philippe Batailler\&. 2005\&.
debian\-l10n\-french@lists\&.debian\&.org\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.PP
\fBAPT team\fR
.RS 4
Auteur.
.RE
.SH "NOTES"
.IP " 1." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
