'\" t
.\"     Title: apt_preferences
.\"    Author: APT team
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 29 F\('evrier 2004
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "APT_PREFERENCES" "5" "29 F\('evrier 2004" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt_preferences \- Un fichier de contr\(^ole des pr\('ef\('erences pour APT
.SH "DESCRIPTION"
.PP
Le fichier d\'APT,
/etc/apt/preferences, peut \(^etre utilis\('e pour choisir la version des paquets que l\'on veut installer\&.
.PP
Quand le fichier
\fBsources.list\fR(5)contient des r\('ef\('erences \(`a plusieurs distributions (par exemple,
stable
et
testing), plusieurs versions d\'un paquet peuvent \(^etre install\('ees\&. APT affecte une priorit\('e \(`a chaque version disponible\&. La commande
\fBapt\-get\fR, tenant compte des contraintes de d\('ependance, installe la version qui poss\(`ede la priorit\('e la plus haute\&. Le fichier des pr\('ef\('erences annule les priorit\('es assign\('ees par d\('efaut aux versions des paquets\ \&: ainsi l\'utilisateur peut choisir la version qu\'il veut installer\&.
.PP
Si le fichier
\fBsources.list\fR(5)contient, pour une m\(^eme distribution, des r\('ef\('erences \(`a plusieurs sites de t\('el\('echargement, il peut exister plusieurs exemplaires de la m\(^eme version d\'un paquet\&. Dans ce cas,
\fBapt\-get\fR
t\('el\('echarge l\'exemplaire qui appara\(^it en premier dans le fichier
\fBsources.list\fR(5)\&. Le fichier des pr\('ef\('erences n\'influe pas sur le choix des exemplaires, seulement sur le choix de la version\&.
.SS "Les priorit\('es affect\('ees par d\('efaut"
.PP
Quand le fichier des pr\('ef\('erences n\'existe pas, ou quand aucune entr\('ee de ce fichier ne s\'applique \(`a une version pr\('ecise, la priorit\('e affect\('ee \(`a cette version est la priorit\('e de la distribution \(`a laquelle elle appartient\&. On peut distinguer une distribution et lui donner une priorit\('e plus haute que celle des autres distributions\ \&: on l\'appelle la distribution par d\('efaut ou \(Fo\ \&target release\ \&\(Fc et elle peut \(^etre d\('efinie sur la ligne de commande de
\fBapt\-get\fR
ou dans le fichier de configuration d\'APT,
/etc/apt/apt\&.conf\&. Par exemple\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
\fBapt\-get install \-t testing \fR\fB\fIpaquet\fR\fR
.fi
.if n \{\
.RE
.\}
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
APT::Default\-Release "stable";
.fi
.if n \{\
.RE
.\}
.PP
Quand une distribution par d\('efaut a \('et\('e indiqu\('ee, APT utilise l\'algorithme suivant pour d\('eterminer la priorit\('e des versions d\'un paquet\ \&:
.PP
une priorit\('e \('egale \(`a 100
.RS 4
est affect\('ee \(`a la version d\('ej\(`a install\('ee (si elle existe)\&.
.RE
.PP
une priorit\('e \('egale \(`a 500
.RS 4
est affect\('ee aux versions qui ne sont pas install\('ees et qui n\'appartiennent pas \(`a la distribution par d\('efaut\&.
.RE
.PP
une priorit\('e \('egale \(`a 990
.RS 4
est affect\('ee aux versions qui ne sont pas install\('ees et qui appartiennent \(`a la distribution par d\('efaut\&.
.RE
.PP
Quand aucune distribution par d\('efaut n\'a \('et\('e indiqu\('ee, APT affecte simplement une priorit\('e \('egale \(`a 100 \(`a toute version install\('ee d\'un paquet et une priorit\('e \('egale \(`a 500 \(`a tout version non install\('ee\&.
.PP
Puis APT applique les r\(`egles suivantes pour d\('eterminer la version du paquet qu\'il faut installer (elles sont list\('ees par ordre de priorit\('e)\ \&:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Ne jamais revenir en arri\(`ere, sauf si la priorit\('e d\'une version disponible d\('epasse 1000\&. \(Fo\ \&Revenir en arri\(`ere\ \&\(Fc signifie installer une version moins r\('ecente que la version install\('ee\&. Il faut noter qu\'aucune des priorit\('es par d\('efaut n\'exc\(`ede 1000\ \&; de telles valeurs ne peuvent \(^etre d\('efinies que dans le fichier des pr\('ef\('erences\&. Notez aussi qu\'il est risqu\('e de revenir en arri\(`ere\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Installer la version qui poss\(`ede la priorit\('e la plus haute\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Quand deux (ou plus) versions ont la m\(^eme priorit\('e, installer la version la plus r\('ecente (c\&.\-\(`a\-d\&. celle dont le num\('ero de version est le plus grand)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Quand deux (ou plus) versions ont la m\(^eme priorit\('e et le m\(^eme num\('ero de version, mais soit les paquets diff\(`erent par certaines m\('etadonn\('ees, soit l\'option
\-\-reinstall
a \('et\('e donn\('ee, installer la version qui n\'est pas install\('ee\&.
.RE
.sp
.RE
.PP
En g\('en\('eral, la version install\('ee d\'un paquet (priorit\('e 100) n\'est pas aussi r\('ecente que les versions disponibles dans les sources list\('ees dans le fichier
\fBsources.list\fR(5)(priorit\('e 500 ou 990)\&. Et donc le paquet sera mis \(`a niveau avec la commande\ \&:
\fBapt\-get install \fR\fB\fIpaquet\fR\fR
ou
\fBapt\-get dist\-upgrade\fR\&.
.PP
La version install\('ee d\'un paquet peut \(^etre \- rarement \-
\fIplus\fR
r\('ecente que tout autre version disponible\&. Les commandes
\fBapt\-get install \fR\fB\fIpaquet\fR\fR
ou
\fBapt\-get upgrade\fR
ne provoquent pas de retour en arri\(`ere\&.
.PP
Parfois, la version install\('ee d\'un paquet est plus r\('ecente que la version appartenant \(`a la distribution par d\('efaut, mais moins r\('ecente que la version appartenant \(`a une autre distribution\&. Une telle version sera mise \(`a niveau par les commandes
\fBapt\-get install \fR\fB\fIpaquet\fR\fR
ou
\fBapt\-get upgrade\fR
car au moins
\fIl\'une\fR
des versions disponibles poss\(`ede une plus haute priorit\('e que celle de la version install\('ee\&.
.SS "Cons\('equences des pr\('ef\('erences"
.PP
Le fichier des pr\('ef\('erences permet \(`a l\'administrateur syst\(`eme de contr\(^oler l\'affectation des priorit\('es\&. Ce fichier est constitu\('e d\'une ou plusieurs entr\('ees s\('epar\('ees par des lignes blanches\&. Ces entr\('ees peuvent avoir deux formes, une forme particuli\(`ere et une forme g\('en\('erale\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
La forme particuli\(`ere affecte une priorit\('e (\fIPin\-Priority\fR) \(`a un paquet pr\('ecis, \(`a une version pr\('ecise ou \(`a un intervalle sp\('ecifiant plusieurs versions\&. Par exemple, l\'entr\('ee suivante affecte une priorit\('e haute \(`a toutes les versions du paquet
perl
dont le num\('ero de version commence par
5\&.8\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: perl
Pin: version 5\&.8*
Pin\-Priority: 1001
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
La forme g\('en\('erale affecte une priorit\('e \(`a toutes les versions d\'un paquet dans une distribution donn\('ee (c\'est\-\(`a\-dire, \(`a toutes les versions d\'un paquet qui sont list\('ees dans un fichier
Release), ou \(`a toutes les versions d\'un paquet provenant d\'un site internet identifi\('e par un nom compl\(`etement qualifi\('e\&.
.sp
Cette forme g\('en\('erale des entr\('ees du fichier des pr\('ef\('erences s\'applique seulement aux groupes de paquets\&. Par exemple, l\'entr\('ee suivante affecte une priorit\('e haute \(`a toutes les versions disponibles dans le site local\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: origin ""
Pin\-Priority: 999
.fi
.if n \{\
.RE
.\}
.sp
Attention ! le mot\-cl\('e utilis\('e ici,
origin, ne doit pas \(^etre confondu avec l\'Origine d\'une distribution indiqu\('ee dans un fichier
Release\&. Ce qui suit l\'\('etiquette \(Fo\ \&Origin:\ \&\(Fc dans un fichier
Release
n\'est pas une adresse internet mais le nom d\'un auteur ou d\'un distributeur, comme Debian ou Ximian\&.
.sp
L\'entr\('ee suivante affecte une priorit\('e basse \(`a toutes les versions d\'un paquet appartenant \(`a toute distribution dont le nom d\'\(Fo\ \&Archive\ \&\(Fc est
unstable\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=unstable
Pin\-Priority: 50
.fi
.if n \{\
.RE
.\}
.sp
L\'entr\('ee suivante affecte une priorit\('e haute \(`a toutes les versions d\'un paquet appartenant \(`a toute distribution dont le nom d\'\(Fo\ \&Archive\ \&\(Fc est
stable
et dont le num\('ero de \(Fo\ \&Version\ \&\(Fc est
3\&.0\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=stable, v=3\&.0
Pin\-Priority: 500
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RE
.SS "Comment APT interpr\(`ete\-t\-il les priorit\('es\ \&?"
.PP
Les priorit\('es (P) indiqu\('ees dans le fichier des pr\('ef\('erences doivent \(^etre des entiers positifs ou n\('egatifs\&. Ils sont interpr\('et\('es \(`a peu pr\(`es comme suit\ \&:
.PP
P > 1000
.RS 4
Cette priorit\('e entra\(^ine l\'installation du paquet m\(^eme s\'il s\'agit d\'un retour en arri\(`ere\&.
.RE
.PP
990 < P <=1000
.RS 4
La version sera install\('ee, m\(^eme si elle n\'appartient pas \(`a la distribution par d\('efaut\ \&; mais elle ne sera pas install\('ee si la version install\('ee est plus r\('ecente\&.
.RE
.PP
500 < P <=990
.RS 4
La version sera install\('ee, sauf s\'il existe une version appartenant \(`a la distribution par d\('efaut ou si la version install\('ee est plus r\('ecente\&.
.RE
.PP
100 < P <=500
.RS 4
La version sera install\('ee, sauf s\'il existe une version appartenant \(`a une autre distribution ou si la version install\('ee est plus r\('ecente\&.
.RE
.PP
0 < P <=100
.RS 4
La version sera install\('ee si aucune version du paquet n\'est install\('ee\&.
.RE
.PP
P < 0
.RS 4
Cette priorit\('e emp\(^eche l\'installation de la version\&.
.RE
.PP
Si l\'une des entr\('ees de forme particuli\(`ere correspond \(`a la version disponible d\'un paquet, la premi\(`ere entr\('ee trouv\('ee d\('etermine la priorit\('e de cette version\&. S\'il n\'en existe pas, et si l\'une des entr\('ees de forme g\('en\('erale correspond \(`a la version disponible d\'un paquet, la premi\(`ere entr\('ee trouv\('ee d\('etermine la priorit\('e\&.
.PP
Supposons par exemple que le fichier des pr\('ef\('erences contienne les trois entr\('ees d\('ecrites ci\-dessous\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Package: perl
Pin: version 5\&.8*
Pin\-Priority: 1001

Package: *
Pin: origin ""
Pin\-Priority: 999

Package: *
Pin: release unstable
Pin\-Priority: 50
.fi
.if n \{\
.RE
.\}
.PP
Alors\ \&:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
La version la plus r\('ecente du paquet
perl
sera install\('e pour autant que son num\('ero de version commence par
5\&.8\&. Si l\'\fIune\fR
des versions 5\&.8* existe et si la version install\('ee est une version 5\&.9*, il y aura un retour en arri\(`ere\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Les versions des paquets (autres que
perl) disponibles dans le site local ont priorit\('e sur les autres versions, m\(^eme celles appartenant \(`a la distribution par d\('efaut\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
La version d\'un paquet dont l\'origine n\'est pas le site local mais un site internet list\('e dans
\fBsources.list\fR(5)et qui appartient \(`a une distribution
unstable, ne sera install\('ee que si aucune version du paquet n\'est d\('ej\(`a install\('ee\&.
.RE
.sp
.RE
.SS "D\('etermination de la version des paquets et des propri\('et\('es des distributions"
.PP
Chaque source list\('ee dans le fichier
\fBsources.list\fR(5)doit fournir les fichiers
Packages
et
Release
qui d\('ecrivent les paquets disponibles \(`a cet endroit\&.
.PP
Le fichier
Packages
se trouve normalement dans le r\('epertoire
\&.\&.\&./dists/\fIdist\-name\fR/\fIcomponent\fR/\fIarch\fR, par exemple,
\&.\&.\&./dists/stable/main/binary\-i386/Packages\&. Il consiste en entr\('ees compos\('ees de lignes, une pour chaque paquet disponible dans le r\('epertoire\&. Seules deux lignes des entr\('ees sont pertinentes pour la d\('etermination des priorit\('es\ \&:
.PP
La ligne Package:
.RS 4
donne le nom du paquet
.RE
.PP
La ligne Version:
.RS 4
donne le num\('ero de version du paquet
.RE
.PP
Le fichier
Release
se trouve normalement dans le r\('epertoire
\&.\&.\&./dists/\fIdist\-name\fR, par exemple,
\&.\&.\&./dists/stable/Release, ou
\&.\&.\&./dists/woody/Release\&. Il consiste en une seule entr\('ee compos\('ee de plusieurs lignes qui s\'applique \(`a
\fItous\fR
les paquets situ\('es dans les r\('epertoires sous le r\('epertoire parent\&. Contrairement au fichier
Packages, presque toutes les lignes du fichier
Release
sont pertinentes pour d\('eterminer les priorit\('es\ \&:
.PP
La ligne Archive:
.RS 4
nomme l\'archive \(`a laquelle appartiennent tous les paquets situ\('es dans les r\('epertoires\&. Par exemple, la ligne
Archive: stable
indique que tous les paquets dans les r\('epertoires situ\('es sous le r\('epertoire parent du fichier
Release
appartiennent \(`a l\'archive
stable\&. Indiquer cette valeur dans le fichier des pr\('ef\('erences demanderait cette ligne\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release a=stable
.fi
.if n \{\
.RE
.\}
.RE
.PP
La ligne Version:
.RS 4
indique la version de la distribution\&. Par exemple, les paquets dans les r\('epertoires peuvent appartenir \(`a la distribution Debian GNU/Linux version 3\&.0\&. Il n\'y a pas de num\('ero de version pour les distributions
testing
et
unstable
car elles n\'ont pas encore \('et\('e publi\('ees\&. Indiquer cette valeur dans le fichier des pr\('ef\('erences demanderait ces lignes\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release v=3\&.0
Pin: release a=stable, v=3\&.0
Pin: release 3\&.0
.fi
.if n \{\
.RE
.\}
.RE
.PP
La ligne Component:
.RS 4
nomme un composant qui indique le type de licence associ\('ee aux paquets situ\('es dans les r\('epertoires sous le fichier
Release\&. Par exemple, la ligne
Component: main
indique que tous les exemplaires dans les r\('epertoires appartiennent au composant
main, c\'est\-\(`a\-dire que leur licence est en accord avec les Directives Debian pour le logiciel libre\&. Indiquer ce composant dans le fichier des pr\('ef\('erences demanderait cette ligne\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release c=main
.fi
.if n \{\
.RE
.\}
.RE
.PP
La ligne Origin:
.RS 4
nomme l\'origine des paquets situ\('es dans les r\('epertoires sous le fichier
Release\&. En g\('en\('eral, c\'est
Debian\&. Indiquer cette origine dans le fichier des pr\('ef\('erences demanderait cette ligne\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release o=Debian
.fi
.if n \{\
.RE
.\}
.RE
.PP
La ligne Label:
.RS 4
indique un label pour les paquets qui se trouvent dans les r\('epertoires sous le fichier
Release\&. En g\('en\('eral, c\'est
Debian\&. Indiquer cette origine dans le fichier des pr\('ef\('erences demanderait cette ligne\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release l=Debian
.fi
.if n \{\
.RE
.\}
.RE
.PP
Tous les fichiers
Packages
et
Release
r\('ecup\('er\('es dans des sources list\('ees par le fichier
\fBsources.list\fR(5)sont conserv\('es dans le r\('epertoire
/var/lib/apt/lists
ou dans le fichier sp\('ecifi\('e par la variable
Dir::State::Lists
dans le fichier
apt\&.conf\&. Par exemple, le fichier
debian\&.lcs\&.mit\&.edu_debian_dists_unstable_contrib_binary\-i386_Release
contient le fichier
Release
du site
debian\&.lcs\&.mit\&.edu, architecture
binary\-i386
et composant
contrib
de la distribution
unstable\&.
.SS "Lignes facultatives dans le fichier des pr\('ef\('erences"
.PP
Toute entr\('ee du fichier des pr\('ef\('erences peut commencer par une ou plusieurs lignes contenant le mot
Explanation:\&. Cela permet des commentaires\&.
.PP
La ligne
Pin\-Priority:
d\'une entr\('ee est facultative\&. Si elle n\'existe pas, APT affecte une priorit\('e inf\('erieure de 1 \(`a la valeur sp\('ecifi\('ee sur une ligne commen\(,cant par
Pin\-Priority: release \&.\&.\&.\&.
.SH "EXEMPLES"
.SS "Comment suivre Stable\ \&?"
.PP
Le fichier des pr\('ef\('erences suivant affecte une priorit\('e plus haute que la priorit\('e par d\('efaut (500) \(`a tous les exemplaires appartenant \(`a la distribution
stable
et une priorit\('e prohibitivement basse \(`a tous les exemplaires appartenant \(`a d\'autres distributions
Debian\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Explanation: Ne pas installer des exemplaires d\'origine Debian
Explanation: sauf ceux de la distribution stable
Package: *
Pin: release a=stable
Pin\-Priority: 900

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
Avec le fichier des pr\('ef\('erences ci\-dessus et un fichier
\fBsources.list\fR(5)ad\('equat, les commandes suivantes utiliseront les versions les plus r\('ecentes de
stable
pour faire la mise \(`a niveau\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpaquet\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
La commande suivante utilisera la version la plus r\('ecente de la distribution
testing
pour mettre \(`a niveau le paquet sp\('ecifi\('e\ \&; cependant les mises \(`a niveau ult\('erieures du paquet ne se feront pas \(`a moins de relancer la commande\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpaquet\fR/testing
.fi
.if n \{\
.RE
.\}
.sp
.SS "Comment suivre Testing ou Unstable\ \&?"
.PP
Le fichier des pr\('ef\('erences suivant affecte une priorit\('e haute aux versions des paquets appartenant \(`a la distribution
testing, une priorit\('e moindre aux versions appartenant \(`a la distribution
unstable
et une priorit\('e prohibitivement basse aux versions appartenant \(`a d\'autres distributions
Debian\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=testing
Pin\-Priority: 900

Package: *
Pin: release a=unstable
Pin\-Priority: 800

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
Avec un fichier
\fBsources.list\fR(5)appropri\('e et le fichier des pr\('ef\('erences ci\-dessus, les commandes suivantes utiliseront les versions les plus r\('ecentes de
testing
pour faire la mise \(`a niveau\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpaquet\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
La commande suivante utilisera la version la plus r\('ecente de la distribution
unstable
pour mettre \(`a niveau le paquet sp\('ecifi\('e\ \&; Par la suite,
\fBapt\-get upgrade\fR
mettra le paquet \(`a jour avec la plus r\('ecente version dans
testing
si elle est plus r\('ecente que la version install\('ee ou avec la plus r\('ecente version dans
unstable
si elle est plus r\('ecente que la version install\('ee\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpaquet\fR/unstable
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP

\fBapt-get\fR(8)
\fBapt-cache\fR(8)
\fBapt.conf\fR(5)
\fBsources.list\fR(5)
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTION"
.PP
Philippe Batailler\&.
debian\-l10n\-french@lists\&.debian\&.org\&. 2005\&.
.SH "AUTEUR"
.PP
\fBAPT team\fR
.RS 4
Auteur.
.RE
.SH "NOTES"
.IP " 1." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
