'\" t
.\"     Title: sources.list
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 29 February 2004
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: French
.\"
.TH "SOURCES\&.LIST" "5" "29 February 2004" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
sources.list \- Liste des sources de paquets
.SH "DESCRIPTION"
.PP
La liste des sources de paquets indique o\(`u trouver les archives du syst\(`eme de distribution de paquets utilis\('e\&. Pour l\'instant, cette page de manuel ne documente que le syst\(`eme d\'empaquetage utilis\('e par le syst\(`eme Debian GNU/Linux\&. Ce fichier de contr\(^ole est
/etc/apt/sources\&.list\&.
.PP
La liste des sources est con\(,cue pour prendre en compte un nombre quelconque de sources actives et diff\('erents m\('edia\&. Le fichier pr\('esente une source par ligne et la source pr\('ef\('er\('ee appara\(^it en premier\&. Le format de chaque ligne est\ \&:
type uri args\&. Le premier \('el\('ement,
type, d\('etermine le format des
args\&.
uri
est un identificateur universel de ressources (URI), qui est un sur\-ensemble du plus sp\('ecifique et bien connu rep\(`ere universel de ressources, ou URL\&. La fin de la ligne peut \(^etre un commentaire commen\(,cant par un caract\(`ere #\&.
.SH "SOURCES.LIST.D"
.PP
Le r\('epertoire
/etc/apt/sources\&.list\&.d
permet de lister des sources de paquets dans des fichiers distincts qui se terminent par
\&.list\&. Leur format est le m\(^eme que celui du fichier
sources\&.list\&.
.SH "LES TYPES DEB ET DEB-SRC."
.PP
Le type
deb
d\('ecrit une archive Debian classique \(`a deux niveaux,
distribution/composant\&.
distribution
peut prendre l\'une des valeurs suivantes\ \&:
stable,
unstable, ou
testing, et composant\ \&:
main,
contrib,
non\-free, ou
non\-us\&. Le type
deb\-src
d\('ecrit le code source pour une distribution Debian dans le m\(^eme format que le type
deb\&. Une ligne
deb\-src
est n\('ecessaire pour r\('ecup\('erer les index des sources\&.
.PP
Le format d\'une entr\('ee dans
sources\&.list
utilisant les types
deb
et
deb\-src
est de la forme\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
deb uri distribution [composant1] [composant2] [\&.\&.\&.]
.fi
.if n \{\
.RE
.\}
.PP
L\'URI de type
deb
doit indiquer la base de la distribution Debian dans laquelle APT trouvera les informations dont il a besoin\&.
distribution
peut sp\('ecifier le chemin exact\ \&: dans ce cas, on doit omettre les composants et
distribution
doit se terminer par une barre oblique (/)\&. C\'est utile quand seule une sous\-section particuli\(`ere de l\'archive d\('ecrite par cet URI est int\('eressante\&. Quand
distribution
n\'indique pas un chemin exact, un
composant
au moins doit \(^etre pr\('esent\&.
.PP

distribution
peut aussi contenir une variable
$(ARCH), qui sera remplac\('ee par l\'architecture Debian (i386, m68k, powerpc, \&.\&.\&.) sur laquelle s\'ex\('ecute le syst\(`eme\&. On peut ainsi utiliser un fichier
sources\&.list
qui ne d\('epend pas d\'une architecture\&. En g\('en\('eral, ce n\'est int\('eressant que si l\'on indique un chemin exact\ \&; sinon
APT
cr\('ee automatiquement un URI en fonction de l\'architecture effective\&.
.PP
Puisqu\'on ne peut indiquer qu\'une seule distribution par ligne, il peut \(^etre n\('ecessaire de disposer le m\(^eme URI sur plusieurs lignes quand on veut acc\('eder \(`a un sous\-ensemble des distributions ou composants disponibles \(`a cette adresse\&. APT trie les URI apr\(`es avoir cr\('ee pour lui\-m\(^eme la liste compl\(`ete\ \&; il regroupe les r\('ef\('erences multiples au m\(^eme h\(^ote Internet en vue d\'une connexion unique et il \('evite ainsi, par exemple, d\'\('etablir une connexion FTP, de la fermer, faire autre chose, puis d\'\('etablir encore cette connexion\&. Cette fonctionnalit\('e permet l\'acc\(`es \(`a des sites FTP surcharg\('es qui limitent le nombre de connexions simultan\('ees pour les utilisateurs anonymes\&. APT parall\('elise aussi les connexions \(`a diff\('erents h\(^otes pour tirer plus efficacement parti des sites \(`a faible bande passante\&.
.PP
Il est important d\'indiquer les sources par ordre de pr\('ef\('erence, la source principale apparaissant en premier\&. Un tri est fait, de la plus rapide \(`a la plus lente\ \&; par exemple, un c\('ed\('erom suivi par les h\(^otes d\'un r\('eseau local, puis les h\(^otes distants\&.
.PP
Voici quelques exemples\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://http\&.us\&.debian\&.org/debian stable main contrib non\-free
deb http://http\&.us\&.debian\&.org/debian dists/stable\-updates/
   
.fi
.if n \{\
.RE
.\}
.SH "LA SP\('ECIFICATION DES URI"
.PP
Les URI actuellement reconnus sont\ \&: cdrom, file, http et ftp\&.
.PP
file
.RS 4
Le proc\('ed\('e
file
permet qu\'un r\('epertoire arbitraire au sein du syst\(`eme de fichier soit consid\('er\('e comme une archive\&. On s\'en sert avec les montages NFS, les miroirs et les archives locaux\&.
.RE
.PP
cdrom
.RS 4
Le proc\('ed\('e
cdrom
permet l\'utilisation d\'un lecteur de c\('ed\('erom avec la possibilit\('e de changer de media\&. Utilisez le programme
\fBapt-cdrom\fR(8)
pour cr\('eer des entr\('ees dans la liste des sources\&.
.RE
.PP
http
.RS 4
Le proc\('ed\('e
http
indique un serveur HTTP comme archive\&. Si une variable d\'environnement
\fBhttp_proxy\fR
(au format http://server:port/) existe, le serveur mandataire indiqu\('e par
\fBhttp_proxy\fR
est utilis\('e\&. Quand un serveur mandataire HTTP/1\&.1 demande une authentification, on peut utiliser la cha\(^ine http://user:pass@server:port/\&. Notez qu\'il s\'agit d\'une m\('ethode d\'authentification peu s\(^ure\&.
.RE
.PP
ftp
.RS 4
Le proc\('ed\('e
ftp
indique un serveur FTP comme archive\&. Le fonctionnement en mode ftp est largement configurable\ \&; r\('ef\('erez\-vous \(`a la page de manuel de
\fBapt-cdrom\fR(8)
pour d\'autres informations\&. On remarquera qu\'on peut indiquer un mandataire ftp avec la variable d\'environnement
\fBftp_proxy\fR\&. On peut aussi sp\('ecifier un mandataire http (les serveurs mandataires http comprennent souvent les URL ftp) en utilisant cette m\('ethode et SEULEMENT cette m\('ethode\&. Les mandataires ftp utilisant http et qui sont sp\('ecifi\('es dans le fichier de configuration seront ignor\('es\&.
.RE
.PP
copy
.RS 4
Le proc\('ed\('e
copy
est identique au proc\('ed\('e
file
except\('e que les paquets sont copi\('es dans le cache du r\('epertoire au lieu d\'\(^etre utilis\('es directement depuis leur emplacement\&. C\'est utile aux gens qui utilisent un disque zip pour recopier des fichiers avec APT\&.
.RE
.PP
rsh, ssh
.RS 4
Le proc\('ed\('e rsh/ssh utilise rsh/ssh pour se connecter \(`a une machine distante en tant que tel utilisateur donn\('e et pour acc\('eder aux fichiers\&. Aucune authentification par mot de passe n\'est possible\ \&: il faut au pr\('ealable r\('egler ce probl\(`eme avec des cl\('es RSA ou bien rhosts\&. Pour l\'acc\(`es aux fichiers de la machine distante et le transfert, on utilise les commandes standard
\fBfind\fR
et
\fBdd\fR\&.
.RE
.SH "EXEMPLES"
.PP
Utiliser l\'archive stock\('ee localement (ou mont\('ee via NFS) dans /home/jason/debian pour stable/main, stable/contrib et stable/non\-free\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/jason/debian stable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Comme ci\-dessus, except\('e que cette ligne utilise la distribution \(Fo\ \&unstable\ \&\(Fc (d\('eveloppement)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/jason/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
La pr\('ec\('edente ligne, mais pour les sources\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb\-src file:/home/jason/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour acc\('eder \(`a l\'archive situ\('ee \(`a archive\&.debian\&.org, et n\'utiliser que la section hamm/main\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://archive\&.debian\&.org/debian\-archive hamm main
.fi
.if n \{\
.RE
.\}
.PP
Utiliser FTP pour acc\('eder \(`a l\'archive situ\('ee \(`a ftp\&.debian\&.org, dans le r\('epertoire debian, et n\'utiliser que la section stable/contrib\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian stable contrib
.fi
.if n \{\
.RE
.\}
.PP
Utiliser FTP pour acc\('eder \(`a l\'archive situ\('ee \(`a ftp\&.debian\&.org, dans le r\('epertoire debian, et n\'utiliser que la section unstable/contrib\&. Si cette ligne et celle de l\'exemple pr\('ec\('edent dans
sources\&.list
apparaissent, une seule session FTP sera utilis\('ee pour les deux lignes\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian unstable contrib
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour acc\('eder \(`a l\'archive situ\('ee \(`a nonus\&.debian\&.org, dans le r\('epertoire debian\-non\-US\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://nonus\&.debian\&.org/debian\-non\-US stable/non\-US main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour acc\('eder \(`a l\'archive situ\('ee \(`a nonus\&.debian\&.org, dans le r\('epertoire debian\-non\-US, et n\'utiliser que les fichiers trouv\('es dans
unstable/binary\-i386
pour les machines i386, dans
unstable/binary\-m68k
pour les machines m68k et ainsi de suite pour les autres architectures reconnues\&. [Notez que cet exemple montre seulement la mani\(`ere d\'utiliser la variable \(`a substituer, non\-us n\'\('etant plus structur\('e de cette mani\(`ere\&.]
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://ftp\&.de\&.debian\&.org/debian\-non\-US unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.SH "VOIR AUSSI"
.PP
\fBapt-cache\fR(8)
\fBapt.conf\fR(5)
.SH "BOGUES"
.PP
Voyez la
\m[blue]\fB page concernant les bogues d\'APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous voulez signaler un bogue, consultez le texte
/usr/share/doc/debian/bug\-reporting\&.txt
ou utilisez la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTION"
.PP
Philippe Batailler\&.
debian\-l10n\-french@lists\&.debian\&.org\&. 2005\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
Auteur.
.RE
.PP
\fBAPT team\fR
.RS 4
Auteur.
.RE
.SH "NOTES"
.IP " 1." 4
page concernant les bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
