'\" t
.\"     Title: sources.list
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 29
février 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "SOURCES\&.LIST" "5" "29 février 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sources.list \- Liste des sources de paquets
.SH "DESCRIPTION"
.PP
La liste des sources de paquets indique où trouver les archives du système de distribution de paquets utilisé\&. Pour l\*(Aqinstant, cette page de manuel ne documente que le système d\*(Aqempaquetage utilisé par le système Debian GNU/Linux\&. Ce fichier de contrôle est
/etc/apt/sources\&.list\&.
.PP
La liste des sources est conçue pour gérer un nombre quelconque de sources actives et différents média\&. Le fichier présente une source par ligne et la source préférée apparaît en premier\&. Le format de chaque ligne est\ \&:
type uri paramètres\&. Le premier élément,
type, détermine le format des
paramètres\&.
uri
est un identificateur universel de ressources (URI), qui est un sur\-ensemble du plus spécifique et bien connu repère universel de ressources, ou URL\&. La fin de la ligne peut être un commentaire commençant par un caractère #\&.
.SH "SOURCES.LIST.D"
.PP
Le répertoire
/etc/apt/sources\&.list\&.d
permet de spécifier des sources de paquets dans des fichiers distincts qui se terminent par
\&.list\&. Leur format est le même que celui du fichier
sources\&.list\&. Les noms de fichiers doivent se terminer par
\&.list
et ne peuvent contenir que des lettres (a\-z et A\-Z), des chiffres (0\-9), des caractères de soulignement (_), des tirets et des points\&. Dans le cas contraire, ils seront ignorés\&.
.SH "LES TYPES DEB ET DEB-SRC."
.PP
Le type
deb
décrit une archive Debian classique à deux niveaux,
distribution/composant\&.
distribution
peut prendre l\*(Aqune des valeurs suivantes\ \&:
stable,
unstable, ou
testing, et composant\ \&:
main,
contrib,
non\-free, ou
non\-us\&. Le type
deb\-src
décrit une archive de distribution de code source pour une distribution Debian dans le même format que le type
deb\&. Une ligne
deb\-src
est nécessaire pour récupérer les index des sources\&.
.PP
Le format d\*(Aqune entrée dans
sources\&.list
utilisant les types
deb
et
deb\-src
est\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
deb uri distribution [composant1] [composant2] [\&.\&.\&.]
.fi
.if n \{\
.RE
.\}
.PP
L\*(AqURI de type
deb
doit indiquer la base de la distribution Debian dans laquelle APT trouvera les informations dont il a besoin\&.
distribution
peut spécifier le chemin exact\ \&: dans ce cas, on doit omettre les composants et
distribution
doit se terminer par une barre oblique (/)\&. C\*(Aqest utile quand seule une sous\-section particulière de l\*(Aqarchive décrite par cet URI est intéressante\&. Quand
distribution
n\*(Aqindique pas un chemin exact, un
composant
au moins doit être présent\&.
.PP
distribution
peut aussi contenir une variable
$(ARCH), qui sera remplacée par l\*(Aqarchitecture Debian (i386, m68k, powerpc, \&.\&.\&.) sur laquelle s\*(Aqexécute le système\&. On peut ainsi utiliser un fichier
sources\&.list
qui ne dépend pas d\*(Aqune architecture\&. En général, ce n\*(Aqest intéressant que si l\*(Aqon indique un chemin exact\ \&; sinon
APT
crée automatiquement un URI en fonction de l\*(Aqarchitecture effective\&.
.PP
Puisqu\*(Aqon ne peut indiquer qu\*(Aqune seule distribution par ligne, il peut être nécessaire de disposer le même URI sur plusieurs lignes quand on veut accéder à un sous\-ensemble des distributions ou composants disponibles à cette adresse\&. APT trie les URI après avoir crée pour lui\-même la liste complète\ \&; il regroupe les références multiples au même hôte Internet en vue d\*(Aqune connexion unique et il évite ainsi, par exemple, d\*(Aqétablir une connexion FTP, de la fermer, faire autre chose, puis d\*(Aqétablir encore cette connexion\&. Cette fonctionnalité permet l\*(Aqaccès à des sites FTP surchargés qui limitent le nombre de connexions simultanées pour les utilisateurs anonymes\&. APT parallélise aussi les connexions à différents hôtes pour tirer plus efficacement parti des sites à faible bande passante\&.
.PP
Il est important d\*(Aqindiquer les sources par ordre de préférence, la source principale apparaissant en premier\&. Un tri est fait, de la plus rapide à la plus lente\ \&; par exemple, un CD suivi par les hôtes d\*(Aqun réseau local, puis les hôtes distants\&.
.PP
Exemples\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://http\&.us\&.debian\&.org/debian stable main contrib non\-free
deb http://http\&.us\&.debian\&.org/debian dists/stable\-updates/
   
.fi
.if n \{\
.RE
.\}
.SH "SPéCIFICATION DES URI"
.PP
Les types d\*(AqURI actuellement reconnus sont\ \&: cdrom, file, http, ftp, copy, ssh et rsh\&.
.PP
file
.RS 4
Le procédé
file
permet qu\*(Aqun répertoire arbitraire au sein du système de fichier soit considéré comme une archive\&. On s\*(Aqen sert avec les montages NFS, les miroirs et les archives locaux\&.
.RE
.PP
cdrom
.RS 4
Le procédé
cdrom
permet l\*(Aqutilisation d\*(Aqun lecteur de CD avec la possibilité de changer de media\&. Utilisez le programme
\fBapt-cdrom\fR(8)
pour créer des entrées dans la liste des sources\&.
.RE
.PP
http
.RS 4
Le procédé
http
indique un serveur HTTP comme archive\&. Si une variable d\*(Aqenvironnement
\fBhttp_proxy\fR
(au format http://server:port/) existe, le serveur mandataire indiqué par
\fBhttp_proxy\fR
est utilisé\&. Quand un serveur mandataire HTTP/1\&.1 demande une authentification, on peut utiliser la chaîne http://user:pass@server:port/\&. Notez qu\*(Aqil s\*(Aqagit d\*(Aqune méthode d\*(Aqauthentification peu sûre\&.
.RE
.PP
ftp
.RS 4
Le procédé
ftp
indique un serveur FTP comme archive\&. Le fonctionnement en mode ftp est largement configurable\ \&; référez\-vous à la page de manuel de
\fBapt-cdrom\fR(8)
pour d\*(Aqautres informations\&. On remarquera qu\*(Aqon peut indiquer un mandataire ftp avec la variable d\*(Aqenvironnement
\fBftp_proxy\fR\&. On peut aussi spécifier un mandataire http (les serveurs mandataires http comprennent souvent les URL ftp) en utilisant cette méthode et SEULEMENT cette méthode\&. Les mandataires ftp utilisant http et qui sont spécifiés dans le fichier de configuration seront ignorés\&.
.RE
.PP
copy
.RS 4
Le procédé
copy
est identique au procédé
file
excepté que les paquets sont copiés dans le cache du répertoire au lieu d\*(Aqêtre utilisés directement depuis leur emplacement\&. C\*(Aqest utile aux gens qui utilisent un disque zip pour recopier des fichiers avec APT\&.
.RE
.PP
rsh, ssh
.RS 4
Le procédé rsh/ssh utilise rsh/ssh pour se connecter à une machine distante en tant qu\*(Aqun certain utilisateur et pour accéder aux fichiers\&. Il est préférable au préalable de s\*(Aqarranger avec des clés RSA ou bien rhosts\&. Pour l\*(Aqaccès aux fichiers de la machine distante et le transfert, on utilise les commandes standard
\fBfind\fR
et
\fBdd\fR\&.
.RE
.PP
more recognizable URI types
.RS 4
APT can be extended with more methods shipped in other optional packages which should follow the nameing scheme
apt\-transport\-\fImethod\fR\&. The APT team e\&.g\&. maintains also the
apt\-transport\-https
package which provides access methods for https\-URIs with features similar to the http method, but other methods for using e\&.g\&. debtorrent are also available, see
\fBapt-transport-debtorrent\fR(1)\&.
.RE
.SH "EXEMPLES"
.PP
Utiliser l\*(Aqarchive stockée localement (ou montée via NFS) dans /home/jason/debian pour stable/main, stable/contrib et stable/non\-free\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/jason/debian stable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Comme ci\-dessus, excepté que cette ligne utilise la distribution \(Fo\ \&unstable\ \&\(Fc (développement)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/jason/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
La précédente ligne, mais pour les sources\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb\-src file:/home/jason/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour accéder à l\*(Aqarchive située à archive\&.debian\&.org, et n\*(Aqutiliser que la section hamm/main\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://archive\&.debian\&.org/debian\-archive hamm main
.fi
.if n \{\
.RE
.\}
.PP
Utiliser FTP pour accéder à l\*(Aqarchive située à ftp\&.debian\&.org, dans le répertoire debian, et n\*(Aqutiliser que la section stable/contrib\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian stable contrib
.fi
.if n \{\
.RE
.\}
.PP
Utiliser FTP pour accéder à l\*(Aqarchive située à ftp\&.debian\&.org, dans le répertoire debian, et n\*(Aqutiliser que la section unstable/contrib\&. Si cette ligne et celle de l\*(Aqexemple précédent dans
sources\&.list
apparaissent, une seule session FTP sera utilisée pour les deux lignes\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian unstable contrib
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour accéder à l\*(Aqarchive située à nonus\&.debian\&.org, dans le répertoire debian\-non\-US\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://nonus\&.debian\&.org/debian\-non\-US stable/non\-US main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour accéder à l\*(Aqarchive située à nonus\&.debian\&.org, dans le répertoire debian\-non\-US, et n\*(Aqutiliser que les fichiers trouvés dans
unstable/binary\-i386
pour les machines i386, dans
unstable/binary\-m68k
pour les machines m68k et ainsi de suite pour les autres architectures reconnues\&. [Notez que cet exemple montre seulement la manière d\*(Aqutiliser la variable à substituer, non\-us n\*(Aqétant plus structuré de cette manière\&.]
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://ftp\&.de\&.debian\&.org/debian\-non\-US unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.sp
.SH "VOIR AUSSI"
.PP
\fBapt-cache\fR(8)
\fBapt.conf\fR(5)
.SH "BOGUES"
.PP
\m[blue]\fBPage des bogues d\*(AqAPT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous souhaitez signaler un bogue à propos d\*(AqAPT, veuillez lire
/usr/share/doc/debian/bug\-reporting\&.txt
ou utiliser la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTEURS"
.PP
Jérôme Marant, Philippe Batailler, Christian Perrier
bubulle@debian\&.org
(2000, 2005, 2009, 2010), Équipe de traduction francophone de Debian
debian\-l10n\-french@lists\&.debian\&.org
.PP
Veuillez noter que cette traduction peut contenir des parties non traduites Cela est volontaire, pour éviter de perdre du contenu quand la traduction est légèrement en retard sur le contenu d\*(Aqorigine\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBÉquipe de développement d\*(AqAPT\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
Page des bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
