'\" t
.\"     Title: apt-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 14 December 2003
.\"    Manual: [FIXME: manual]
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-KEY" "8" "14 December 2003" "Linux" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-key \- APT キー管理ユーティリティ
.SH "SYNOPSIS"
.HP \w'\fBapt\-key\fR\ 'u
\fBapt\-key\fR [\fIcommand\fR/] [\fB\fIarguments\fR\fR...]
.SH "説明"
.PP


\fBapt\-key\fR
は、 apt が パッケージを認証するのに使用するキーの一覧を管理するのに使用します。 このキーで認証されたパッケージは、信頼するに足ると見なせるでしょう。
.SH "コマンド"
.PP
add \fIfilename\fR
.RS 4

信頼キー一覧に新しいキーを追加します。 このキーは
\fIfilename\fR
から読み込みますが、
\fIfilename\fR
を
\-
とすると、 標準入力から読み込みます。
.RE
.PP
del \fIkeyid\fR
.RS 4

信頼キー一覧からキーを削除します。
.RE
.PP
list
.RS 4

信頼キーを一覧表示します。
.RE
.PP
update
.RS 4

Debian アーカイブキーで、ローカルキーリングを更新し、 もう有効でないキーをキーリングから削除します。
.RE
.SH "ファイル"
.PP
/etc/apt/trusted\&.gpg
.RS 4
ローカル信頼キーのキーリング。 新しいキーはここに追加されます。
.RE
.PP
/etc/apt/trustdb\&.gpg
.RS 4
アーカイブキーのローカル信頼データベース
.RE
.PP
/usr/share/keyrings/debian\-archive\-keyring\&.gpg
.RS 4
Debian アーカイブ信頼キーのキーリング
.RE
.PP
/usr/share/keyrings/debian\-archive\-removed\-keys\&.gpg
.RS 4
削除された Debian アーカイブ信頼キーのキーリング
.RE
.SH "関連項目"
.PP

\fBapt-get\fR(8),
\fBapt-secure\fR(8)
.SH "バグ"
.PP
\m[blue]\fBAPT バグページ\fR\m[]\&\s-2\u[1]\d\s+2を ご覧ください。 APT のバグを報告する場合は、
/usr/share/doc/debian/bug\-reporting\&.txt
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "著者"
.PP
APT は the APT team
apt@packages\&.debian\&.org
によって 書かれました。
.SH "訳者"
.PP
倉澤 望
nabetaro@debian\&.or\&.jp
(2003\-2006), Debian JP Documentation ML
debian\-doc@debian\&.or\&.jp
.SH "AUTHOR"
.PP
\fBJason Gunthorpe\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
CopyrightCopyright \(co 1998-2001 Jason Gunthorpe
.br
.SH "NOTES"
.IP " 1." 4
APT バグページ
.RS 4
\%http://bugs.debian.org/src:apt
.RE
