'\" t
.\"     Title: apt-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 28 October 2008
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-KEY" "8" "28 October 2008" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-key \- APT キー管理ユーティリティ
.SH "SYNOPSIS"
.HP \w'\fBapt\-key\fR\ 'u
\fBapt\-key\fR [\fB\-\-keyring\ \fR\fB\fIfilename\fR\fR] [\fIcommand\fR] [\fB\fIarguments\fR\fR...]
.SH "説明"
.PP

\fBapt\-key\fR
は、apt が パッケージを認証するのに使用するキーの一覧を管理するのに使用します。このキーで認証されたパッケージは、信頼するに足ると見なせるでしょう。
.SH "コマンド"
.PP
add \fIfilename\fR
.RS 4
信頼キー一覧に新しいキーを追加します。このキーは
\fIfilename\fR
から読み込みますが、\fIfilename\fR
を
\-
とすると、標準入力から読み込みます。
.RE
.PP
del \fIkeyid\fR
.RS 4
信頼キー一覧からキーを削除します。
.RE
.PP
export \fIkeyid\fR
.RS 4
キー
\fIkeyid\fR
を標準出力に出力します。
.RE
.PP
exportall
.RS 4
信頼するキーをすべて標準出力に出力します。
.RE
.PP
list
.RS 4
信頼キーを一覧表示します。
.RE
.PP
finger
.RS 4
信頼キーのフィンガープリントを一覧表示します。
.RE
.PP
adv
.RS 4
gpg に上級オプションを渡します。adv \-\-recv\-key とすると、公開鍵をダウンロードできます。
.RE
.PP
update
.RS 4
Debian アーカイブキーで、ローカルキーリングを更新し、もう有効でないキーをキーリングから削除します。
.RE
.SH "オプション"
.PP
Note that options need to be defined before the commands described in the previous section\&.
.PP
\-\-keyring \fIfilename\fR
.RS 4
With this option it is possible to specify a specific keyring file the command should operate on\&. The default is that a command is executed on the
trusted\&.gpg
file as well as on all parts in the
trusted\&.gpg\&.d
directory, through
trusted\&.gpg
is the primary keyring which means that e\&.g\&. new keys are added to this one\&.
.RE
.SH "ファイル"
.PP
/etc/apt/trusted\&.gpg
.RS 4
Keyring of local trusted keys, new keys will be added here\&. Configuration Item:
Dir::Etc::Trusted\&.
.RE
.PP
/etc/apt/trusted\&.gpg\&.d/
.RS 4
File fragments for the trusted keys, additional keyrings can be stored here (by other packages or the administrator)\&. Configuration Item
Dir::Etc::TrustedParts\&.
.RE
.PP
/etc/apt/trustdb\&.gpg
.RS 4
アーカイブキーのローカル信頼データベースです。
.RE
.PP
/usr/share/keyrings/debian\-archive\-keyring\&.gpg
.RS 4
Debian アーカイブ信頼キーのキーリングです。
.RE
.PP
/usr/share/keyrings/debian\-archive\-removed\-keys\&.gpg
.RS 4
削除された Debian アーカイブ信頼キーのキーリングです。
.RE
.SH "関連項目"
.PP

\fBapt-get\fR(8),
\fBapt-secure\fR(8)
.SH "バグ"
.PP
\m[blue]\fBAPT バグページ\fR\m[]\&\s-2\u[1]\d\s+2
をご覧ください。 APT のバグを報告する場合は、
/usr/share/doc/debian/bug\-reporting\&.txt
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "著者"
.PP
APT は APT team
apt@packages\&.debian\&.org
によって書かれました。
.SH "訳者"
.PP
倉澤 望
nabetaro@debian\&.or\&.jp
(2003\-2006,2009), Debian JP Documentation ML
debian\-doc@debian\&.or\&.jp
.PP
Note that this translated document may contain untranslated parts\&. This is done on purpose, to avoid losing content when the translation is lagging behind the original content\&.
.SH "AUTHOR"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1998-2001 Jason Gunthorpe
.br
.SH "NOTES"
.IP " 1." 4
APT バグページ
.RS 4
\%http://bugs.debian.org/src:apt
.RE
