'\" t
.\"     Title: apt_preferences
.\"    Author: APT team
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04 May 2009
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT_PREFERENCES" "5" "04 May 2009" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt_preferences \- APT 設定制御ファイル
.SH "説明"
.PP
The APT preferences file
/etc/apt/preferences
and the fragment files in the
/etc/apt/preferences\&.d/
folder can be used to control which versions of packages will be selected for installation\&.
.PP
\fBsources.list\fR(5)
ファイルに複数のディストリビューション (stable
と
testing
など) が指定されていて、パッケージに対し複数のバージョンがインストールできることがあります。このとき APT は、利用できるバージョンごとに優先度を割り当てます。依存関係規則を条件として、\fBapt\-get\fR
は、最も高い優先度を持つバージョンをインストールするよう選択します。APT 設定ファイルは、APT がデフォルトで割り当てた、パッケージのバージョンの優先度を上書きします。その結果インストールするものの選択を、ユーザが選択できるようになります。
.PP
\fBsources.list\fR(5)
ファイルに複数の参照が書かれている場合、パッケージの同じバージョンのインスタンスが複数利用できる可能性があります。この場合、\fBapt\-get\fR
は
\fBsources.list\fR(5)
ファイルの初めの方に指定されているところからダウンロードします。APT 設定ファイルはバージョンの選択にのみ影響し、インスタンスの選択には影響しません。
.PP
Note that the files in the
/etc/apt/preferences\&.d
directory are parsed in alphanumeric ascending order and need to obey the following naming convention: The files have no or "pref" as filename extension and which only contain alphanumeric, hyphen (\-), underscore (_) and period (\&.) characters \- otherwise they will be silently ignored\&.
.SS "APT のデフォルト優先度の割り当て"
.PP
設定ファイルがなかったり、設定ファイルに特定のパッケージを割り当てるエントリがない場合、そのバージョンの優先度は、そのバージョンが属しているディストリビューションの優先度となります。デフォルトで他のディストリビューションより高い優先度を持つ、特定のディストリビューションを「ターゲットリリース」としておけます。後述する
/etc/apt/preferences
ファイルで設定した一般優先度よりもこれは優先されますが、pin 止めしたパッケージには及ばないことに注意してください。例えば以下のようになります。
.sp
.if n \{\
.RS 4
.\}
.nf
\fBapt\-get install \-t testing \fR\fB\fIsome\-package\fR\fR
.fi
.if n \{\
.RE
.\}
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
APT::Default\-Release "stable";
.fi
.if n \{\
.RE
.\}
.PP
ターゲットリリースが指定されると、APT は以下のアルゴリズムで、パッケージのバージョンの優先度を設定します。以下のように割り当てます。.PP
priority 100
.RS 4
(あるならば) 既にインストールされているバージョン。
.RE
.PP
priority 500
.RS 4
インストールされておらず、ターゲットリリースに含まれないバージョン。
.RE
.PP
priority 990
.RS 4
インストールされておらず、ターゲットリリースに含まれるバージョン。
.RE
.PP
ターゲットリリースが指定されていなければ、APT は単純にインストールしているパッケージのバージョンには 100 を、インストールしていないパッケージのバージョンには 500 を割り当てます。
.PP
APT は、インストールするパッケージのバージョンを決定するために、以下のルールを上から順番に適用します。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
有効なバージョンの優先度が 1000 を越えない場合、決してダウングレードしません。(「ダウングレード」は、現在のパッケージのバージョンよりも、小さいバージョンのものをインストールします。APT のデフォルト優先度が 1000 を越えないことに注意してください。そのような優先度は設定ファイルでのみ設定できます。また、パッケージのダウングレードは危険であることにも注意してください)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
最も高い優先度のバージョンをインストールします。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
同じ優先度のバージョンが複数存在する場合、最も新しいもの (最もバージョン番号が高いもの) をインストールします。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
優先度・バージョン番号が同じものが複数存在し、そのパッケージのメタデータが異なるか
\-\-reinstall
オプションが与えられている場合、インストールされていないものをインストールします。
.RE
.PP
よくある状況として、あるインストールされているパッケージのバージョン (優先度 100) が、\fBsources.list\fR(5)
ファイルのリストから得られるバージョン (優先度 500 か 990) よりも新しくないということがあります。この場合、\fBapt\-get install \fR\fB\fIsome\-package\fR\fR
や
\fBapt\-get upgrade\fR
を実行するとパッケージが更新されます。
.PP
まれに、インストールされているパッケージのバージョンが、\fI他の有効なバージョンよりも\fR新しい場合があります。この時
\fBapt\-get install \fR\fB\fIsome\-package\fR\fR
や
\fBapt\-get upgrade\fR
を実行しても、ダウングレードしません。
.PP
時々、インストールしているパッケージのバージョンが、ターゲットリリースに属するバージョンよりも新しく、他のディストリビューションよりも古い場合があります。そのようなパッケージに対して
\fBapt\-get install \fR\fB\fIsome\-package\fR\fR
や
\fBapt\-get upgrade\fR
を実行すると、パッケージは更新されます。この場合、インストールされているバージョンよりも、少なくとも\fIひとつ\fRは、高い優先度を持つ有効なパッケージがあるからです。
.SS "APT 設定の効果"
.PP
APT 設定ファイルを使うと、システム管理者が優先度を割り当てられるようになります。ファイルは、空白行で区切られた、複数行からなるレコードで構成されています。レコードは特定形式か、汎用形式のどちらかの形式をとります。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
特定形式は、優先度 ("Pin\-Priority") を、指定したパッケージの指定したバージョン (範囲) について割り当てます。例えば以下のレコードは、"5\&.8" で始まる
perl
パッケージを、高い優先度に設定します。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: perl
Pin: version 5\&.8*
Pin\-Priority: 1001
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
汎用形式は、与えられたディストリビューションにある、すべてのパッケージ (Release
ファイルに列挙したパッケージ) の優先度や、FQDNで指定した、特定のインターネットサイトから取得するパッケージの優先度を割り当てます。
.sp
APT 設定ファイルに書かれている汎用形式のエントリは、パッケージのグループについてのみ適用されます。例えば以下のレコードは、ローカルサイトにある全パッケージについて、高い優先度を割り当てます。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: origin ""
Pin\-Priority: 999
.fi
.if n \{\
.RE
.\}
.sp
注意: ここで使用しているキーワードは "origin" です。Release
ファイルに指定されたような、ディストリビューションの Origin と混同しないようにしてください。Release
ファイルにある "Origin:" タグは、インターネットアドレスではなく、"Debian" や "Ximian" といった作者やベンダ名です。
.sp
以下のレコードは、アーカイブ名が "unstable" となっているディストリビューションに属するパッケージを、すべて低い優先度に割り当てます。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=unstable
Pin\-Priority: 50
.fi
.if n \{\
.RE
.\}
.sp
以下のレコードは、コード名が "squeeze" となっているディストリビューションに属するパッケージを、すべて高い優先度に割り当てます。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release n=squeeze
Pin\-Priority: 900
.fi
.if n \{\
.RE
.\}
.sp
以下のレコードは、アーカイブ名が "stable" で、リリースバージョン番号が "3\&.0" となっているリリースに属するパッケージを、すべて高い優先度に割り当てます。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=stable, v=3\&.0
Pin\-Priority: 500
.fi
.if n \{\
.RE
.\}
.RE
.sp
.SS "APT が優先度に割り込む方法"
.PP
APT 設定ファイルで割り当てた優先度 (P) は、正負の整数でなくてはなりません。これは (おおざっぱにいうと) 以下のように解釈されます。.PP
P > 1000
.RS 4
パッケージがダウングレードしても、このバージョンのパッケージをインストール
.RE
.PP
990 < P <=1000
.RS 4
インストールされているバージョンの方が新しいことを除き、ターゲットリリースに含まれなくても、このバージョンのパッケージをインストール
.RE
.PP
500 < P <=990
.RS 4
ターゲットリリースに属するバージョンがあったり、インストールされているバージョンの方が新しいのでなければ、このバージョンのパッケージをインストール
.RE
.PP
100 < P <=500
.RS 4
他のディストリビューションに属するバージョンがあったり、インストールされているバージョンの方が新しいのでなければ、このバージョンのパッケージをインストール
.RE
.PP
0 < P <=100
.RS 4
このパッケージがインストールされていない場合、このバージョンのパッケージをインストール
.RE
.PP
P < 0
.RS 4
このバージョンのインストール禁止
.RE
.PP
特定形式のレコードが利用可能パッケージバージョンに一致した場合、最初のレコードが、パッケージバージョンの優先度を決定します。失敗して、汎用形式のレコードが利用可能パッケージバージョンに一致した場合、最初のレコードが、パッケージバージョンの優先度を決定します。
.PP
例えば、APT 設定ファイルの上の方に、以下のレコードが書かれていると仮定してください。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: perl
Pin: version 5\&.8*
Pin\-Priority: 1001

Package: *
Pin: origin ""
Pin\-Priority: 999

Package: *
Pin: release unstable
Pin\-Priority: 50
.fi
.if n \{\
.RE
.\}
.PP
すると、以下のように動作します。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
バージョン番号が "5\&.8" で始まっていれば、perl
の最新の利用可能パッケージがインストールされます。バージョン 5\&.8* が利用可能で、バージョン 5\&.9* がインストールされている場合、perl
はダウングレードされます。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ローカルシステムで有効な、perl
以外のどんなパッケージでも、他のバージョンより (たとえターゲットリリースに属していても) 優先度が高くなります。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ローカルシステムにはなくても
\fBsources.list\fR(5)
に列挙されたサイトにあるバージョンで、unstable
ディストリビューションに属しているパッケージは、インストールするよう選択され、既にインストールされているバージョンがない場合にのみインストールされます。
.RE
.sp
.SS "パッケージのバージョンとディストリビューションプロパティの決定"
.PP
\fBsources.list\fR(5)
ファイルに列挙した場所では、その場所で利用できるパッケージを記述した、Packages
ファイルや
Release
ファイルを提供します。
.PP
Packages
ファイルは通常
\&.\&.\&./dists/\fIdist\-name\fR/\fIcomponent\fR/\fIarch\fR
ディレクトリにあります。例えば、\&.\&.\&./dists/stable/main/binary\-i386/Packages
です。これは、ディレクトリにある利用可能パッケージごとに、複数行のレコードからできています。APT 優先度の設定は、レコードごとに以下の 2 行だけです。.PP
Package: 行
.RS 4
パッケージ名
.RE
.PP
Version: 行
.RS 4
その名前のパッケージのバージョン番号
.RE
.PP
The
Release
file is normally found in the directory
\&.\&.\&./dists/\fIdist\-name\fR: for example,
\&.\&.\&./dists/stable/Release, or
\&.\&.\&./dists/woody/Release\&. It consists of a single multi\-line record which applies to
\fIall\fR
of the packages in the directory tree below its parent\&. Unlike the
Packages
file, nearly all of the lines in a
Release
file are relevant for setting APT priorities:
.PP
Archive: 行や Suite: 行
.RS 4
names the archive to which all the packages in the directory tree belong\&. For example, the line "Archive: stable" or "Suite: stable" specifies that all of the packages in the directory tree below the parent of the
Release
file are in a
stable
archive\&. Specifying this value in the APT preferences file would require the line:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release a=stable
.fi
.if n \{\
.RE
.\}
.RE
.PP
Codename: 行
.RS 4
names the codename to which all the packages in the directory tree belong\&. For example, the line "Codename: squeeze" specifies that all of the packages in the directory tree below the parent of the
Release
file belong to a version named
squeeze\&. Specifying this value in the APT preferences file would require the line:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release n=squeeze
.fi
.if n \{\
.RE
.\}
.RE
.PP
Version: 行
.RS 4
リリースバージョン名です。例えば、このツリーのパッケージが、GNU/Linux リリースバージョン 3\&.0 に属するとします。通常
testing
ディストリビューションや
unstable
ディストリビューションには、まだリリースされていないので、バージョン番号が付きません。APT 設定ファイルでこれを指定するには、以下の行のいずれかが必要になります。
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release v=3\&.0
Pin: release a=stable, v=3\&.0
Pin: release 3\&.0
.fi
.if n \{\
.RE
.\}
.RE
.PP
Component: 行
.RS 4
Release
ファイルの、ディレクトリツリーにあるパッケージのライセンスコンポーネント名です。例えば、"Component: main" という行は、このディレクトリ以下の全ファイルが、main
コンポーネント (Debian フリーソフトウェアガイドラインの元でライセンスされている) であることを表します。APT 設定ファイルでこのコンポーネントを指定するには、以下の行が必要になります。
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release c=main
.fi
.if n \{\
.RE
.\}
.RE
.PP
Origin: 行
.RS 4
Release
ファイルのディレクトリツリーにあるパッケージの提供者名です。ほとんど共通で、Debian
です。APT 設定ファイルでこの提供者を指定するには、以下の行が必要になります。
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release o=Debian
.fi
.if n \{\
.RE
.\}
.RE
.PP
Label: 行
.RS 4
Release
ファイルのディレクトリツリーにあるパッケージのラベル名です。ほとんど共通で
Debian
です。APT 設定ファイルでこのラベルを指定するには、以下の行が必要になります。
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release l=Debian
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBsources.list\fR(5)
ファイルに列挙された場所から取得した
Packages
ファイルや
Release
ファイルはすべて、/var/lib/apt/lists
ディレクトリや、apt\&.conf
ファイルの
Dir::State::Lists
変数で指定した場所に取得されます。例えば、debian\&.lcs\&.mit\&.edu_debian_dists_unstable_contrib_binary\-i386_Release
ファイルは、debian\&.lcs\&.mit\&.edu
から取得した、unstable
ディストリビューションで、contrib
コンポーネントな、binary\-i386
アーキテクチャ用の
Release
ファイルを含んでいます。
.SS "APT 設定レコードのオプション行"
.PP
APT 設定ファイルのレコードごとに、任意で
Explanation:
で始まる行を持てます。これは、コメント用の場所を確保します。
.PP
The
Pin\-Priority:
line in each APT preferences record is optional\&. If omitted, APT assigns a priority of 1 less than the last value specified on a line beginning with
Pin\-Priority: release \&.\&.\&.\&.
.SH "サンプル"
.SS "安定版の追跡"
.PP
The following APT preferences file will cause APT to assign a priority higher than the default (500) to all package versions belonging to a
stable
distribution and a prohibitively low priority to package versions belonging to other
Debian
distributions\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Explanation: Uninstall or do not install any Debian\-originated
Explanation: package versions other than those in the stable distro
Package: *
Pin: release a=stable
Pin\-Priority: 900

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
With a suitable
\fBsources.list\fR(5)
file and the above preferences file, any of the following commands will cause APT to upgrade to the latest
stable
version(s)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpackage\-name\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
The following command will cause APT to upgrade the specified package to the latest version from the
testing
distribution; the package will not be upgraded again unless this command is given again\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpackage\fR/testing
.fi
.if n \{\
.RE
.\}
.sp
.SS "テスト版や不安定版の追跡"
.PP
The following APT preferences file will cause APT to assign a high priority to package versions from the
testing
distribution, a lower priority to package versions from the
unstable
distribution, and a prohibitively low priority to package versions from other
Debian
distributions\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=testing
Pin\-Priority: 900

Package: *
Pin: release a=unstable
Pin\-Priority: 800

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
With a suitable
\fBsources.list\fR(5)
file and the above preferences file, any of the following commands will cause APT to upgrade to the latest
testing
version(s)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpackage\-name\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
The following command will cause APT to upgrade the specified package to the latest version from the
unstable
distribution\&. Thereafter,
\fBapt\-get upgrade\fR
will upgrade the package to the most recent
testing
version if that is more recent than the installed version, otherwise, to the most recent
unstable
version if that is more recent than the installed version\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpackage\fR/unstable
.fi
.if n \{\
.RE
.\}
.sp
.SS "Tracking the evolution of a codename release"
.PP
The following APT preferences file will cause APT to assign a priority higher than the default (500) to all package versions belonging to a specified codename of a distribution and a prohibitively low priority to package versions belonging to other
Debian
distributions, codenames and archives\&. Note that with this APT preference APT will follow the migration of a release from the archive
testing
to
stable
and later
oldstable\&. If you want to follow for example the progress in
testing
notwithstanding the codename changes you should use the example configurations above\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Explanation: Uninstall or do not install any Debian\-originated package versions
Explanation: other than those in the distribution codenamed with squeeze or sid
Package: *
Pin: release n=squeeze
Pin\-Priority: 900

Explanation: Debian unstable is always codenamed with sid
Package: *
Pin: release a=sid
Pin\-Priority: 800

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
With a suitable
\fBsources.list\fR(5)
file and the above preferences file, any of the following commands will cause APT to upgrade to the latest version(s) in the release codenamed with
squeeze\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpackage\-name\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
The following command will cause APT to upgrade the specified package to the latest version from the
sid
distribution\&. Thereafter,
\fBapt\-get upgrade\fR
will upgrade the package to the most recent
squeeze
version if that is more recent than the installed version, otherwise, to the most recent
sid
version if that is more recent than the installed version\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpackage\fR/sid
.fi
.if n \{\
.RE
.\}
.sp
.SH "ファイル"
.PP
/etc/apt/preferences
.RS 4
Version preferences file\&. This is where you would specify "pinning", i\&.e\&. a preference to get certain packages from a separate source or from a different version of a distribution\&. Configuration Item:
Dir::Etc::Preferences\&.
.RE
.PP
/etc/apt/preferences\&.d/
.RS 4
File fragments for the version preferences\&. Configuration Item:
Dir::Etc::PreferencesParts\&.
.RE
.SH "関連項目"
.PP
\fBapt-get\fR(8)
\fBapt-cache\fR(8)
\fBapt.conf\fR(5)
\fBsources.list\fR(5)
.SH "バグ"
.PP
\m[blue]\fBAPT バグページ\fR\m[]\&\s-2\u[1]\d\s+2
をご覧ください。 APT のバグを報告する場合は、
/usr/share/doc/debian/bug\-reporting\&.txt
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "訳者"
.PP
倉澤 望
nabetaro@debian\&.or\&.jp
(2003\-2006,2009), Debian JP Documentation ML
debian\-doc@debian\&.or\&.jp
.PP
Note that this translated document may contain untranslated parts\&. This is done on purpose, to avoid losing content when the translation is lagging behind the original content\&.
.SH "AUTHOR"
.PP
\fBAPT team\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
APT バグページ
.RS 4
\%http://bugs.debian.org/src:apt
.RE
