'\" t
.\"     Title: sources.list
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 29
February 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "SOURCES\&.LIST" "5" "29 February 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sources.list \- APT 用パッケージリソースリスト
.SH "説明"
.PP
The package resource list is used to locate archives of the package distribution system in use on the system\&. At this time, this manual page documents only the packaging system used by the Debian GNU/Linux system\&. This control file is
/etc/apt/sources\&.list\&.
.PP
The source list is designed to support any number of active sources and a variety of source media\&. The file lists one source per line, with the most preferred source listed first\&. The format of each line is:
type uri args
The first item,
type
determines the format for
args\&.
uri
is a Universal Resource Identifier (URI), which is a superset of the more specific and well\-known Universal Resource Locator, or URL\&. The rest of the line can be marked as a comment by using a #\&.
.SH "SOURCES.LIST.D"
.PP
The
/etc/apt/sources\&.list\&.d
directory provides a way to add sources\&.list entries in separate files\&. The format is the same as for the regular
sources\&.list
file\&. File names need to end with
\&.list
and may only contain letters (a\-z and A\-Z), digits (0\-9), underscore (_), hyphen (\-) and period (\&.) characters\&. Otherwise they will be silently ignored\&.
.SH "DEB タイプと DEB-SRC タイプ"
.PP
The
deb
type describes a typical two\-level Debian archive,
distribution/component\&. Typically,
distribution
is generally one of
stable
unstable
or
testing
while component is one of
main
contrib
non\-free
or
non\-us\&. The
deb\-src
type describes a debian distribution\*(Aqs source code in the same form as the
deb
type\&. A
deb\-src
line is required to fetch source indexes\&.
.PP
The format for a
sources\&.list
entry using the
deb
and
deb\-src
types is:
.sp
.if n \{\
.RS 4
.\}
.nf
deb uri distribution [component1] [component2] [\&.\&.\&.]
.fi
.if n \{\
.RE
.\}
.PP
The URI for the
deb
type must specify the base of the Debian distribution, from which APT will find the information it needs\&.
distribution
can specify an exact path, in which case the components must be omitted and
distribution
must end with a slash (/)\&. This is useful for when the case only a particular sub\-section of the archive denoted by the URI is of interest\&. If
distribution
does not specify an exact path, at least one
component
must be present\&.
.PP
distribution
は、$(ARCH)
変数を含む場合があります。$(ARCH)
変数は、システムで使用している Debian アーキテクチャ (i386, m68k, powerpc, \&.\&.\&.) に展開されます。これにより、アーキテクチャに依存しない
sources\&.list
ファイルを使用できます。一般的に、これは正しいパスを指定するときに気にするだけです。そうでない場合は、APT
は現在のアーキテクチャで URI を自動的に生成します。
.PP
有効な全 distribution, component の場所から、一部が必要な場合、1 行につき 1 distribution しか指定できないため、同じ URI の行を複数記述することになるでしょう。APT は内部で URI リストを生成してから、並べ替えます。そして、同じインターネットホストに対しては複数の参照をまとめます。例えば FTP 接続後、切断してからまた同じホストに再接続するといった、効率の悪いことをせずに、1 接続にまとめます。この機能は、同時接続匿名ユーザ数を制限している、混んでいる FTP サイトにアクセスするのに便利です。APT は、帯域の狭いサイトを効率よく扱うのに、異なるホストへは、接続を並行して行うようにもしています。
.PP
最優先する取得元を最初に記述するというように、優先順に取得元を記述するのは重要です。一般的には、スピードの速い順に並べることになる (例えば、CD\-ROM に続いてローカルネットワークのホスト、さらに続いて彼方のインターネットホスト) でしょう。
.PP
例:
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://http\&.us\&.debian\&.org/debian stable main contrib non\-free
deb http://http\&.us\&.debian\&.org/debian dists/stable\-updates/
   
.fi
.if n \{\
.RE
.\}
.SH "URI の仕様"
.PP
現在認識する URI タイプは、cdrom, file, http, ftp, copy, ssh, rsh です。.PP
ファイル
.RS 4
file スキームは、システム内の任意のディレクトリを、アーカイブとして扱えるようにします。これは NFS マウントやローカルミラーで便利です。
.RE
.PP
cdrom
.RS 4
cdrom スキームは、APT がローカル CD\-ROM ドライブを、メディア交換しながら使えるようにします。取得元リストに cdrom エントリを追加するには、\fBapt-cdrom\fR(8)
プログラムを使用してください。
.RE
.PP
http
.RS 4
The http scheme specifies an HTTP server for the archive\&. If an environment variable
\fBhttp_proxy\fR
is set with the format http://server:port/, the proxy server specified in
\fBhttp_proxy\fR
will be used\&. Users of authenticated HTTP/1\&.1 proxies may use a string of the format http://user:pass@server:port/\&. Note that this is an insecure method of authentication\&.
.RE
.PP
ftp
.RS 4
ftp スキームは、アーカイブに FTP サーバを指定します。APT の FTP の振る舞いは、高度に設定できます。詳細は、\fBapt.conf\fR(5)
のマニュアルページをご覧ください。ftp プロキシは、\fBftp_proxy\fR
環境変数で指定することにご注意ください。この方法用に、さらにこの方法でしか使用しないのに、http プロキシを使用することができます (http プロキシサーバは大抵 ftp urlも理解できます)。設定ファイルで http を使用する際に、ftp プロキシを使用するよう設定してあっても無視されます。
.RE
.PP
copy
.RS 4
copy スキームは、file スキームと同様ですが、パッケージをその場で使用せず、キャッシュディレクトリにコピーするところが違います。zip ディスクを使用していて、APT でコピーを行う場合に便利です。
.RE
.PP
rsh, ssh
.RS 4
rsh/ssh メソッドは、与えられたユーザでリモートホストに接続し、ファイルにアクセスするのに rsh/ssh を使用します。あらかじめ RSA キーや rhosts の配置しておくと良いでしょう。リモートホストのファイルへのアクセスの際、ファイル転送に標準の
\fBfind\fR
コマンドや
\fBdd\fR
コマンドを使用します。
.RE
.PP
more recognizable URI types
.RS 4
APT can be extended with more methods shipped in other optional packages which should follow the nameing scheme
apt\-transport\-\fImethod\fR\&. The APT team e\&.g\&. maintains also the
apt\-transport\-https
package which provides access methods for https\-URIs with features similar to the http method, but other methods for using e\&.g\&. debtorrent are also available, see
\fBapt-transport-debtorrent\fR(1)\&.
.RE
.SH "サンプル"
.PP
/home/jason/debian に格納されている stable/main, stable/contrib, stable/non\-free 用のローカル (または NFS) アーカイブを使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/jason/debian stable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
上記同様ですが、不安定版 (開発版) を使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/jason/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
上記のソース行
.sp
.if n \{\
.RS 4
.\}
.nf
deb\-src file:/home/jason/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
archive\&.debian\&.org のアーカイブに HTTP アクセスし、hamm/main のみを使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://archive\&.debian\&.org/debian\-archive hamm main
.fi
.if n \{\
.RE
.\}
.PP
ftp\&.debian\&.org のアーカイブに FTP アクセスし、debian ディレクトリ以下の stable/contrib のみを使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian stable contrib
.fi
.if n \{\
.RE
.\}
.PP
Uses FTP to access the archive at ftp\&.debian\&.org, under the debian directory, and uses only the unstable/contrib area\&. If this line appears as well as the one in the previous example in
sources\&.list
a single FTP session will be used for both resource lines\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian unstable contrib
.fi
.if n \{\
.RE
.\}
.PP
nonus\&.debian\&.org のアーカイブに HTTP アクセスし、debian\-non\-US ディレクトリ以下を使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://nonus\&.debian\&.org/debian\-non\-US stable/non\-US main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
nonus\&.debian\&.org のアーカイブに HTTP アクセスし、debian\-non\-US ディレクトリ以下を使用します。また、i386 マシンでは
unstable/binary\-i386
以下にあるファイル、m68k マシンでは
unstable/binary\-m68k
以下にあるファイル、その他サポートするアーキテクチャごとのファイルのみ使用します。[このサンプルは変数展開の使用法の説明でしかないことに注意してください。non\-us はこのような構造になっていません]
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://ftp\&.de\&.debian\&.org/debian\-non\-US unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.sp
.SH "関連項目"
.PP
\fBapt-cache\fR(8)
\fBapt.conf\fR(5)
.SH "バグ"
.PP
\m[blue]\fBAPT バグページ\fR\m[]\&\s-2\u[1]\d\s+2
をご覧ください。 APT のバグを報告する場合は、
/usr/share/doc/debian/bug\-reporting\&.txt
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "訳者"
.PP
倉澤 望
nabetaro@debian\&.or\&.jp
(2003\-2006,2009), Debian JP Documentation ML
debian\-doc@debian\&.or\&.jp
.PP
Note that this translated document may contain untranslated parts\&. This is done on purpose, to avoid losing content when the translation is lagging behind the original content\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT team\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
APT バグページ
.RS 4
\%http://bugs.debian.org/src:apt
.RE
